package br.com.lojadafatima.InterfacesPessoa;

import br.com.lojadafatima.ClassesFerramentas.ClasseDatas;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.ClassesFerramentas.PermiteNumerosPontoBarra;
import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.Pessoa.ClasseFornecedor;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceFornecedor extends javax.swing.JDialog {

    MaskFormatter data, cnpj, fone, cep;
    private java.awt.Frame primeiratela;
    Preenche preenche = new Preenche();
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    LimpaCamposTela limpar = new LimpaCamposTela();
    ClasseDatas datas = new ClasseDatas();
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    ClasseFornecedor fornecedor = new ClasseFornecedor();
    MensagensUsuario msg = new MensagensUsuario();

    public InterfaceFornecedor(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(usuario);
        analisausuario();
        TfNrCNPJKeyReleased(null);
        valida.validacamposCancelar(PnCadastro, PnBotoes);
        preenche.PreencheJComboBox(CbEstado, fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().buscarestadosjcombobox());
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        TbPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TfBairro.setDocument(new NaoPermiteAspasSimples());
        TfDsEmail.setDocument(new NaoPermiteAspasSimples());
        TfLogradouro.setDocument(new NaoPermiteAspasSimples());
        TfNomeFantasia.setDocument(new NaoPermiteAspasSimples());
        TfNumero.setDocument(new NaoPermiteAspasSimples());
        TfRazaoSocial.setDocument(new NaoPermiteAspasSimples());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PopupMenuRetorna = new javax.swing.JPopupMenu();
        MnItRetorna = new javax.swing.JMenuItem();
        TabbedPaneFornecedor = new javax.swing.JTabbedPane();
        PnCadastro = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TfNomeFantasia = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TfRazaoSocial = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        try{
            cnpj = new MaskFormatter("##.###.###/####-##");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel localizar");
        }
        TfNrCNPJ = new JFormattedTextField(cnpj);
        jLabel16 = new javax.swing.JLabel();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel localizar");
        }
        TfDtFund = new JFormattedTextField(data);
        jLabel14 = new javax.swing.JLabel();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel localizar");
        }
        TfDtCadastro = new JFormattedTextField(data);
        jSeparator1 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        try{
            fone = new MaskFormatter("(##)####-####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel localizar");
        }
        TfNrTelefone = new JFormattedTextField(fone);
        jLabel20 = new javax.swing.JLabel();
        jCbOpTelefone = new javax.swing.JComboBox();
        jBtAddTelefone = new javax.swing.JButton();
        jBtDelTelefone = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbTelefone = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        TfDsEmail = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jCbOpEmail = new javax.swing.JComboBox();
        jBtAddEmail = new javax.swing.JButton();
        jBtDelEmail = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbEmail = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        TfLogradouro = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TfNumero = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        TfBairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        CbEstado = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        CbCidade = new javax.swing.JComboBox();
        PnBotoes = new javax.swing.JPanel();
        BtGravar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtIncluir = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        BtCadCidade = new javax.swing.JButton();
        BtCadEstado = new javax.swing.JButton();
        try{
            cep = new MaskFormatter("#####-###");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel localizar");
        }
        TfCEP = new JFormattedTextField(cep);
        LbCNPJValido = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        LbNotificacao = new javax.swing.JLabel();
        PnConsulta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        CbPesquisa = new javax.swing.JComboBox();
        TfPesquisa = new javax.swing.JTextField();
        BtPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPesquisa = new javax.swing.JTable();

        MnItRetorna.setText("Carregar dados");
        MnItRetorna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItRetornaActionPerformed(evt);
            }
        });
        PopupMenuRetorna.add(MnItRetorna);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Fornecedor - Software Loja da Fátima");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Código");

        TfCodigo.setEditable(false);

        jLabel7.setText("Nome Fantasia*");

        TfNomeFantasia.setName("NM_FANTASIA"); // NOI18N
        TfNomeFantasia.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfNomeFantasiaKeyTyped(evt);
            }
        });

        jLabel8.setText("Razão Social");

        TfRazaoSocial.setName("DS_RAZAO_SOCIAL"); // NOI18N
        TfRazaoSocial.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfRazaoSocialKeyTyped(evt);
            }
        });

        jLabel9.setText("Nr. CNPJ*");

        TfNrCNPJ.setName("NR_CNPJ"); // NOI18N
        TfNrCNPJ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfNrCNPJFocusLost(evt);
            }
        });
        TfNrCNPJ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfNrCNPJKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfNrCNPJKeyTyped(evt);
            }
        });

        jLabel16.setText("Data de Fundação");

        TfDtFund.setName("DT_NASC"); // NOI18N
        TfDtFund.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfDtFundFocusLost(evt);
            }
        });

        jLabel14.setText("Data do Cadastro");

        TfDtCadastro.setEditable(false);
        TfDtCadastro.setName("DT_CADASTRO"); // NOI18N

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel23.setText("Nr. Telefone:");

        TfNrTelefone.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfNrTelefoneFocusLost(evt);
            }
        });

        jLabel20.setText("Tipo");

        jCbOpTelefone.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PRINCIPAL", "CELULAR", "ALTERNATIVO" }));

        jBtAddTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        jBtAddTelefone.setText("Adicionar");
        jBtAddTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddTelefoneActionPerformed(evt);
            }
        });

        jBtDelTelefone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        jBtDelTelefone.setText("Excluir");
        jBtDelTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDelTelefoneActionPerformed(evt);
            }
        });

        TbTelefone.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sel.", "Nr. Telefone", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbTelefone.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TbTelefone);

        jLabel24.setText("E-mail");

        TfDsEmail.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfDsEmailFocusLost(evt);
            }
        });
        TfDsEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDsEmailKeyTyped(evt);
            }
        });

        jLabel25.setText("Tipo");

        jCbOpEmail.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "PRINCIPAL", "ALTERNATIVO" }));

        jBtAddEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        jBtAddEmail.setText("Adicionar");
        jBtAddEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtAddEmailActionPerformed(evt);
            }
        });

        jBtDelEmail.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        jBtDelEmail.setText("Excluir");
        jBtDelEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtDelEmailActionPerformed(evt);
            }
        });

        TbEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Sel.", "E-mail", "Tipo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Boolean.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbEmail.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TbEmail);

        jLabel10.setText("Rua/Avenida*");

        TfLogradouro.setName("DS_RUA"); // NOI18N
        TfLogradouro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfLogradouroKeyTyped(evt);
            }
        });

        jLabel11.setText("Número*");

        jLabel13.setText("CEP*");

        TfNumero.setName("DS_NUMERO"); // NOI18N
        TfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfNumeroKeyTyped(evt);
            }
        });

        jLabel12.setText("Bairro*");

        TfBairro.setName("DS_BAIRRO"); // NOI18N
        TfBairro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfBairroKeyTyped(evt);
            }
        });

        jLabel17.setText("Estado");

        CbEstado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbEstadoMouseClicked(evt);
            }
        });
        CbEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbEstadoActionPerformed(evt);
            }
        });

        jLabel18.setText("Cidade");

        BtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/salvar.png"))); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.setName("Gravar"); // NOI18N
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/editar.png"))); // NOI18N
        BtAlterar.setText("Alterar Dados");
        BtAlterar.setName("Alterar"); // NOI18N
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluir.setText("Cadastrar Fornecedor");
        BtIncluir.setName("Incluir"); // NOI18N
        BtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirActionPerformed(evt);
            }
        });

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/lixeira.png"))); // NOI18N
        BtExcluir.setText("Excluir Fornecedor");
        BtExcluir.setName("Excluir"); // NOI18N
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/cancelar.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.setName("Cancelar"); // NOI18N
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotoesLayout = new javax.swing.GroupLayout(PnBotoes);
        PnBotoes.setLayout(PnBotoesLayout);
        PnBotoesLayout.setHorizontalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotoesLayout.createSequentialGroup()
                .addComponent(BtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnBotoesLayout.setVerticalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(BtAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        BtCadCidade.setText("Adicionar Cidade");
        BtCadCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadCidadeActionPerformed(evt);
            }
        });

        BtCadEstado.setText("Adicionar Estado");
        BtCadEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadEstadoActionPerformed(evt);
            }
        });

        TfCEP.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCEPFocusLost(evt);
            }
        });

        LbCNPJValido.setText("Informa CNPJ Valido");

        LbNotificacao.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacao)
        );

        javax.swing.GroupLayout PnCadastroLayout = new javax.swing.GroupLayout(PnCadastro);
        PnCadastro.setLayout(PnCadastroLayout);
        PnCadastroLayout.setHorizontalGroup(
            PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnCadastroLayout.createSequentialGroup()
                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(PnCadastroLayout.createSequentialGroup()
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfNrCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel9))
                                .addGap(18, 18, 18)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addComponent(TfDtFund, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnCadastroLayout.createSequentialGroup()
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(TfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TfDtCadastro)))
                            .addComponent(jLabel10)
                            .addComponent(jLabel12)
                            .addGroup(PnCadastroLayout.createSequentialGroup()
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addComponent(TfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnCadastroLayout.createSequentialGroup()
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(CbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18)
                                    .addComponent(CbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtCadCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(TfNomeFantasia)
                                .addComponent(TfRazaoSocial, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                                .addComponent(TfBairro)
                                .addComponent(TfLogradouro))
                            .addComponent(LbCNPJValido))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jCbOpTelefone, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PnCadastroLayout.createSequentialGroup()
                                        .addComponent(jBtAddEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                                        .addComponent(jBtDelEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCbOpEmail, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TfDsEmail))
                                .addComponent(jLabel23)
                                .addGroup(PnCadastroLayout.createSequentialGroup()
                                    .addComponent(jBtAddTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jBtDelTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel20))
                            .addComponent(TfNrTelefone))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(BtCadEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(PnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        PnCadastroLayout.setVerticalGroup(
            PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnCadastroLayout.createSequentialGroup()
                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnCadastroLayout.createSequentialGroup()
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(PnCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(PnCadastroLayout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TfDtCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfNomeFantasia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(1, 1, 1)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfRazaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel16))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TfNrCNPJ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TfDtFund, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LbCNPJValido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PnCadastroLayout.createSequentialGroup()
                                        .addGap(26, 26, 26)
                                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TfCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(PnCadastroLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel13))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CbEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CbCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtCadEstado)
                            .addComponent(BtCadCidade)))
                    .addGroup(PnCadastroLayout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfNrTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbOpTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtAddTelefone)
                                    .addComponent(jBtDelTelefone)))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(36, 36, 36)
                        .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnCadastroLayout.createSequentialGroup()
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfDsEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel25)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCbOpEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jBtAddEmail)
                                    .addComponent(jBtDelEmail))
                                .addGap(12, 12, 12)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(PnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TabbedPaneFornecedor.addTab("Cadastro", PnCadastro);

        jLabel2.setText("Consulta por:");

        CbPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos os Fornecedores", "Código", "Nome Fantasia", "CNPJ" }));
        CbPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPesquisaActionPerformed(evt);
            }
        });

        TfPesquisa.setEnabled(false);

        BtPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesquisa.setText("Pesquisar");
        BtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisaActionPerformed(evt);
            }
        });

        TbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Fantasia", "CNPJ", "Data do Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbPesquisa.setComponentPopupMenu(PopupMenuRetorna);
        TbPesquisa.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbPesquisa);

        javax.swing.GroupLayout PnConsultaLayout = new javax.swing.GroupLayout(PnConsulta);
        PnConsulta.setLayout(PnConsultaLayout);
        PnConsultaLayout.setHorizontalGroup(
            PnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(PnConsultaLayout.createSequentialGroup()
                        .addComponent(CbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtPesquisa, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE))
                    .addGroup(PnConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnConsultaLayout.setVerticalGroup(
            PnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        TabbedPaneFornecedor.addTab("Consulta", PnConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPaneFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneFornecedor)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBtAddTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddTelefoneActionPerformed
        preenche.PreencheJTableEmailOuTelefone(TfNrTelefone, jCbOpTelefone, TbTelefone);
    }//GEN-LAST:event_jBtAddTelefoneActionPerformed

    private void jBtDelTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDelTelefoneActionPerformed
        preenche.RemoveDaJTableEmailOuTelefone(TbTelefone);
    }//GEN-LAST:event_jBtDelTelefoneActionPerformed

    private void jBtAddEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtAddEmailActionPerformed
        preenche.PreencheJTableEmailOuTelefone(TfDsEmail, jCbOpEmail, TbEmail);
    }//GEN-LAST:event_jBtAddEmailActionPerformed

    private void jBtDelEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtDelEmailActionPerformed
        preenche.RemoveDaJTableEmailOuTelefone(TbEmail);
    }//GEN-LAST:event_jBtDelEmailActionPerformed

    private void TfNrTelefoneFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfNrTelefoneFocusLost
        valida.FocusLostDeCamposFormatados(TfNrTelefone);
    }//GEN-LAST:event_TfNrTelefoneFocusLost

    private void BtCadEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadEstadoActionPerformed
        final InterfaceEstado tela = new InterfaceEstado(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                preenche.PreencheJComboBox(CbEstado, fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().buscarestadosjcombobox());
            }
        });
    }//GEN-LAST:event_BtCadEstadoActionPerformed

    private void TfNrCNPJFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfNrCNPJFocusLost
        valida.FocusLostDeCamposFormatados(TfNrCNPJ);
        fornecedor.getPessoajur().setCnpj(TfNrCNPJ.getText());
        if (valida.CampoTotalmentePreenchido(fornecedor.getPessoajur().getCnpj())) {
            if (!fornecedor.getPessoajur().CNPJnumerosiguais()) {
                if (fornecedor.getPessoajur().CNPJvalido()) {
                    LbCNPJValido.setText("Válido");
                    LbCNPJValido.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sucesso2.png")));
                    if(fornecedor.getPessoajur().CNPJexistente()){
                        if(fornecedor.efornecedor()){
                            if (!TfCodigo.getText().equals("") && (fornecedor.getCodigo() == Integer.parseInt(TfCodigo.getText()))){
                                
                            }else
                            if(fornecedor.efornecedorativo()){
                                JOptionPane.showMessageDialog(null, "Este CNPJ pertence a um fornecedor já cadastrado no sistema!\n"
                                        + "Consulte os dados deste fornecedor na aba \"Consulta\" e informe o código ao fornecedor, caso ele tenha esquecido!", "CNPJ existente", JOptionPane.INFORMATION_MESSAGE);
                                TfNrCNPJ.setText("");
                                TfNrCNPJKeyReleased(null);
                            } else {
                                int op = JOptionPane.showConfirmDialog(null, "Este CNPJ pertence a " + fornecedor.getPessoajur().retornanomeporCNPJ() + ". "
                                        + "Os dados desta empresa foram excluídas do sistema!\n\n"
                                        + "Deseja recuperar os dados desta empresa?", "O que deseja fazer?", JOptionPane.YES_NO_OPTION);
                                if (op == JOptionPane.YES_OPTION){
                                    fornecedor.getPessoajur().getPessoa().setCodigo(fornecedor.retornacodigopessoafornecedor());
                                    fornecedor.getPessoajur().getPessoa().recuperar();
                                    JOptionPane.showMessageDialog(null, "Recuperação realizada com sucesso!\nAs informações do fornecedor permanecem iguais as que estavam cadastradas no momento da exclusão\n\n"
                                            + "Código: " + fornecedor.getCodigo() + "\nNome: " + fornecedor.getPessoajur().retornanomeporCNPJ(), "Recuperação realizada com sucesso", JOptionPane.INFORMATION_MESSAGE);
                                    limpar.Limpar(PnCadastro);
                                    limpar.Limpar(TbTelefone);
                                    limpar.Limpar(TbEmail);
                                    limpar.Limpar(TbPesquisa);
                                    TfNrCNPJKeyReleased(null);
                                    valida.validacamposCancelar(PnCadastro, PnBotoes);
                                }else {
                                    TfNrCNPJ.setText("");
                                    TfNrCNPJKeyReleased(null);
                                }
                            }
                        } else {
                            int op = JOptionPane.showConfirmDialog(null, "Este CNPJ pertence a " + fornecedor.getPessoajur().retornanomeporCNPJ() + ". "
                                    + "Os dados desta empresa estão cadastrados no sistema!\n\n"
                                    + "Deseja importar os dados desta empresa para criar um novo fornecedor?\n"
                                    + "(Caso queira, o fornecedor será criado automaticamente com as informações contidas no sistema)", "O que deseja fazer?", JOptionPane.YES_NO_OPTION);
                            if (op == JOptionPane.YES_OPTION){
                                fornecedor.importardadosnovofornecedor();
                                JOptionPane.showMessageDialog(null, "Importação dos dados realizada com sucesso!\n"
                                        + "Um novo fornecedor está gravado no sistema com as informações contidas no CNPJ da empresa.\n"
                                        + "Caso deseja conferir ou alterar os dados do fornecedor, faça a busca na aba \"Consulta\".\n\n"
                                        + "Código: " + fornecedor.getCodigo() + "\nNome: " + fornecedor.getPessoajur().retornanomeporCNPJ());
                                limpar.Limpar(PnCadastro);
                                limpar.Limpar(TbTelefone);
                                limpar.Limpar(TbEmail);
                                limpar.Limpar(TbPesquisa);
                                TfNrCNPJKeyReleased(null);
                                valida.validacamposCancelar(PnCadastro, PnBotoes);
                            } else {
                                TfNrCNPJ.setText("");
                                TfNrCNPJKeyReleased(null);
                            }
                        }
                    }
                } else {
                    LbCNPJValido.setText("CNPJ Inválido");
                    LbCNPJValido.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/erro.png")));
                }
            } else {
                LbCNPJValido.setText("Números Iguais");
                LbCNPJValido.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/erro.png")));
            }
        } else {
            LbCNPJValido.setText("Espaços em Branco");
            LbCNPJValido.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/erro.png")));
        }
    }//GEN-LAST:event_TfNrCNPJFocusLost

    private void BtCadCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadCidadeActionPerformed
        final InterfaceCidade tela = new InterfaceCidade(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                CbEstadoActionPerformed(null);
            }
        });
    }//GEN-LAST:event_BtCadCidadeActionPerformed

    private void CbEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbEstadoActionPerformed
        if (CbEstado.getSelectedItem() == null) {
            preenche.PreencheJComboBox(CbEstado, fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().buscarestadosjcombobox());
        }
        fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().setEstado(CbEstado.getSelectedItem().toString());
        preenche.PreencheJComboBox(CbCidade, fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().buscarcidadesporestado());
    }//GEN-LAST:event_CbEstadoActionPerformed

    private void CbEstadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbEstadoMouseClicked

    }//GEN-LAST:event_CbEstadoMouseClicked

    private void TfDtFundFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfDtFundFocusLost
        if (valida.CampoTotalmentePreenchido(TfDtFund.getText())) {
            if (datas.validadatas(TfDtFund.getText())) {

            } else {
                TfDtFund.setValue(null);
            }
        } else {
            if (datas.validadatas(TfDtFund.getText())) {

            } else {
                TfDtFund.setValue(null);
            }
        }
    }//GEN-LAST:event_TfDtFundFocusLost

    private void TfCEPFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCEPFocusLost
        valida.FocusLostDeCamposFormatados(TfCEP);
    }//GEN-LAST:event_TfCEPFocusLost

    private void TfDsEmailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfDsEmailFocusLost

    }//GEN-LAST:event_TfDsEmailFocusLost

    private void BtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirActionPerformed
        valida.validacamposCadastrar(PnCadastro, PnBotoes);
        limpar.Limpar(PnCadastro);
        limpar.Limpar(TbTelefone);
        limpar.Limpar(TbEmail);
        preenche.PreencheJComboBox(CbEstado, fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().buscarestadosjcombobox());
        TfNrCNPJKeyReleased(null);
        TfDtCadastro.setText(datas.retornadataatual());
        msg.StatusNovo(LbNotificacao, "Insira os dados do novo Fornecedor");
    }//GEN-LAST:event_BtIncluirActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        if (TfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Busque por um Fornecedor na Aba \"Consulta\" e selecione a opção \"Carregar Dados\" após selecionar e\nclicar com o botão direito sobre os dados do fornecedor para que a opção de Alterar os Dados seja realizada!");
            TabbedPaneFornecedor.setSelectedIndex(1);
            CbPesquisa.grabFocus();
        } else {
            valida.validacamposCadastrar(PnCadastro, PnBotoes);
            msg.StatusEditar(LbNotificacao, "Editando dados do Fornecedor...");
        }
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        if (TfCodigo.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Busque por um Fornecedor na Aba \"Consulta\" e selecione a opção \"Carregar Dados\" após selecionar e\nclicar com o botão direito sobre os dados do fornecedor para que a opção de Excluir os Dados seja realizada!");
            TabbedPaneFornecedor.setSelectedIndex(1);
            CbPesquisa.grabFocus();
        } else {
            if (JOptionPane.showConfirmDialog(null, "Você tem certeza que deseja EXCLUIR os dados deste Fornecedor?", "Deseja excluir?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                fornecedor.setCodigo(Integer.parseInt(TfCodigo.getText()));
                if(fornecedor.excluir()) msg.StatusExcluido(LbNotificacao, "Fornecedor excluído com sucesso!");
                limpar.Limpar(PnCadastro);
                limpar.Limpar(TbTelefone);
                limpar.Limpar(TbEmail);
                valida.validacamposCancelar(PnCadastro, PnBotoes);
                TfNrCNPJKeyReleased(null);
                BtPesquisaActionPerformed(evt);
            }
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente Cancelar esta operação?\n(TODOS os dados na tela serão limpos)", "Confirmar ação", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpar.Limpar(PnCadastro);
            limpar.Limpar(TbTelefone);
            limpar.Limpar(TbEmail);
            TfNrCNPJKeyReleased(null);
            valida.validacamposCancelar(PnCadastro, PnBotoes);
            msg.Limpar(LbNotificacao);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void TfNomeFantasiaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfNomeFantasiaKeyTyped
        valida.limitemaximo(evt, TfNomeFantasia.getText(), 80);
    }//GEN-LAST:event_TfNomeFantasiaKeyTyped

    private void TfRazaoSocialKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfRazaoSocialKeyTyped
        valida.limitemaximo(evt, TfRazaoSocial.getText(), 80);
    }//GEN-LAST:event_TfRazaoSocialKeyTyped

    private void TfDsEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDsEmailKeyTyped
        valida.limitemaximo(evt, TfDsEmail.getText(), 60);
    }//GEN-LAST:event_TfDsEmailKeyTyped

    private void TfLogradouroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfLogradouroKeyTyped
        valida.limitemaximo(evt, TfLogradouro.getText(), 50);
    }//GEN-LAST:event_TfLogradouroKeyTyped

    private void TfNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfNumeroKeyTyped
        valida.limitemaximo(evt, TfNumero.getText(), 10);
    }//GEN-LAST:event_TfNumeroKeyTyped

    private void TfBairroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfBairroKeyTyped
        valida.limitemaximo(evt, TfBairro.getText(), 30);
    }//GEN-LAST:event_TfBairroKeyTyped

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (camposobrigatoriospreenchidos()) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja realmente Gravar os dados deste fornecedor?", "Confirmar", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                if (TfCodigo.getText().equals("")) {
                    enviardados();
                    if(fornecedor.incluir()) msg.Sucesso(LbNotificacao, "Dados do Fornecedor gravados com sucesso!");
                    fornecedor.getPessoajur().getPessoa().getTelefone().setCodigopessoa(fornecedor.getPessoajur().getPessoa().getCodigo());
                    fornecedor.getPessoajur().getPessoa().getEmail().setCodigopessoa(fornecedor.getPessoajur().getPessoa().getCodigo());
                    JOptionPane.showMessageDialog(null, "Código: " + fornecedor.getCodigo() + "\n"
                            + "Fornecedor: " + fornecedor.getPessoajur().getNomefantasia().toUpperCase(), "Informe o Código", JOptionPane.INFORMATION_MESSAGE);
                    for (int i = 0; i < TbTelefone.getRowCount(); i++) {
                        fornecedor.getPessoajur().getPessoa().getTelefone().setCodigo(i + 1);
                        fornecedor.getPessoajur().getPessoa().getTelefone().setNrtelefone(TbTelefone.getValueAt(i, 1).toString());
                        fornecedor.getPessoajur().getPessoa().getTelefone().setTipotelefone(TbTelefone.getValueAt(i, 2).toString());
                        fornecedor.getPessoajur().getPessoa().getTelefone().incluir();
                    }
                    for (int i = 0; i < TbEmail.getRowCount(); i++) {
                        fornecedor.getPessoajur().getPessoa().getEmail().setCodigo(i + 1);
                        fornecedor.getPessoajur().getPessoa().getEmail().setEmail(TbEmail.getValueAt(i, 1).toString());
                        fornecedor.getPessoajur().getPessoa().getEmail().setTipoemail(TbEmail.getValueAt(i, 2).toString());
                        fornecedor.getPessoajur().getPessoa().getEmail().incluir();
                    }
                    limpar.Limpar(PnCadastro);
                    limpar.Limpar(TbTelefone);
                    limpar.Limpar(TbEmail);
                    TfNrCNPJKeyReleased(null);
                    valida.validacamposCancelar(PnCadastro, PnBotoes);
                } else {
                    fornecedor.setCodigo(Integer.parseInt(TfCodigo.getText()));
                    fornecedor.getPessoajur().getPessoa().setCodigo(fornecedor.retornacodigopessoafornecedor());
                    enviardados();
                    if(fornecedor.alterar()) msg.Sucesso(LbNotificacao, "Dados do Fornecedor alterados com sucesso!");
                    fornecedor.getPessoajur().getPessoa().getTelefone().setCodigopessoa(fornecedor.getPessoajur().getPessoa().getCodigo());
                    fornecedor.getPessoajur().getPessoa().getEmail().setCodigopessoa(fornecedor.getPessoajur().getPessoa().getCodigo());
                    fornecedor.getPessoajur().getPessoa().getTelefone().deletartelefones();
                    fornecedor.getPessoajur().getPessoa().getEmail().deletaremails();
                    for (int i = 0; i < TbTelefone.getRowCount(); i++) {
                        fornecedor.getPessoajur().getPessoa().getTelefone().setCodigo(i + 1);
                        fornecedor.getPessoajur().getPessoa().getTelefone().setNrtelefone(TbTelefone.getValueAt(i, 1).toString());
                        fornecedor.getPessoajur().getPessoa().getTelefone().setTipotelefone(TbTelefone.getValueAt(i, 2).toString());
                        fornecedor.getPessoajur().getPessoa().getTelefone().incluir();
                    }
                    for (int i = 0; i < TbEmail.getRowCount(); i++) {
                        fornecedor.getPessoajur().getPessoa().getEmail().setCodigo(i + 1);
                        fornecedor.getPessoajur().getPessoa().getEmail().setEmail(TbEmail.getValueAt(i, 1).toString());
                        fornecedor.getPessoajur().getPessoa().getEmail().setTipoemail(TbEmail.getValueAt(i, 2).toString());
                        fornecedor.getPessoajur().getPessoa().getEmail().incluir();
                    }
                    limpar.Limpar(PnCadastro);
                    limpar.Limpar(TbTelefone);
                    limpar.Limpar(TbEmail);
                    TfNrCNPJKeyReleased(null);
                    valida.validacamposCancelar(PnCadastro, PnBotoes);
                }
            }
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void TfNrCNPJKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfNrCNPJKeyTyped
        TfNrCNPJKeyReleased(evt);
    }//GEN-LAST:event_TfNrCNPJKeyTyped

    private void BtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisaActionPerformed
        int[] parametro = new int[4];
        parametro[0] = 70;
        parametro[1] = 300;
        parametro[2] = 100;
        parametro[3] = 70;
        preenche.FormataJtable(TbPesquisa, parametro);

        switch (CbPesquisa.getSelectedIndex()) {
            case 0: {
                preenche.PreencherJtable(TbPesquisa, fornecedor.consultageral());
                break;
            }
            case 1: {
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o Código do fornecedor que deseja consultar!", "Digite o código", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    fornecedor.setCodigo(Integer.parseInt(TfPesquisa.getText()));
                    preenche.PreencherJtable(TbPesquisa, fornecedor.consultacodigo());
                }
                break;
            }
            case 2:{
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o Nome fantasia do fornecedor que deseja consultar!", "Digite o nome fantasia", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    fornecedor.getPessoajur().setNomefantasia(TfPesquisa.getText());
                    preenche.PreencherJtable(TbPesquisa, fornecedor.consultanomefantasia());
                }
                break;
            }
            case 3:{
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o CNPJ do fornecedor que deseja consultar!", "Digite o CNPJ", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    fornecedor.getPessoajur().setCnpj(TfPesquisa.getText());
                    preenche.PreencherJtable(TbPesquisa, fornecedor.consultaCNPJ());
                }
                break;
            }
        }
    }//GEN-LAST:event_BtPesquisaActionPerformed

    private void CbPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPesquisaActionPerformed
        switch (CbPesquisa.getSelectedIndex()) {
            case 0: {
                TfPesquisa.setEnabled(false);
                TfPesquisa.setDocument(TfNomeFantasia.getDocument());
                break;
            }
            case 1: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(new PermiteApenasNumeros());
                break;
            }
            case 2: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(TfNomeFantasia.getDocument());
                break;
            }
            case 3: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(new PermiteNumerosPontoBarra());
                break;
            }
        }
    }//GEN-LAST:event_CbPesquisaActionPerformed

    private void MnItRetornaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItRetornaActionPerformed
        if (TbPesquisa.getSelectedRow() != -1) {
            fornecedor.setCodigo(Integer.parseInt(TbPesquisa.getValueAt(TbPesquisa.getSelectedRow(), 0).toString()));
            fornecedor.getPessoajur().getPessoa().setCodigo(fornecedor.retornacodigopessoafornecedor());
            fornecedor.getPessoajur().getPessoa().getTelefone().setCodigopessoa(fornecedor.getPessoajur().getPessoa().getCodigo());
            fornecedor.getPessoajur().getPessoa().getEmail().setCodigopessoa(fornecedor.getPessoajur().getPessoa().getCodigo());
            preenche.PreencheJtableSEL(TbTelefone, fornecedor.getPessoajur().getPessoa().getTelefone().retornatelefonespessoa());
            preenche.PreencheJtableSEL(TbEmail, fornecedor.getPessoajur().getPessoa().getEmail().retornaemailspessoa());
            fornecedor.getPessoajur().retornapessoajuridica();
            valida.validacamposCancelar(PnCadastro, PnBotoes);
            limpar.Limpar(PnCadastro);
            TfCodigo.setText("" + fornecedor.getCodigo() + "");
            TfDtCadastro.setText(fornecedor.getPessoajur().getPessoa().getDatacadastro());
            TfNomeFantasia.setText(fornecedor.getPessoajur().getNomefantasia());
            TfRazaoSocial.setText(fornecedor.getPessoajur().getRazaosocial());
            TfNrCNPJ.setText(fornecedor.getPessoajur().getCnpj());
            TfNrCNPJKeyReleased(null);
            TfDtFund.setText(fornecedor.getPessoajur().getDatafund());
            TfLogradouro.setText(fornecedor.getPessoajur().getPessoa().getEndereco().getLogradouro());
            TfCEP.setText(fornecedor.getPessoajur().getPessoa().getEndereco().getCep());
            TfBairro.setText(fornecedor.getPessoajur().getPessoa().getEndereco().getBairro());
            TfNumero.setText(fornecedor.getPessoajur().getPessoa().getEndereco().getNumero());
            CbEstado.setSelectedItem(fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().getEstado());
            CbEstadoActionPerformed(evt);
            CbCidade.setSelectedItem(fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getCidade());
            TabbedPaneFornecedor.setSelectedIndex(0);
            valida.validacamposCancelar(PnCadastro, PnBotoes);
            msg.StatusBusca(LbNotificacao, "Dados do Fornecedor carregados na tela");
        }
    }//GEN-LAST:event_MnItRetornaActionPerformed

    private void TfNrCNPJKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfNrCNPJKeyReleased
        valida.FocusLostDeCamposFormatados(TfNrCNPJ);
        fornecedor.getPessoajur().setCnpj(TfNrCNPJ.getText());
        if (valida.CampoTotalmentePreenchido(fornecedor.getPessoajur().getCnpj())) {
            if (!fornecedor.getPessoajur().CNPJnumerosiguais()) {
                if (fornecedor.getPessoajur().CNPJvalido()) {
                    LbCNPJValido.setText("Válido");
                    LbCNPJValido.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sucesso2.png")));
                } else {
                    LbCNPJValido.setText("CNPJ Inválido");
                    LbCNPJValido.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/erro.png")));
                }
            } else {
                LbCNPJValido.setText("Números Iguais");
                LbCNPJValido.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/erro.png")));
            }
        } else {
            LbCNPJValido.setText("Espaços em Branco");
            LbCNPJValido.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/erro.png")));
        }
    }//GEN-LAST:event_TfNrCNPJKeyReleased

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(PnBotoes.isVisible() && BtGravar.isEnabled()){
            if(JOptionPane.showConfirmDialog(null, "Você esta prestes a fechar esta janela.\nAo fechar esta janela tudo que você digitou será esquecido!", "Tem certeza que deseja fechar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                dispose();
            }
        }else{
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtCadCidade;
    private javax.swing.JButton BtCadEstado;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtIncluir;
    private javax.swing.JButton BtPesquisa;
    private javax.swing.JComboBox CbCidade;
    private javax.swing.JComboBox CbEstado;
    private javax.swing.JComboBox CbPesquisa;
    private javax.swing.JLabel LbCNPJValido;
    private javax.swing.JLabel LbNotificacao;
    private javax.swing.JMenuItem MnItRetorna;
    private javax.swing.JPanel PnBotoes;
    private javax.swing.JPanel PnCadastro;
    private javax.swing.JPanel PnConsulta;
    private javax.swing.JPopupMenu PopupMenuRetorna;
    private javax.swing.JTabbedPane TabbedPaneFornecedor;
    private javax.swing.JTable TbEmail;
    private javax.swing.JTable TbPesquisa;
    private javax.swing.JTable TbTelefone;
    private javax.swing.JTextField TfBairro;
    private javax.swing.JFormattedTextField TfCEP;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfDsEmail;
    private javax.swing.JFormattedTextField TfDtCadastro;
    private javax.swing.JFormattedTextField TfDtFund;
    private javax.swing.JTextField TfLogradouro;
    private javax.swing.JTextField TfNomeFantasia;
    private javax.swing.JFormattedTextField TfNrCNPJ;
    private javax.swing.JFormattedTextField TfNrTelefone;
    private javax.swing.JTextField TfNumero;
    private javax.swing.JTextField TfPesquisa;
    private javax.swing.JTextField TfRazaoSocial;
    private javax.swing.JButton jBtAddEmail;
    private javax.swing.JButton jBtAddTelefone;
    private javax.swing.JButton jBtDelEmail;
    private javax.swing.JButton jBtDelTelefone;
    private javax.swing.JComboBox jCbOpEmail;
    private javax.swing.JComboBox jCbOpTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario(){
        getTelasusuario().getTela().setCodigo(2);
        if(!getTelasusuario().eadmintela()){
            PnBotoes.setVisible(false);
        }
        
        getTelasusuario().getTela().setCodigo(4);
        if(!getTelasusuario().eadmintela()){
            BtCadEstado.setVisible(false);
        }
        
        getTelasusuario().getTela().setCodigo(5);
        if(!getTelasusuario().eadmintela()){
            BtCadCidade.setVisible(false);
        }
    }
    
    public boolean camposobrigatoriospreenchidos() {

        if (!TfNomeFantasia.getText().equals("")) {
        } else {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Nome Fantasia do fornecedor e obrigatório");
            TfNomeFantasia.grabFocus();
            return false;
        }

        if (LbCNPJValido.getText().equals("Válido")) {
        } else {
            JOptionPane.showMessageDialog(null, "Digite um CNPJ válido!");
            TfNrCNPJ.grabFocus();
            return false;
        }
        if (TfLogradouro.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite a Rua/Avenida de localização do fornecedor!");
            TfLogradouro.grabFocus();
            return false;
        }
        if (TfNumero.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite o Número da localização do fornecedor!");
            TfNumero.grabFocus();
            return false;
        }
        if (!valida.CampoTotalmentePreenchido(TfCEP.getText())) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite o CEP da localização do fornecedor!");
            TfCEP.grabFocus();
            return false;
        }
        if (TfBairro.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite o Bairro de localização do fornecedor!");
            TfBairro.grabFocus();
            return false;
        }
        if (CbEstado.getSelectedItem() == null) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira ou cadastre um Estado!");
            BtCadEstado.grabFocus();
            return false;
        }
        if (CbCidade.getSelectedItem() == null) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira ou cadastre uma Cidade!");
            BtCadCidade.grabFocus();
            return false;
        }
        return true;
    }

    public void enviardados() {
        fornecedor.getPessoajur().getPessoa().setDatacadastro(TfDtCadastro.getText());
        fornecedor.getPessoajur().getPessoa().setTipopessoa("J");
        fornecedor.getPessoajur().setNomefantasia(TfNomeFantasia.getText());
        fornecedor.getPessoajur().setCnpj(TfNrCNPJ.getText());
        fornecedor.getPessoajur().setRazaosocial(TfRazaoSocial.getText());
        fornecedor.getPessoajur().setDatafund(TfDtFund.getText());
        if(fornecedor.getPessoajur().getDatafund().equals("  /  /    "))
            fornecedor.getPessoajur().setDatafund("01/01/0001");
        fornecedor.getPessoajur().getPessoa().getEndereco().setLogradouro(TfLogradouro.getText());
        fornecedor.getPessoajur().getPessoa().getEndereco().setNumero(TfNumero.getText());
        fornecedor.getPessoajur().getPessoa().getEndereco().setBairro(TfBairro.getText());
        fornecedor.getPessoajur().getPessoa().getEndereco().setCep(TfCEP.getText());
        fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().setEstado(CbEstado.getSelectedItem().toString());
        fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().setCodigo(fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().getEstado().retornacodigo());
        fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().setCidade(CbCidade.getSelectedItem().toString());
        fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().setCodigo(fornecedor.getPessoajur().getPessoa().getEndereco().getCidade().retornacodigo());
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
