package br.com.lojadafatima.InterfacesPessoa;

import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.DadosPessoa.ClasseCidade;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceCidade extends javax.swing.JDialog {

    private java.awt.Frame primeiratela;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    Preenche preenche = new Preenche();
    ClasseCidade cidade = new ClasseCidade();
    LimpaCamposTela limpar = new LimpaCamposTela();
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    MensagensUsuario msg = new MensagensUsuario();
    
    public InterfaceCidade(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super (telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        
        setTelasusuario(usuario);
        analisausuario();
        int[] tam = new int[3];
        tam[0] = 50;
        tam[1] = 150;
        tam[2] = 100;
        preenche.FormataJtable(TbCidades, tam);
        preenche.PreencherJtable(TbCidades, cidade.buscarcidadesjtable());
        preenche.PreencheJComboBox(CbEstado, cidade.getEstado().buscarestadosjcombobox());
        TbCidades.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TfCidade.setDocument(new NaoPermiteAspasSimples());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnItAlterar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TfCidade = new javax.swing.JTextField();
        BtGravar = new javax.swing.JButton();
        BtLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbCidades = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        CbEstado = new javax.swing.JComboBox();
        BtCadEstado = new javax.swing.JButton();
        jPanel24 = new javax.swing.JPanel();
        LbNotificacoes = new javax.swing.JLabel();

        MnItAlterar.setText("Alterar Cidade");
        MnItAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItAlterarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnItAlterar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cidades - Software Loja da Fátima");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodigo.setEditable(false);
        jPanel1.add(TfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 100, -1));

        jLabel2.setText("Cidade*");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 11, -1, -1));

        TfCidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfCidadeKeyTyped(evt);
            }
        });
        jPanel1.add(TfCidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(128, 31, 200, -1));

        BtGravar.setText("Gravar");
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });
        jPanel1.add(BtGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 116, 89, -1));

        BtLimpar.setText("Limpar");
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });
        jPanel1.add(BtLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(109, 116, 85, -1));

        TbCidades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Cidade", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbCidades.setComponentPopupMenu(jPopupMenu1);
        TbCidades.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbCidades);
        if (TbCidades.getColumnModel().getColumnCount() > 0) {
            TbCidades.getColumnModel().getColumn(0).setResizable(false);
            TbCidades.getColumnModel().getColumn(1).setResizable(false);
            TbCidades.getColumnModel().getColumn(2).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 145, 318, 161));

        jLabel3.setText("Estado*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        jPanel1.add(CbEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 83, 133, -1));

        BtCadEstado.setText("Adicionar Estado");
        BtCadEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadEstadoActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadEstado, new org.netbeans.lib.awtextra.AbsoluteConstraints(149, 82, -1, -1));

        LbNotificacoes.setText(" ");

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(LbNotificacoes)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacoes)
        );

        jPanel1.add(jPanel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 312, 318, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if(!TfCidade.getText().equals("")){
            int opcao;
            cidade.setCidade(TfCidade.getText());
            cidade.getEstado().setEstado(CbEstado.getSelectedItem().toString());
            if(TfCodigo.getText().equals("")){
                opcao = JOptionPane.showConfirmDialog(rootPane, "Incluir nova Cidade?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if(opcao == JOptionPane.YES_OPTION)
                if (cidade.incluir()){
                    msg.Sucesso(LbNotificacoes, "Dados da Cidade gravados com sucesso!");
                }
                limpar.Limpar(jPanel1);
                limpar.Limpar(TbCidades);
            } else {
                cidade.setCodigo(Integer.parseInt(TfCodigo.getText()));
                opcao = JOptionPane.showConfirmDialog(rootPane, "Alterar dados da Cidade?", "Confirmar", JOptionPane.YES_NO_OPTION);
                if(opcao == JOptionPane.YES_OPTION)
                if (cidade.alterar()){
                    msg.Sucesso(LbNotificacoes, "Dados da Cidade alterados com sucesso!");
                }
                limpar.Limpar(jPanel1);
                limpar.Limpar(TbCidades);
            }
            preenche.PreencherJtable(TbCidades, cidade.buscarcidadesjtable());
        }else{
            msg.CampoObrigatorioNaoPreenchido(LbNotificacoes, "Digite o Nome da Cidade!");
            TfCidade.grabFocus();
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        limpar.Limpar(jPanel1);
    }//GEN-LAST:event_BtLimparActionPerformed

    private void MnItAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItAlterarActionPerformed
        int index = TbCidades.getSelectedRow();
        if (index > -1) {
            BtLimparActionPerformed(evt);
            TfCodigo.setText(TbCidades.getValueAt(index, 0).toString());
            TfCidade.setText(TbCidades.getValueAt(index, 1).toString());
            CbEstado.setSelectedItem(TbCidades.getValueAt(index, 2).toString());
            msg.StatusEditar(LbNotificacoes, "Editando informações...");
        }
    }//GEN-LAST:event_MnItAlterarActionPerformed

    private void BtCadEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadEstadoActionPerformed
        final InterfaceEstado tela = new InterfaceEstado(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                preenche.PreencheJComboBox(CbEstado, cidade.getEstado().buscarestadosjcombobox());
            }
        });
    }//GEN-LAST:event_BtCadEstadoActionPerformed

    private void TfCidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCidadeKeyTyped
        valida.limitemaximo(evt, TfCidade.getText(), 50);
    }//GEN-LAST:event_TfCidadeKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadEstado;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JComboBox CbEstado;
    private javax.swing.JLabel LbNotificacoes;
    private javax.swing.JMenuItem MnItAlterar;
    private javax.swing.JTable TbCidades;
    private javax.swing.JTextField TfCidade;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    
    public void analisausuario(){
        getTelasusuario().getTela().setCodigo(5);
        if(!getTelasusuario().eadmintela()){
            BtGravar.setVisible(false);
        }
        getTelasusuario().getTela().setCodigo(4);
        if(!getTelasusuario().eadmintela()){
            BtCadEstado.setVisible(false);
        }
    }
    
    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
