/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lojadafatima.InterfacesPessoa;

import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.DadosPessoa.ClasseEstado;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author hp
 */
public class InterfaceEstado extends javax.swing.JDialog {

    MaskFormatter sigla;
    Preenche preenche = new Preenche();
    ClasseEstado estado = new ClasseEstado();
    LimpaCamposTela limpar = new LimpaCamposTela();
    private java.awt.Frame primeiratela;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();

    public InterfaceEstado(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();

        setTelasusuario(usuario);
        analisausuario();
        int[] tam = new int[3];
        tam[0] = 50;
        tam[1] = 200;
        tam[2] = 50;
        preenche.FormataJtable(TbEstados, tam);
        preenche.PreencherJtable(TbEstados, estado.buscarestadosjtable());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        MnItAlterar = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TfEstado = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        BtGravar = new javax.swing.JButton();
        BtLimpar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbEstados = new javax.swing.JTable();
        try{
            sigla = new MaskFormatter("UU");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel localizar");
        }
        TfSigla = new JFormattedTextField(sigla);

        MnItAlterar.setText("Alterar Estado");
        MnItAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItAlterarActionPerformed(evt);
            }
        });
        jPopupMenu1.add(MnItAlterar);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estados - Software Loja da Fátima");
        setResizable(false);

        jLabel1.setText("Código");

        TfCodigo.setEditable(false);

        jLabel2.setText("Estado*");

        TfEstado.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfEstadoKeyTyped(evt);
            }
        });

        jLabel3.setText("Sigla*");

        BtGravar.setText("Gravar");
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtLimpar.setText("Limpar");
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });

        TbEstados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Estado", "Sigla"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbEstados.setComponentPopupMenu(jPopupMenu1);
        TbEstados.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbEstados);
        if (TbEstados.getColumnModel().getColumnCount() > 0) {
            TbEstados.getColumnModel().getColumn(0).setResizable(false);
            TbEstados.getColumnModel().getColumn(1).setResizable(false);
            TbEstados.getColumnModel().getColumn(2).setResizable(false);
        }

        TfSigla.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfSiglaFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(TfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfSigla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtGravar)
                    .addComponent(BtLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TfSiglaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfSiglaFocusLost
        TfSigla.setFocusLostBehavior(JFormattedTextField.PERSIST);
    }//GEN-LAST:event_TfSiglaFocusLost

    private void MnItAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItAlterarActionPerformed
        int index = TbEstados.getSelectedRow();
        if (index > -1) {
            BtLimparActionPerformed(evt);
            TfCodigo.setText(TbEstados.getValueAt(index, 0).toString());
            TfEstado.setText(TbEstados.getValueAt(index, 1).toString());
            TfSigla.setText(TbEstados.getValueAt(index, 2).toString());
        }
    }//GEN-LAST:event_MnItAlterarActionPerformed

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        limpar.Limpar(jPanel1);
    }//GEN-LAST:event_BtLimparActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (!TfEstado.getText().equals("")) {
            if (!TfSigla.getText().equals("  ")) {
                int opcao;
                estado.setEstado(TfEstado.getText());
                estado.setSigla(TfSigla.getText());
                if (TfCodigo.getText().equals("")) {
                    opcao = JOptionPane.showConfirmDialog(rootPane, "Incluir novo Estado?", "Confirmar", JOptionPane.YES_NO_OPTION);
                    if (opcao == JOptionPane.YES_OPTION) {
                        estado.incluir();
                        limpar.Limpar(TbEstados);
                        limpar.Limpar(jPanel1);
                    }
                } else {
                    estado.setCodigo(Integer.parseInt(TfCodigo.getText()));
                    opcao = JOptionPane.showConfirmDialog(rootPane, "Alterar dados do Estado?", "Confirmar", JOptionPane.YES_NO_OPTION);
                    if (opcao == JOptionPane.YES_OPTION) {
                        estado.alterar();
                        limpar.Limpar(TbEstados);
                        limpar.Limpar(jPanel1);
                    }
                }
                preenche.PreencherJtable(TbEstados, estado.buscarestadosjtable());
            } else {
                JOptionPane.showMessageDialog(rootPane, "Digite a Sigla", "Campos Obrigatorios", JOptionPane.INFORMATION_MESSAGE);
                TfSigla.grabFocus();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Digite o Nome do Estado", "Campos Obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            TfEstado.grabFocus();
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void TfEstadoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfEstadoKeyTyped
        valida.limitemaximo(evt, TfEstado.getText(), 40);
    }//GEN-LAST:event_TfEstadoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JMenuItem MnItAlterar;
    private javax.swing.JTable TbEstados;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfEstado;
    private javax.swing.JFormattedTextField TfSigla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

   
    public void analisausuario(){
        getTelasusuario().getTela().setCodigo(4);
        if(!getTelasusuario().eadmintela()){
            BtGravar.setVisible(false);
        }
    }
    
    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
