/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lojadafatima.InterfacesUsuario;

import br.com.lojadafatima.InterfacesFinanceiro.InterfaceMultas;
import br.com.lojadafatima.InterfacesOperacoes.InterfaceOperacoes;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceCondicaoPagto;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceContasPagar;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceMovimentacaoCaixa;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceFormaPagto;
import br.com.lojadafatima.InterfacesFinanceiro.InterfacePagamentoFuncionarios;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceContasReceber;
import br.com.lojadafatima.InterfacesOperacoes.InterfaceCompra;
import br.com.lojadafatima.InterfacesOperacoes.InterfaceRealizarOperacoes;
import br.com.lojadafatima.InterfacesOperacoes.InterfaceVenda;
import br.com.lojadafatima.Financeiro.ClasseParcelas;
import br.com.lojadafatima.InterfaceConsultaSimples.InterfaceRelatorios;
import br.com.lojadafatima.InterfacesProduto.InterfaceProduto;
import br.com.lojadafatima.InterfacesProduto.InterfaceTabelas;
import br.com.lojadafatima.InterfacesProduto.InterfaceTipoProduto;
import br.com.lojadafatima.InterfacesPessoa.InterfaceCliente;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFuncionario;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFornecedor;
import br.com.lojadafatima.InterfacesPessoa.InterfaceCidade;
import br.com.lojadafatima.InterfacesPessoa.InterfaceEstado;
import br.com.lojadafatima.InterfacesProduto.InterfaceEstoque;
import br.com.lojadafatima.Produto.ClasseMvtoEstoque;
import br.com.lojadafatima.Usuario.ClasseTelas;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import br.com.lojadafatima.Usuario.ClasseUsuario;
import java.awt.Menu;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author hp
 */
public class InterfacePrincipal extends javax.swing.JDialog {

    private java.awt.Frame primeiratela;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();

    public InterfacePrincipal(java.awt.Frame telaorigem, boolean modal, ClasseUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        getTelasusuario().setUsuario(usuario);
        LbNmUsuario.setText(getTelasusuario().getUsuario().getLogin());
//        liberatelas();
        atualizasituacao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtVenda = new javax.swing.JButton();
        LbSair = new javax.swing.JLabel();
        BtCompra = new javax.swing.JButton();
        BtContasReceber = new javax.swing.JButton();
        BtContasPagar = new javax.swing.JButton();
        BtMvtoCaixa = new javax.swing.JButton();
        BtEstoque = new javax.swing.JButton();
        LbNmUsuario = new javax.swing.JLabel();
        BtRealizarOperacao = new javax.swing.JButton();
        BtPagamentoFuncionarios = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LbQtProdutosBaixos = new javax.swing.JLabel();
        LbContasReceberVencidas = new javax.swing.JLabel();
        LbContasReceberAbertas = new javax.swing.JLabel();
        LbContasPagarVencida = new javax.swing.JLabel();
        LbContasPagarAbertas = new javax.swing.JLabel();
        BtRelatorios = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        MnCadastros = new javax.swing.JMenu();
        MnItCadCliente = new javax.swing.JMenuItem();
        MnItCadFornecedor = new javax.swing.JMenuItem();
        MnItFuncionario = new javax.swing.JMenuItem();
        MnItCadCondicaoPagto = new javax.swing.JMenuItem();
        MnItCadFormaPgto = new javax.swing.JMenuItem();
        MnItCadUsuario = new javax.swing.JMenuItem();
        MnItCadEstado = new javax.swing.JMenuItem();
        MnItCadCidade = new javax.swing.JMenuItem();
        MnItCadMultas = new javax.swing.JMenuItem();
        MnItCadOperacoes = new javax.swing.JMenuItem();
        MnFinanceiro = new javax.swing.JMenu();
        MnItContasReceber = new javax.swing.JMenuItem();
        MnItContasPagar = new javax.swing.JMenuItem();
        MnItMovimentacaoCaixa = new javax.swing.JMenuItem();
        MnProduto = new javax.swing.JMenu();
        MnItCadProduto = new javax.swing.JMenuItem();
        MnItCadTipoProduto = new javax.swing.JMenuItem();
        MnItCadTabelas = new javax.swing.JMenuItem();
        MnItEstoque = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Menu Principal - Software Loja da Fátima");
        setResizable(false);

        BtVenda.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtVenda.setText("Venda");
        BtVenda.setName("16"); // NOI18N
        BtVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtVendaActionPerformed(evt);
            }
        });

        LbSair.setForeground(javax.swing.UIManager.getDefaults().getColor("CheckBoxMenuItem.selectionBackground"));
        LbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sair.png"))); // NOI18N
        LbSair.setText("Trocar Usuário");
        LbSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbSairMouseClicked(evt);
            }
        });

        BtCompra.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtCompra.setText("Compra");
        BtCompra.setName("17"); // NOI18N
        BtCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCompraActionPerformed(evt);
            }
        });

        BtContasReceber.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtContasReceber.setText("Contas à Receber");
        BtContasReceber.setName("9"); // NOI18N
        BtContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtContasReceberActionPerformed(evt);
            }
        });

        BtContasPagar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtContasPagar.setText("Contas à Pagar");
        BtContasPagar.setName("10"); // NOI18N
        BtContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtContasPagarActionPerformed(evt);
            }
        });

        BtMvtoCaixa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtMvtoCaixa.setText("Movimentação de Caixa");
        BtMvtoCaixa.setName("11"); // NOI18N
        BtMvtoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtMvtoCaixaActionPerformed(evt);
            }
        });

        BtEstoque.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtEstoque.setText("Estoque");
        BtEstoque.setName("15"); // NOI18N
        BtEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEstoqueActionPerformed(evt);
            }
        });

        LbNmUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/boneco.png"))); // NOI18N
        LbNmUsuario.setText("admin");

        BtRealizarOperacao.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtRealizarOperacao.setText("Realizar Operação");
        BtRealizarOperacao.setName("18"); // NOI18N
        BtRealizarOperacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRealizarOperacaoActionPerformed(evt);
            }
        });

        BtPagamentoFuncionarios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtPagamentoFuncionarios.setText("Pagamento de Funcionarios");
        BtPagamentoFuncionarios.setName("18"); // NOI18N
        BtPagamentoFuncionarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPagamentoFuncionariosActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Situacao:");

        LbQtProdutosBaixos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbQtProdutosBaixos.setText("jLabel2");
        LbQtProdutosBaixos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbQtProdutosBaixos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbQtProdutosBaixosMouseClicked(evt);
            }
        });

        LbContasReceberVencidas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbContasReceberVencidas.setText("jLabel3");
        LbContasReceberVencidas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbContasReceberVencidas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbContasReceberVencidasMouseClicked(evt);
            }
        });

        LbContasReceberAbertas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbContasReceberAbertas.setText("jLabel4");
        LbContasReceberAbertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbContasReceberAbertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbContasReceberAbertasMouseClicked(evt);
            }
        });

        LbContasPagarVencida.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbContasPagarVencida.setText("jLabel5");
        LbContasPagarVencida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbContasPagarVencida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbContasPagarVencidaMouseClicked(evt);
            }
        });

        LbContasPagarAbertas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        LbContasPagarAbertas.setText("jLabel6");
        LbContasPagarAbertas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        LbContasPagarAbertas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LbContasPagarAbertasMouseClicked(evt);
            }
        });

        BtRelatorios.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BtRelatorios.setText("Relatórios");
        BtRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(LbNmUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(LbSair))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(BtContasReceber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(BtVenda, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                            .addComponent(BtRealizarOperacao, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtContasPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(BtMvtoCaixa, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtPagamentoFuncionarios, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(BtRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(LbQtProdutosBaixos)
                            .addComponent(LbContasPagarVencida)
                            .addComponent(LbContasPagarAbertas)
                            .addComponent(LbContasReceberVencidas)
                            .addComponent(LbContasReceberAbertas))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LbSair)
                    .addComponent(LbNmUsuario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(BtContasReceber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtContasPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtMvtoCaixa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtRealizarOperacao, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE)
                    .addComponent(BtPagamentoFuncionarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(BtRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbQtProdutosBaixos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbContasReceberVencidas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbContasReceberAbertas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbContasPagarVencida)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LbContasPagarAbertas)
                .addContainerGap())
        );

        MnCadastros.setText("Telas/Cadastros");

        MnItCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnItCadCliente.setText("Cliente");
        MnItCadCliente.setName("6"); // NOI18N
        MnItCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadClienteActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadCliente);

        MnItCadFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnItCadFornecedor.setText("Fornecedor");
        MnItCadFornecedor.setName("7"); // NOI18N
        MnItCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadFornecedorActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadFornecedor);

        MnItFuncionario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnItFuncionario.setText("Funcionário");
        MnItFuncionario.setName("8"); // NOI18N
        MnItFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItFuncionarioActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItFuncionario);

        MnItCadCondicaoPagto.setText("Condição de Pagamento");
        MnItCadCondicaoPagto.setName("3"); // NOI18N
        MnItCadCondicaoPagto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadCondicaoPagtoActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadCondicaoPagto);

        MnItCadFormaPgto.setText("Forma de Pagamento");
        MnItCadFormaPgto.setName("4"); // NOI18N
        MnItCadFormaPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadFormaPgtoActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadFormaPgto);

        MnItCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnItCadUsuario.setText("Usuário");
        MnItCadUsuario.setName("5"); // NOI18N
        MnItCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadUsuarioActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadUsuario);

        MnItCadEstado.setText("Estado");
        MnItCadEstado.setName("1"); // NOI18N
        MnItCadEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadEstadoActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadEstado);

        MnItCadCidade.setText("Cidade");
        MnItCadCidade.setName("2"); // NOI18N
        MnItCadCidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadCidadeActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadCidade);

        MnItCadMultas.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnItCadMultas.setText("Multas");
        MnItCadMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadMultasActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadMultas);

        MnItCadOperacoes.setText("Operações");
        MnItCadOperacoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadOperacoesActionPerformed(evt);
            }
        });
        MnCadastros.add(MnItCadOperacoes);

        jMenuBar1.add(MnCadastros);

        MnFinanceiro.setText("Financeiro");

        MnItContasReceber.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        MnItContasReceber.setText("Contas à Receber");
        MnItContasReceber.setName("9"); // NOI18N
        MnItContasReceber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItContasReceberActionPerformed(evt);
            }
        });
        MnFinanceiro.add(MnItContasReceber);

        MnItContasPagar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.ALT_MASK));
        MnItContasPagar.setText("Contas à Pagar");
        MnItContasPagar.setName("10"); // NOI18N
        MnItContasPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItContasPagarActionPerformed(evt);
            }
        });
        MnFinanceiro.add(MnItContasPagar);

        MnItMovimentacaoCaixa.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        MnItMovimentacaoCaixa.setText("Movimentação de Caixa");
        MnItMovimentacaoCaixa.setName("11"); // NOI18N
        MnItMovimentacaoCaixa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItMovimentacaoCaixaActionPerformed(evt);
            }
        });
        MnFinanceiro.add(MnItMovimentacaoCaixa);

        jMenuBar1.add(MnFinanceiro);

        MnProduto.setText("Produto");

        MnItCadProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnItCadProduto.setText("Produto");
        MnItCadProduto.setName("12"); // NOI18N
        MnItCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadProdutoActionPerformed(evt);
            }
        });
        MnProduto.add(MnItCadProduto);

        MnItCadTipoProduto.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        MnItCadTipoProduto.setText("Tipo de Produto");
        MnItCadTipoProduto.setName("13"); // NOI18N
        MnItCadTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadTipoProdutoActionPerformed(evt);
            }
        });
        MnProduto.add(MnItCadTipoProduto);

        MnItCadTabelas.setText("Características e Especificações");
        MnItCadTabelas.setName("14"); // NOI18N
        MnItCadTabelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItCadTabelasActionPerformed(evt);
            }
        });
        MnProduto.add(MnItCadTabelas);

        MnItEstoque.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        MnItEstoque.setText("Estoque");
        MnItEstoque.setName("15"); // NOI18N
        MnItEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MnItEstoqueActionPerformed(evt);
            }
        });
        MnProduto.add(MnItEstoque);

        jMenuBar1.add(MnProduto);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void MnItCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadProdutoActionPerformed
        final InterfaceProduto tela = new InterfaceProduto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadProdutoActionPerformed

    private void LbSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbSairMouseClicked
        InterfaceLogin login = new InterfaceLogin();
        login.setSedispose(false);
        dispose();
    }//GEN-LAST:event_LbSairMouseClicked

    private void BtVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtVendaActionPerformed
        final InterfaceVenda tela = new InterfaceVenda(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_BtVendaActionPerformed

    private void BtCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCompraActionPerformed
        final InterfaceCompra tela = new InterfaceCompra(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_BtCompraActionPerformed

    private void BtContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtContasReceberActionPerformed
        final InterfaceContasReceber tela = new InterfaceContasReceber(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_BtContasReceberActionPerformed

    private void BtContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtContasPagarActionPerformed
        final InterfaceContasPagar tela = new InterfaceContasPagar(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_BtContasPagarActionPerformed

    private void BtMvtoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtMvtoCaixaActionPerformed
        final InterfaceMovimentacaoCaixa tela = new InterfaceMovimentacaoCaixa(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtMvtoCaixaActionPerformed

    private void MnItCadEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadEstadoActionPerformed
        final InterfaceEstado tela = new InterfaceEstado(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_MnItCadEstadoActionPerformed

    private void MnItCadCidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadCidadeActionPerformed
        final InterfaceCidade tela = new InterfaceCidade(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadCidadeActionPerformed

    private void MnItCadCondicaoPagtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadCondicaoPagtoActionPerformed
        final InterfaceCondicaoPagto tela = new InterfaceCondicaoPagto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadCondicaoPagtoActionPerformed

    private void MnItCadFormaPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadFormaPgtoActionPerformed
        final InterfaceFormaPagto tela = new InterfaceFormaPagto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadFormaPgtoActionPerformed

    private void MnItCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadClienteActionPerformed
        final InterfaceCliente tela = new InterfaceCliente(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadClienteActionPerformed

    private void MnItContasReceberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItContasReceberActionPerformed
        BtContasReceberActionPerformed(evt);
    }//GEN-LAST:event_MnItContasReceberActionPerformed

    private void MnItContasPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItContasPagarActionPerformed
        BtContasPagarActionPerformed(evt);
    }//GEN-LAST:event_MnItContasPagarActionPerformed

    private void MnItMovimentacaoCaixaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItMovimentacaoCaixaActionPerformed
        BtMvtoCaixaActionPerformed(evt);
    }//GEN-LAST:event_MnItMovimentacaoCaixaActionPerformed

    private void MnItCadTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadTipoProdutoActionPerformed
        final InterfaceTipoProduto tela = new InterfaceTipoProduto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadTipoProdutoActionPerformed

    private void MnItCadTabelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadTabelasActionPerformed
        final InterfaceTabelas tela = new InterfaceTabelas(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadTabelasActionPerformed

    private void MnItCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadUsuarioActionPerformed
        final InterfaceUsuario tela = new InterfaceUsuario(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadUsuarioActionPerformed

    private void MnItCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadFornecedorActionPerformed
        final InterfaceFornecedor tela = new InterfaceFornecedor(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadFornecedorActionPerformed

    private void MnItFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItFuncionarioActionPerformed
        final InterfaceFuncionario tela = new InterfaceFuncionario(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItFuncionarioActionPerformed

    private void MnItCadMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadMultasActionPerformed
        final InterfaceMultas tela = new InterfaceMultas(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadMultasActionPerformed

    private void MnItCadOperacoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItCadOperacoesActionPerformed
        final InterfaceOperacoes tela = new InterfaceOperacoes(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_MnItCadOperacoesActionPerformed

    private void BtRealizarOperacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRealizarOperacaoActionPerformed
        final InterfaceRealizarOperacoes tela = new InterfaceRealizarOperacoes(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_BtRealizarOperacaoActionPerformed

    private void BtEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEstoqueActionPerformed
        final InterfaceEstoque tela = new InterfaceEstoque(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_BtEstoqueActionPerformed

    private void MnItEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MnItEstoqueActionPerformed
        BtEstoqueActionPerformed(evt);
    }//GEN-LAST:event_MnItEstoqueActionPerformed

    private void BtPagamentoFuncionariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPagamentoFuncionariosActionPerformed
        final InterfacePagamentoFuncionarios tela = new InterfacePagamentoFuncionarios(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_BtPagamentoFuncionariosActionPerformed

    private void LbQtProdutosBaixosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbQtProdutosBaixosMouseClicked
        if(BtEstoque.isEnabled())
        BtEstoqueActionPerformed(null);
    }//GEN-LAST:event_LbQtProdutosBaixosMouseClicked

    private void LbContasReceberVencidasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbContasReceberVencidasMouseClicked
        if(BtContasReceber.isEnabled())
        BtContasReceberActionPerformed(null);
    }//GEN-LAST:event_LbContasReceberVencidasMouseClicked

    private void LbContasReceberAbertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbContasReceberAbertasMouseClicked
        if(BtContasReceber.isEnabled())
        BtContasReceberActionPerformed(null);
    }//GEN-LAST:event_LbContasReceberAbertasMouseClicked

    private void LbContasPagarVencidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbContasPagarVencidaMouseClicked
        if(BtContasPagar.isEnabled())
        BtContasPagarActionPerformed(null);
    }//GEN-LAST:event_LbContasPagarVencidaMouseClicked

    private void LbContasPagarAbertasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LbContasPagarAbertasMouseClicked
        if(BtContasPagar.isEnabled())
        BtContasPagarActionPerformed(null);
    }//GEN-LAST:event_LbContasPagarAbertasMouseClicked

    private void BtRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRelatoriosActionPerformed
        final InterfaceRelatorios tela = new InterfaceRelatorios(getPrimeiratela(), true);
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                atualizasituacao();
            }
        });
    }//GEN-LAST:event_BtRelatoriosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCompra;
    private javax.swing.JButton BtContasPagar;
    private javax.swing.JButton BtContasReceber;
    private javax.swing.JButton BtEstoque;
    private javax.swing.JButton BtMvtoCaixa;
    private javax.swing.JButton BtPagamentoFuncionarios;
    private javax.swing.JButton BtRealizarOperacao;
    private javax.swing.JButton BtRelatorios;
    private javax.swing.JButton BtVenda;
    private javax.swing.JLabel LbContasPagarAbertas;
    private javax.swing.JLabel LbContasPagarVencida;
    private javax.swing.JLabel LbContasReceberAbertas;
    private javax.swing.JLabel LbContasReceberVencidas;
    private javax.swing.JLabel LbNmUsuario;
    private javax.swing.JLabel LbQtProdutosBaixos;
    private javax.swing.JLabel LbSair;
    private javax.swing.JMenu MnCadastros;
    private javax.swing.JMenu MnFinanceiro;
    private javax.swing.JMenuItem MnItCadCidade;
    private javax.swing.JMenuItem MnItCadCliente;
    private javax.swing.JMenuItem MnItCadCondicaoPagto;
    private javax.swing.JMenuItem MnItCadEstado;
    private javax.swing.JMenuItem MnItCadFormaPgto;
    private javax.swing.JMenuItem MnItCadFornecedor;
    private javax.swing.JMenuItem MnItCadMultas;
    private javax.swing.JMenuItem MnItCadOperacoes;
    private javax.swing.JMenuItem MnItCadProduto;
    private javax.swing.JMenuItem MnItCadTabelas;
    private javax.swing.JMenuItem MnItCadTipoProduto;
    private javax.swing.JMenuItem MnItCadUsuario;
    private javax.swing.JMenuItem MnItContasPagar;
    private javax.swing.JMenuItem MnItContasReceber;
    private javax.swing.JMenuItem MnItEstoque;
    private javax.swing.JMenuItem MnItFuncionario;
    private javax.swing.JMenuItem MnItMovimentacaoCaixa;
    private javax.swing.JMenu MnProduto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void liberatelas() {
        ResultSet telasdousuario = getTelasusuario().retornatelasusuario();
        try {
            while (telasdousuario.next()) {
                procuratela(telasdousuario.getInt(1));
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
        }
    }

    public void procuratela(int cdtela) {
        switch(cdtela){
            case 1:{
                MnItCadCliente.setEnabled(true);
                
                break;
            }
            case 2:{
                MnItCadFornecedor.setEnabled(true);
                break;
            }
            case 3:{
                MnItFuncionario.setEnabled(true);
                break;
            }
            case 4:{
                MnItCadEstado.setEnabled(true);
                break;
            }
            case 5:{
                MnItCadCidade.setEnabled(true);
                break;
            }
            case 6:{
                MnItCadCondicaoPagto.setEnabled(true);
                break;
            }
            case 7:{
                MnItCadFormaPgto.setEnabled(true);
                break;
            }
            case 8:{
                MnItCadUsuario.setEnabled(true);
                break;
            }
            case 9:{
                MnItCadMultas.setEnabled(true);
                break;
            }
            case 10:{
                MnItCadOperacoes.setEnabled(true);
                break;
            }
            case 11:{
                MnItCadProduto.setEnabled(true);
                break;
            }
            case 12:{
                MnItCadTipoProduto.setEnabled(true);
                break;
            }
            case 13:{
                MnItCadTabelas.setEnabled(true);
                break;
            }
            case 14:{
                MnItEstoque.setEnabled(true);
                BtEstoque.setEnabled(true);
                break;
            }
            case 15:{
                BtVenda.setEnabled(true);
                break;
            }
            case 16:{
                BtCompra.setEnabled(true);
                break;
            }
            case 17:{
                MnItContasReceber.setEnabled(true);
                BtContasReceber.setEnabled(true);
                break;
            }
            case 18:{
                MnItContasPagar.setEnabled(true);
                BtContasPagar.setEnabled(true);
                break;
            }
            case 19:{
                MnItMovimentacaoCaixa.setEnabled(true);
                BtMvtoCaixa.setEnabled(true);
                break;
            }
            case 20:{
                BtPagamentoFuncionarios.setEnabled(true);
                break;
            }
            case 21:{
                BtRelatorios.setEnabled(true);
                break;
            }
            case 22:{
                BtRealizarOperacao.setEnabled(true);
                break;
            }
        }
    }

    public void atualizasituacao(){
        int aux;
        ClasseMvtoEstoque mvtoestoque = new ClasseMvtoEstoque();
        ClasseParcelas parcelas = new ClasseParcelas();
        parcelas.atualizaparcelasecontas();
        aux = parcelas.getConta().retornanumerocontasreceberabertas();
        if (aux == 0){
            LbContasReceberAbertas.setText("Nenhuma Conta a Receber em Aberto");
            LbContasReceberAbertas.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_verde.png")));
        } else {
            LbContasReceberAbertas.setText("Existem "+aux+" Contas a Receber em Aberto");
            LbContasReceberAbertas.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_amarela.png")));
        }
        
        aux = parcelas.getConta().retornanumerocontasrecebervencidas();
        if (aux == 0){
            LbContasReceberVencidas.setText("Nenhuma Conta a Receber Vencida");
            LbContasReceberVencidas.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_verde.png")));
        } else {
            LbContasReceberVencidas.setText("Existem "+aux+" Contas a Receber Vencidas");
            LbContasReceberVencidas.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_vermelha.png")));
        }
        
        aux = parcelas.getConta().retornanumerocontaspagarabertas();
        if (aux == 0){
            LbContasPagarAbertas.setText("Nenhuma Conta a Pagar em Aberto");
            LbContasPagarAbertas.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_verde.png")));
        } else {
            LbContasPagarAbertas.setText("Existem "+aux+" Contas a Pagar em Aberto");
            LbContasPagarAbertas.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_amarela.png")));
        }
        
        aux = parcelas.getConta().retornanumerocontaspagarvencidas();
        if (aux == 0){
            LbContasPagarVencida.setText("Nenhuma Conta a Pagar Vencida");
            LbContasPagarVencida.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_verde.png")));
        } else {
            LbContasPagarVencida.setText("Existem "+aux+" Contas a Pagar Vencidas");
            LbContasPagarVencida.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_vermelha.png")));
        }
        
        aux = mvtoestoque.retornanumerodeprodutoscomestoquebaixo();
        if (aux == 0){
            LbQtProdutosBaixos.setText("Nenhum Produto com Estoque Baixo");
            LbQtProdutosBaixos.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_verde.png")));
        } else {
            LbQtProdutosBaixos.setText("Existem "+aux+" Produtos com Estoque Baixo");
            LbQtProdutosBaixos.setIcon(new ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/bandeira_vermelha.png")));
        }
    }
    
    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
