package br.com.lojadafatima.InterfacesProduto;

import br.com.lojadafatima.InterfacesPessoa.InterfaceFornecedor;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFornecedor;
import br.com.lojadafatima.Produto.ClasseEspecificacaoProduto;
import br.com.lojadafatima.Produto.ClasseFornecedoresProduto;
import br.com.lojadafatima.Produto.ClasseProduto;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author hp
 */
public class InterfaceProduto extends javax.swing.JDialog {

    MaskFormatter valor;
    private java.awt.Frame primeiratela;
    Preenche preenche = new Preenche();
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    LimpaCamposTela limpar = new LimpaCamposTela();
    ClasseEspecificacaoProduto especproduto = new ClasseEspecificacaoProduto();
    ClasseFornecedoresProduto forneproduto = new ClasseFornecedoresProduto();

    /**
     * Creates new form InterfaceProduto
     */
    public InterfaceProduto(java.awt.Frame telaorigem, boolean modal) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        valida.validacamposCancelar(PnProduto, PnBotoes);
        valida.validacamposCancelar(PnFornecedor, PnBotoes);
        TfCodFornecedor.setDocument(new PermiteApenasNumeros());
        preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());

        int[] tam = new int[2];
        tam[0] = 50;
        tam[1] = 200;
        preenche.FormataJtable(TbCarcteristica, tam);
        preenche.FormataJtable(TbEspecificacao, tam);
        tam[0] = 10;
        tam[1] = 400;
        preenche.FormataJtable(TbFornecedoresProd, tam);

        int[] tam2 = new int[4];
        tam2[0] = 20;
        tam2[1] = 100;
        tam2[2] = 20;
        tam2[3] = 50;
        preenche.FormataJtable(TbProduto, tam2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        TabbedPaneProduto = new javax.swing.JTabbedPane();
        PnCadastro = new javax.swing.JPanel();
        PnBotoes = new javax.swing.JPanel();
        BtGravar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtIncluir = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        TabbedPaneCadastro = new javax.swing.JTabbedPane();
        PnProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        TfDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtCadTipoProduto = new javax.swing.JButton();
        CbTipoProduto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbCarcteristica = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbEspecificacao = new javax.swing.JTable();
        BtCadTabela2 = new javax.swing.JButton();
        BtIncluirEspecific = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbProduto = new javax.swing.JTable();
        BtRemoverEspecific = new javax.swing.JButton();
        TfValor = new JNumberField.JNumberField();
        TfQtEstoqueMin = new JNumberField.JNumberField(2);
        ;
        PnFornecedor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TfCodFornecedor = new javax.swing.JTextField();
        BtAddFornecedor = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TbFornecedoresProd = new javax.swing.JTable();
        BtPesqFornecedor = new javax.swing.JButton();
        TfFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtCadFornecedor = new javax.swing.JButton();
        BtDelFornecedor = new javax.swing.JButton();
        PnConsulta = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CbPesquisa = new javax.swing.JComboBox();
        TfPesquisa = new javax.swing.JTextField();
        BtPesquisar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TbConsulta = new javax.swing.JTable();

        jMenuItem1.setText("Carregar dados");
        jMenuItem1.setComponentPopupMenu(jPopupMenu1);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos - Software Loja da Fátima");

        BtGravar.setText("Gravar");
        BtGravar.setName("Gravar"); // NOI18N
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtAlterar.setText("Alterar Dados");
        BtAlterar.setName("Alterar"); // NOI18N
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtIncluir.setText("Novo Produto");
        BtIncluir.setName("Incluir"); // NOI18N
        BtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirActionPerformed(evt);
            }
        });

        BtExcluir.setText("Excluir Produto");
        BtExcluir.setName("Excluir"); // NOI18N
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtCancelar.setText("Cancelar");
        BtCancelar.setName("Cancelar"); // NOI18N
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotoesLayout = new javax.swing.GroupLayout(PnBotoes);
        PnBotoes.setLayout(PnBotoesLayout);
        PnBotoesLayout.setHorizontalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotoesLayout.createSequentialGroup()
                .addComponent(BtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnBotoesLayout.setVerticalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(BtAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setText("Código");

        TfCodigo.setEditable(false);

        TfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfDescricaoKeyPressed(evt);
            }
        });

        jLabel5.setText("Descrição do Produto*");

        jLabel9.setText("Valor do Produto*");

        jLabel12.setText("Quantidade Mínima de Estoque*");

        BtCadTipoProduto.setText("Cadastrar Tipo de Produto");
        BtCadTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadTipoProdutoActionPerformed(evt);
            }
        });

        CbTipoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbTipoProdutoMouseClicked(evt);
            }
        });
        CbTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTipoProdutoActionPerformed(evt);
            }
        });

        jLabel2.setText("Tipo de Produto*");

        jLabel6.setText("Características do tipo do produto:");

        TbCarcteristica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Característica"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbCarcteristica.getTableHeader().setReorderingAllowed(false);
        TbCarcteristica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbCarcteristicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbCarcteristica);
        if (TbCarcteristica.getColumnModel().getColumnCount() > 0) {
            TbCarcteristica.getColumnModel().getColumn(0).setResizable(false);
            TbCarcteristica.getColumnModel().getColumn(1).setResizable(false);
        }

        jLabel7.setText("Especificação:");

        TbEspecificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Especificação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbEspecificacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TbEspecificacao);
        if (TbEspecificacao.getColumnModel().getColumnCount() > 0) {
            TbEspecificacao.getColumnModel().getColumn(0).setResizable(false);
            TbEspecificacao.getColumnModel().getColumn(1).setResizable(false);
        }

        BtCadTabela2.setText("Cadastrar Característica");
        BtCadTabela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadTabelaActionPerformed(evt);
            }
        });

        BtIncluirEspecific.setText("Incluir ao Produto");
        BtIncluirEspecific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirEspecificActionPerformed(evt);
            }
        });

        jLabel8.setText("Produto*:");

        TbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cod. Caracteristica", "Caracteristica", "Cod Especificacao", "Especificação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbProduto.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TbProduto);
        if (TbProduto.getColumnModel().getColumnCount() > 0) {
            TbProduto.getColumnModel().getColumn(2).setResizable(false);
        }

        BtRemoverEspecific.setText("Remover");
        BtRemoverEspecific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverEspecificActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnProdutoLayout = new javax.swing.GroupLayout(PnProduto);
        PnProduto.setLayout(PnProdutoLayout);
        PnProdutoLayout.setHorizontalGroup(
            PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PnProdutoLayout.createSequentialGroup()
                        .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8)
                            .addComponent(BtRemoverEspecific)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 578, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PnProdutoLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(PnProdutoLayout.createSequentialGroup()
                                            .addComponent(BtIncluirEspecific)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(BtCadTabela2)
                                            .addGap(11, 11, 11))
                                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PnProdutoLayout.createSequentialGroup()
                        .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(PnProdutoLayout.createSequentialGroup()
                                .addComponent(CbTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtCadTipoProduto))
                            .addComponent(jLabel6)
                            .addGroup(PnProdutoLayout.createSequentialGroup()
                                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(TfDescricao))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(TfValor, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(TfQtEstoqueMin, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        PnProdutoLayout.setVerticalGroup(
            PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PnProdutoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel12))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCadTipoProduto)
                    .addComponent(TfQtEstoqueMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addGap(3, 3, 3)
                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnProdutoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtCadTabela2)
                    .addComponent(BtIncluirEspecific))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtRemoverEspecific)
                .addContainerGap())
        );

        TabbedPaneCadastro.addTab("Produto", PnProduto);

        jLabel3.setText("Código do Fornecedor*");

        TfCodFornecedor.setName("CD_FORNECEDOR"); // NOI18N
        TfCodFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCodFornecedorActionPerformed(evt);
            }
        });
        TfCodFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfCodFornecedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodFornecedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfCodFornecedorKeyTyped(evt);
            }
        });

        BtAddFornecedor.setText("Adicionar Fornecedor");
        BtAddFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddFornecedorActionPerformed(evt);
            }
        });

        TbFornecedoresProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbFornecedoresProd.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(TbFornecedoresProd);

        BtPesqFornecedor.setText("Pesquisar");
        BtPesqFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFornecedorActionPerformed(evt);
            }
        });

        TfFornecedor.setEditable(false);
        TfFornecedor.setName("NM_FANTASIA"); // NOI18N

        jLabel4.setText("Fornecedor");

        BtCadFornecedor.setText("Cadastrar Fornecedor");
        BtCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadFornecedorActionPerformed(evt);
            }
        });

        BtDelFornecedor.setText("Remover Fornecedor");
        BtDelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDelFornecedorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnFornecedorLayout = new javax.swing.GroupLayout(PnFornecedor);
        PnFornecedor.setLayout(PnFornecedorLayout);
        PnFornecedorLayout.setHorizontalGroup(
            PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane5)
                    .addGroup(PnFornecedorLayout.createSequentialGroup()
                        .addGap(441, 441, 441)
                        .addComponent(BtCadFornecedor))
                    .addGroup(PnFornecedorLayout.createSequentialGroup()
                        .addComponent(BtAddFornecedor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtDelFornecedor))
                    .addGroup(PnFornecedorLayout.createSequentialGroup()
                        .addGroup(PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PnFornecedorLayout.createSequentialGroup()
                                .addComponent(TfCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtPesqFornecedor))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(TfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        PnFornecedorLayout.setVerticalGroup(
            PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnFornecedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addGap(8, 8, 8)
                .addGroup(PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TfCodFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtPesqFornecedor)
                        .addComponent(TfFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BtCadFornecedor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(PnFornecedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtAddFornecedor)
                    .addComponent(BtDelFornecedor))
                .addGap(9, 9, 9)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPaneCadastro.addTab("Fornecedor", PnFornecedor);

        javax.swing.GroupLayout PnCadastroLayout = new javax.swing.GroupLayout(PnCadastro);
        PnCadastro.setLayout(PnCadastroLayout);
        PnCadastroLayout.setHorizontalGroup(
            PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(PnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(TabbedPaneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        PnCadastroLayout.setVerticalGroup(
            PnCadastroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnCadastroLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TabbedPaneCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, 485, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        TabbedPaneProduto.addTab("Cadastro", PnCadastro);

        jLabel13.setText("Consulta por:");

        CbPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos os produtos", "Código", "Descrição", "Código do Tipo de Produto" }));
        CbPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPesquisaActionPerformed(evt);
            }
        });

        TfPesquisa.setEnabled(false);

        BtPesquisar.setText("Pesquisar");
        BtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarActionPerformed(evt);
            }
        });

        TbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Tipo de Produto", "Valor(R$)", "Estoque minimo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbConsulta.setComponentPopupMenu(jPopupMenu1);
        TbConsulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TbConsulta);
        if (TbConsulta.getColumnModel().getColumnCount() > 0) {
            TbConsulta.getColumnModel().getColumn(0).setResizable(false);
        }

        javax.swing.GroupLayout PnConsultaLayout = new javax.swing.GroupLayout(PnConsulta);
        PnConsulta.setLayout(PnConsultaLayout);
        PnConsultaLayout.setHorizontalGroup(
            PnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 611, Short.MAX_VALUE)
                    .addGroup(PnConsultaLayout.createSequentialGroup()
                        .addComponent(CbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TfPesquisa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PnConsultaLayout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PnConsultaLayout.setVerticalGroup(
            PnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PnConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                .addContainerGap())
        );

        TabbedPaneProduto.addTab("Consulta", PnConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneProduto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneProduto)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadTipoProdutoActionPerformed
        final InterfaceTipoProduto tela = new InterfaceTipoProduto(getPrimeiratela(), true);
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());
            }
        });
    }//GEN-LAST:event_BtCadTipoProdutoActionPerformed

    private void BtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirActionPerformed
        limpar.Limpar(PnProduto);
        limpar.Limpar(PnFornecedor);
        limpar.Limpar(TbFornecedoresProd);
        limpar.Limpar(TbCarcteristica);
        limpar.Limpar(TbEspecificacao);
        limpar.Limpar(TbProduto);
        preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());
        valida.validacamposCadastrar(PnProduto, PnBotoes);
        valida.validacamposCadastrar(PnFornecedor, PnBotoes);
    }//GEN-LAST:event_BtIncluirActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        if (!TfCodigo.getText().equals("")) {
            valida.validacamposCadastrar(PnProduto, PnBotoes);
            valida.validacamposCadastrar(PnFornecedor, PnBotoes);
            CbTipoProduto.setEnabled(false);
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto na aba \"Consulta\" e carregue os dados para que a operacao seja realizada!", "Selecione um produto", JOptionPane.YES_NO_OPTION);
            TabbedPaneProduto.setSelectedIndex(1);
            CbPesquisa.grabFocus();
        }
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadFornecedorActionPerformed
        final InterfaceFornecedor tela = new InterfaceFornecedor(getPrimeiratela(), true);
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadFornecedorActionPerformed

    private void TbCarcteristicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbCarcteristicaMouseClicked
        int index = TbCarcteristica.getSelectedRow();
        if (index > -1) {
            especproduto.getTipoproduto().getTabela().setCodigo(Integer.parseInt(TbCarcteristica.getValueAt(index, 0).toString()));
            preenche.PreencherJtable(TbEspecificacao, especproduto.getTipoproduto().getTabela().buscarvalorestabela());
        }
    }//GEN-LAST:event_TbCarcteristicaMouseClicked

    private void BtIncluirEspecificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirEspecificActionPerformed
        if (TbEspecificacao.getSelectedRow() > -1) {
            DefaultTableModel tabela = (DefaultTableModel) TbProduto.getModel();
            int linhas = tabela.getRowCount();
            int index = TbCarcteristica.getSelectedRow();
            int posexclui = -1;
            boolean substitui = false;
            for (int i = 0; i < linhas; i++) {
                if (tabela.getValueAt(i, 0).toString().equals(TbCarcteristica.getValueAt(index, 0).toString())) {
                    substitui = true;
                    posexclui = i;
                }
            }
            int indexespecific = TbEspecificacao.getSelectedRow();
            if (substitui) {
                tabela.setNumRows(linhas + 1);
                tabela.setValueAt(TbEspecificacao.getValueAt(indexespecific, 0).toString(), linhas, 2);
                tabela.setValueAt(TbEspecificacao.getValueAt(indexespecific, 1).toString(), linhas, 3);
                tabela.setValueAt(TbCarcteristica.getValueAt(index, 0).toString(), linhas, 0);
                tabela.setValueAt(TbCarcteristica.getValueAt(index, 1).toString(), linhas, 1);
                tabela.removeRow(posexclui);
            } else {
                tabela.setNumRows(linhas + 1);
                tabela.setValueAt(TbEspecificacao.getValueAt(indexespecific, 0).toString(), linhas, 2);
                tabela.setValueAt(TbEspecificacao.getValueAt(indexespecific, 1).toString(), linhas, 3);
                tabela.setValueAt(TbCarcteristica.getValueAt(index, 0).toString(), linhas, 0);
                tabela.setValueAt(TbCarcteristica.getValueAt(index, 1).toString(), linhas, 1);
            }
        }
    }//GEN-LAST:event_BtIncluirEspecificActionPerformed

    private void CbTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTipoProdutoActionPerformed
        limpar.Limpar(TbEspecificacao);
        limpar.Limpar(TbProduto);
        if (CbTipoProduto.getSelectedItem() == null) {
            preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());
        }
        especproduto.getTipoproduto().setTipoproduto(CbTipoProduto.getSelectedItem().toString());
        especproduto.getTipoproduto().setCodigo(especproduto.getTipoproduto().retornacodigo());
        preenche.PreencherJtable(TbCarcteristica, especproduto.getTipoproduto().buscartabelasdotipoproduto());
    }//GEN-LAST:event_CbTipoProdutoActionPerformed

    private void CbTipoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbTipoProdutoMouseClicked

    }//GEN-LAST:event_CbTipoProdutoMouseClicked

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (camposobrigatoriospreenchidos()) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja gravar os dados deste produto?", "Deseja gravar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                enviardados();
                if (TfCodigo.getText().equals("")) {
                    especproduto.getProduto().incluir();
                    for (int i = 0; i < TbProduto.getRowCount(); i++) {
                        especproduto.getTipoproduto().getTabela().setCodigo(Integer.parseInt(TbProduto.getValueAt(i, 0).toString()));
                        especproduto.getTipoproduto().getTabela().getValor().setCodigo(Integer.parseInt(TbProduto.getValueAt(i, 2).toString()));
                        especproduto.incluirespecific();
                    }
                    forneproduto.getProduto().setCodigo(especproduto.getProduto().getCodigo());
                    for (int i = 0; i < TbFornecedoresProd.getRowCount(); i++) {
                        forneproduto.getFornecedor().setCodigo(Integer.parseInt(TbFornecedoresProd.getValueAt(i, 0).toString()));
                        forneproduto.incluirfornecedor();
                    }
                    JOptionPane.showMessageDialog(null, "Codigo: " + especproduto.getProduto().getCodigo() + "\n"
                            + "Produto: " + especproduto.getProduto().getDescricao().toUpperCase(), "Codigo do produto", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    especproduto.getProduto().setCodigo(Integer.parseInt(TfCodigo.getText()));
                    forneproduto.getProduto().setCodigo(Integer.parseInt(TfCodigo.getText()));
                    especproduto.getProduto().alterar();
                    for (int i = 0; i < TbProduto.getRowCount(); i++) {
                        especproduto.getTipoproduto().getTabela().setCodigo(Integer.parseInt(TbProduto.getValueAt(i, 0).toString()));
                        especproduto.getTipoproduto().getTabela().getValor().setCodigo(Integer.parseInt(TbProduto.getValueAt(i, 2).toString()));
                        especproduto.alterarespecific();
                    }
                    forneproduto.excluirfornecedores();
                    for (int i = 0; i < TbFornecedoresProd.getRowCount(); i++) {
                        forneproduto.getFornecedor().setCodigo(Integer.parseInt(TbFornecedoresProd.getValueAt(i, 0).toString()));
                        forneproduto.incluirfornecedor();
                    }
                    BtPesquisarActionPerformed(evt);
                }
                limpar.Limpar(PnProduto);
                limpar.Limpar(PnFornecedor);
                limpar.Limpar(TbFornecedoresProd);
                limpar.Limpar(TbCarcteristica);
                limpar.Limpar(TbEspecificacao);
                limpar.Limpar(TbProduto);
                valida.validacamposCancelar(PnProduto, PnBotoes);
                valida.validacamposCancelar(PnFornecedor, PnBotoes);
            }
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtCadTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadTabelaActionPerformed
        final InterfaceTabelas tela = new InterfaceTabelas(getPrimeiratela(), true);
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                TbCarcteristicaMouseClicked(null);
            }
        });
    }//GEN-LAST:event_BtCadTabelaActionPerformed

    private void BtRemoverEspecificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverEspecificActionPerformed
        if (TbProduto.getSelectedRow() > -1) {
            DefaultTableModel tabela = (DefaultTableModel) TbProduto.getModel();
            tabela.removeRow(TbProduto.getSelectedRow());
        }
    }//GEN-LAST:event_BtRemoverEspecificActionPerformed

    private void BtAddFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddFornecedorActionPerformed
        if (!TfCodFornecedor.getText().equals("") && !TfFornecedor.getText().equals("")) {
            boolean inclui = true;
            for (int i = 0; i < TbFornecedoresProd.getRowCount(); i++) {
                if ((TfCodFornecedor.getText().equals(TbFornecedoresProd.getValueAt(i, 0).toString())) && (TfFornecedor.getText().equals(TbFornecedoresProd.getValueAt(i, 1).toString()))) {
                    inclui = false;
                }
            }
            if (inclui) {
                DefaultTableModel tabela = (DefaultTableModel) TbFornecedoresProd.getModel();
                int linha = tabela.getRowCount();
                tabela.setRowCount(linha + 1);
                tabela.setValueAt(TfCodFornecedor.getText(), linha, 0);
                tabela.setValueAt(TfFornecedor.getText(), linha, 1);
                TfCodFornecedor.setText("");
                TfFornecedor.setText("");
            }
        }
    }//GEN-LAST:event_BtAddFornecedorActionPerformed

    private void TfCodFornecedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFornecedorKeyTyped

    }//GEN-LAST:event_TfCodFornecedorKeyTyped

    private void TfCodFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCodFornecedorActionPerformed

    }//GEN-LAST:event_TfCodFornecedorActionPerformed

    private void TfCodFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFornecedorKeyPressed

    }//GEN-LAST:event_TfCodFornecedorKeyPressed

    private void TfCodFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFornecedorKeyReleased
        if (!TfCodFornecedor.getText().equals("")) {
            forneproduto.getFornecedor().setCodigo(Integer.parseInt(TfCodFornecedor.getText()));
            if (forneproduto.getFornecedor().efornecedorativo()) {
                forneproduto.getFornecedor().getPessoajur().getPessoa().setCodigo(forneproduto.getFornecedor().retornacodigopessoafornecedor());
                TfFornecedor.setText(forneproduto.getFornecedor().getPessoajur().retornanomeporCodigo());
            } else {
                TfFornecedor.setText("");
            }
        } else {
            TfFornecedor.setText("");
        }
    }//GEN-LAST:event_TfCodFornecedorKeyReleased

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar esta operacao?\n"
                + "(Caso queira, TODOS os dados serao limpos da tela)", "Deseja cancelar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpar.Limpar(PnProduto);
            limpar.Limpar(PnFornecedor);
            limpar.Limpar(TbFornecedoresProd);
            limpar.Limpar(TbCarcteristica);
            limpar.Limpar(TbEspecificacao);
            limpar.Limpar(TbProduto);
            valida.validacamposCancelar(PnProduto, PnBotoes);
            valida.validacamposCancelar(PnFornecedor, PnBotoes);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        if (!TfCodigo.getText().equals("")) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja EXCLUIR os dados deste produto?", "Deseja excluir?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                especproduto.getProduto().setCodigo(Integer.parseInt(TfCodigo.getText()));
                especproduto.getProduto().excluir();
                BtPesquisarActionPerformed(evt);
                limpar.Limpar(PnProduto);
                limpar.Limpar(PnFornecedor);
                limpar.Limpar(TbFornecedoresProd);
                limpar.Limpar(TbCarcteristica);
                limpar.Limpar(TbEspecificacao);
                limpar.Limpar(TbProduto);
                valida.validacamposCancelar(PnProduto, PnBotoes);
                valida.validacamposCancelar(PnFornecedor, PnBotoes);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto na aba \"Consulta\" e carregue os dados para que a operacao seja realizada!", "Selecione um produto", JOptionPane.YES_NO_OPTION);
            TabbedPaneProduto.setSelectedIndex(1);
            CbPesquisa.grabFocus();
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtDelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDelFornecedorActionPerformed
        if (TbFornecedoresProd.getSelectedRow() > -1) {
            DefaultTableModel tabela = (DefaultTableModel) TbFornecedoresProd.getModel();
            tabela.removeRow(TbFornecedoresProd.getSelectedRow());
        }
    }//GEN-LAST:event_BtDelFornecedorActionPerformed

    private void BtPesqFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFornecedorActionPerformed
        final ConsulSimplesFornecedor tela = new ConsulSimplesFornecedor(getPrimeiratela(), true, forneproduto.getFornecedor());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (forneproduto.getFornecedor().getCodigo() != 0) {
                    TfCodFornecedor.setText("" + forneproduto.getFornecedor().getCodigo());
                    TfCodFornecedorKeyReleased(null);
                } else {
                    TfCodFornecedor.setText("");
                    TfFornecedor.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqFornecedorActionPerformed

    private void CbPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPesquisaActionPerformed
        switch (CbPesquisa.getSelectedIndex()) {
            case 0: {
                TfPesquisa.setEnabled(false);
                TfPesquisa.setDocument(TfDescricao.getDocument());
                break;
            }
            case 1: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(new PermiteApenasNumeros());
                break;
            }
            case 2: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(TfDescricao.getDocument());
                break;
            }
            case 3: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(new PermiteApenasNumeros());
                break;
            }
        }
    }//GEN-LAST:event_CbPesquisaActionPerformed

    private void BtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarActionPerformed
        int[] tam = new int[5];
        tam[0] = 15;
        tam[1] = 100;
        tam[2] = 70;
        tam[3] = 20;
        tam[4] = 20;
        preenche.FormataJtable(TbConsulta, tam);
        switch (CbPesquisa.getSelectedIndex()) {
            case 0: {
                preenche.PreencherJtable(TbConsulta, especproduto.getProduto().consultageral());
                break;
            }
            case 1: {
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o codigo do produto que deseja consultar!", "Digite a informacao", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    especproduto.getProduto().setCodigo(Integer.parseInt(TfPesquisa.getText()));
                    preenche.PreencherJtable(TbConsulta, especproduto.getProduto().consultacodigo());
                }
                break;
            }
            case 2: {
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite a descricao do produto que deseja consultar!", "Digite a informacao", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    especproduto.getProduto().setDescricao(TfPesquisa.getText());
                    preenche.PreencherJtable(TbConsulta, especproduto.getProduto().consultadescricao());
                }
                break;
            }
            case 3: {
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o codigo do tipo de produto que deseja consultar!", "Digite a informacao", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    especproduto.getTipoproduto().setCodigo(Integer.parseInt(TfPesquisa.getText()));
                    preenche.PreencherJtable(TbConsulta, especproduto.consultatipoproduto());
                }
                break;
            }
        }
    }//GEN-LAST:event_BtPesquisarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (TbConsulta.getSelectedRow() > -1) {
            especproduto.getProduto().setCodigo(Integer.parseInt(TbConsulta.getValueAt(TbConsulta.getSelectedRow(), 0).toString()));
            especproduto.retornaproduto();
            TfCodigo.setText("" + especproduto.getProduto().getCodigo());
            TfDescricao.setText(especproduto.getProduto().getDescricao());
            TfValor.setValue(BigDecimal.valueOf(especproduto.getProduto().getValor()));
            TfQtEstoqueMin.setValue(BigDecimal.valueOf(especproduto.getProduto().getEstoquemin()));
            if (CbTipoProduto.getSelectedItem() == null) {
                preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());
            }
            CbTipoProduto.setSelectedItem(especproduto.getTipoproduto().getTipoproduto());
            CbTipoProdutoActionPerformed(evt);

            limpar.Limpar(TbProduto);
            limpar.Limpar(TbFornecedoresProd);

            ResultSet rs = especproduto.retornacaracproduto();
            DefaultTableModel tabela = (DefaultTableModel) TbProduto.getModel();
            try {
                for (int i = 0; rs.next(); i++) {
                    especproduto.getTipoproduto().getTabela().setCodigo(rs.getInt(1));
                    especproduto.getTipoproduto().getTabela().getValor().setCodigoTabela(rs.getInt(1));
                    especproduto.getTipoproduto().getTabela().getValor().setCodigo(rs.getInt(2));
                    tabela.setRowCount(i + 1);
                    tabela.setValueAt(especproduto.getTipoproduto().getTabela().getCodigo(), i, 0);
                    tabela.setValueAt(especproduto.getTipoproduto().getTabela().retornatabela(), i, 1);
                    tabela.setValueAt(especproduto.getTipoproduto().getTabela().getValor().getCodigo(), i, 2);
                    tabela.setValueAt(especproduto.getTipoproduto().getTabela().getValor().retornavalor(), i, 3);
                }
            } catch (SQLException ex) {
            }

            forneproduto.getProduto().setCodigo(Integer.parseInt(TbConsulta.getValueAt(TbConsulta.getSelectedRow(), 0).toString()));
            rs = forneproduto.retornafornecedoresproduto();
            try {
                for (int i = 0; rs.next(); i++) {
                    TfCodFornecedor.setText(rs.getString(1));
                    TfCodFornecedorKeyReleased(null);
                    BtAddFornecedorActionPerformed(evt);
                }
            } catch (SQLException ex) {

            }

            TfCodFornecedor.setText("");
            TfFornecedor.setText("");

            valida.validacamposCancelar(PnProduto, PnBotoes);
            valida.validacamposCancelar(PnFornecedor, PnBotoes);
            TabbedPaneProduto.setSelectedIndex(0);
            TabbedPaneCadastro.setSelectedIndex(0);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TfDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescricaoKeyPressed
        valida.limitemaximo(evt, TfDescricao.getText(), 70);
    }//GEN-LAST:event_TfDescricaoKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddFornecedor;
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtCadFornecedor;
    private javax.swing.JButton BtCadTabela2;
    private javax.swing.JButton BtCadTipoProduto;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtDelFornecedor;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtIncluir;
    private javax.swing.JButton BtIncluirEspecific;
    private javax.swing.JButton BtPesqFornecedor;
    private javax.swing.JButton BtPesquisar;
    private javax.swing.JButton BtRemoverEspecific;
    private javax.swing.JComboBox CbPesquisa;
    private javax.swing.JComboBox CbTipoProduto;
    private javax.swing.JPanel PnBotoes;
    private javax.swing.JPanel PnCadastro;
    private javax.swing.JPanel PnConsulta;
    private javax.swing.JPanel PnFornecedor;
    private javax.swing.JPanel PnProduto;
    private javax.swing.JTabbedPane TabbedPaneCadastro;
    private javax.swing.JTabbedPane TabbedPaneProduto;
    private javax.swing.JTable TbCarcteristica;
    private javax.swing.JTable TbConsulta;
    private javax.swing.JTable TbEspecificacao;
    private javax.swing.JTable TbFornecedoresProd;
    private javax.swing.JTable TbProduto;
    private javax.swing.JTextField TfCodFornecedor;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfDescricao;
    private javax.swing.JTextField TfFornecedor;
    private javax.swing.JTextField TfPesquisa;
    private JNumberField.JNumberField TfQtEstoqueMin;
    private JNumberField.JNumberField TfValor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

    public boolean camposobrigatoriospreenchidos() {
        if (TfDescricao.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Digite a descricao do produto!", "Campos obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            TfDescricao.grabFocus();
            return false;
        }
        if (TfValor.getValue() == BigDecimal.valueOf(0)) {
            JOptionPane.showMessageDialog(null, "Digite o valor do produto!", "Campos obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            TfValor.grabFocus();
            return false;
        }
        if (TfQtEstoqueMin.getValue() == BigDecimal.valueOf(0)) {
            JOptionPane.showMessageDialog(null, "Digite a quantidade minima do estoque do produto!", "Campos obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            TfQtEstoqueMin.grabFocus();
            return false;
        }
        if (CbTipoProduto.getSelectedItem() == null) {
            JOptionPane.showMessageDialog(null, "Selecione ou insira o tipo de produto deste produto!", "Campo obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            CbTipoProduto.grabFocus();
            return false;
        }
        if (TbProduto.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione ou insira as caracteristicas do produto!", "Campo obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (TbProduto.getRowCount() != TbCarcteristica.getRowCount()) {
            JOptionPane.showMessageDialog(null, "Selecione ou insira todas as caracteristicas do produto!", "Campo obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        if (TbFornecedoresProd.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Selecione ou insira o fornecedor do produto!", "Campo obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            return false;
        }
        return true;
    }

    public void enviardados() {
        especproduto.getProduto().setDescricao(TfDescricao.getText());
        especproduto.getProduto().setValor(Float.parseFloat(TfValor.getValue().toString()));
        especproduto.getProduto().setEstoquemin(Float.parseFloat(TfQtEstoqueMin.getValue().toString()));
        especproduto.getTipoproduto().setTipoproduto(CbTipoProduto.getSelectedItem().toString());
        especproduto.getTipoproduto().setCodigo(especproduto.getTipoproduto().retornacodigo());
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }
}
