package br.com.lojadafatima.InterfacesProduto;

import br.com.lojadafatima.InterfacesPessoa.InterfaceFornecedor;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFornecedor;
import br.com.lojadafatima.Produto.ClasseEspecificacaoProduto;
import br.com.lojadafatima.Produto.ClasseFornecedoresProduto;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JDialog;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceProduto extends javax.swing.JDialog {

    private java.awt.Frame primeiratela;
    Preenche preenche = new Preenche();
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    LimpaCamposTela limpar = new LimpaCamposTela();
    ClasseEspecificacaoProduto especproduto = new ClasseEspecificacaoProduto();
    ClasseFornecedoresProduto forneproduto = new ClasseFornecedoresProduto();
    private ClasseTelasUsuario telausuario = new ClasseTelasUsuario();
    MensagensUsuario msg = new MensagensUsuario();

    /**
     * Creates new form InterfaceProduto
     */
    public InterfaceProduto(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelausuario(usuario);
        analisausuario();
        valida.validacamposCancelar(PnProduto, PnBotoes);
        valida.validacamposCancelar(PnFornecedor, PnBotoes);
        TfCodFornecedor.setDocument(new PermiteApenasNumeros());
        preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());

        int[] tam = new int[2];
        tam[0] = 50;
        tam[1] = 200;
        preenche.FormataJtable(TbCarcteristica, tam);
        preenche.FormataJtable(TbEspecificacao, tam);
        tam[0] = 10;
        tam[1] = 400;
        preenche.FormataJtable(TbFornecedoresProd, tam);

        int[] tam2 = new int[4];
        tam2[0] = 20;
        tam2[1] = 100;
        tam2[2] = 20;
        tam2[3] = 50;
        preenche.FormataJtable(TbProduto, tam2);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        TbFornecedoresProd.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TbCarcteristica.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TbEspecificacao.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TbProduto.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TbConsulta.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TfDescricao.setDocument(new NaoPermiteAspasSimples());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        TabbedPaneProduto = new javax.swing.JTabbedPane();
        PnCadastro = new javax.swing.JPanel();
        PnBotoes = new javax.swing.JPanel();
        BtGravar = new javax.swing.JButton();
        BtAlterar = new javax.swing.JButton();
        BtIncluir = new javax.swing.JButton();
        BtExcluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        TabbedPaneCadastro = new javax.swing.JTabbedPane();
        PnProduto = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        TfDescricao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BtCadTipoProduto = new javax.swing.JButton();
        CbTipoProduto = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbCarcteristica = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbEspecificacao = new javax.swing.JTable();
        BtCadTabela2 = new javax.swing.JButton();
        BtIncluirEspecific = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbProduto = new javax.swing.JTable();
        BtRemoverEspecific = new javax.swing.JButton();
        TfPercentLucro = new JNumberField.JNumberField(2);
        ;
        TfQtEstoqueMin = new JNumberField.JNumberField(2);
        ;
        PnFornecedor = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        TfCodFornecedor = new javax.swing.JTextField();
        BtAddFornecedor = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        TbFornecedoresProd = new javax.swing.JTable();
        BtPesqFornecedor = new javax.swing.JButton();
        TfFornecedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtCadFornecedor = new javax.swing.JButton();
        BtDelFornecedor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        LbNotificacao = new javax.swing.JLabel();
        PnConsulta = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        CbPesquisa = new javax.swing.JComboBox();
        TfPesquisa = new javax.swing.JTextField();
        BtPesquisar = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        TbConsulta = new javax.swing.JTable();
        RbPesqProduto = new javax.swing.JRadioButton();
        RbPesqServico = new javax.swing.JRadioButton();

        jMenuItem1.setText("Carregar dados");
        jMenuItem1.setComponentPopupMenu(jPopupMenu1);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Produtos - Software Loja da Fátima");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PnCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/salvar.png"))); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.setName("Gravar"); // NOI18N
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/editar.png"))); // NOI18N
        BtAlterar.setText("Alterar Dados");
        BtAlterar.setName("Alterar"); // NOI18N
        BtAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAlterarActionPerformed(evt);
            }
        });

        BtIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluir.setText("Novo");
        BtIncluir.setName("Incluir"); // NOI18N
        BtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirActionPerformed(evt);
            }
        });

        BtExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/lixeira.png"))); // NOI18N
        BtExcluir.setText("Excluir");
        BtExcluir.setName("Excluir"); // NOI18N
        BtExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtExcluirActionPerformed(evt);
            }
        });

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/cancelar.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.setName("Cancelar"); // NOI18N
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotoesLayout = new javax.swing.GroupLayout(PnBotoes);
        PnBotoes.setLayout(PnBotoesLayout);
        PnBotoesLayout.setHorizontalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotoesLayout.createSequentialGroup()
                .addComponent(BtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );
        PnBotoesLayout.setVerticalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(BtAlterar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PnCadastro.add(PnBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 507, 608, -1));

        PnProduto.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        PnProduto.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodigo.setEditable(false);
        PnProduto.add(TfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 80, -1));

        TfDescricao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfDescricaoKeyPressed(evt);
            }
        });
        PnProduto.add(TfDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 31, 335, -1));

        jLabel5.setText("Descrição do Produto/Serviço*");
        PnProduto.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 11, -1, -1));

        jLabel9.setText("Percentual de lucro");
        PnProduto.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 11, -1, -1));

        jLabel12.setText("Quantidade Mínima de Estoque*");
        PnProduto.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 57, -1, -1));

        BtCadTipoProduto.setText("Cadastrar Tipo");
        BtCadTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadTipoProdutoActionPerformed(evt);
            }
        });
        PnProduto.add(BtCadTipoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 77, 139, -1));

        CbTipoProduto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CbTipoProdutoMouseClicked(evt);
            }
        });
        CbTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbTipoProdutoActionPerformed(evt);
            }
        });
        PnProduto.add(CbTipoProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 256, -1));

        jLabel2.setText("Tipo de Produto/Serviço*");
        PnProduto.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        jLabel6.setText("Características do tipo do produto:");
        PnProduto.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        TbCarcteristica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Característica"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbCarcteristica.getTableHeader().setReorderingAllowed(false);
        TbCarcteristica.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbCarcteristicaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbCarcteristica);
        if (TbCarcteristica.getColumnModel().getColumnCount() > 0) {
            TbCarcteristica.getColumnModel().getColumn(0).setResizable(false);
            TbCarcteristica.getColumnModel().getColumn(1).setResizable(false);
        }

        PnProduto.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 123, 256, 124));

        jLabel7.setText("Especificação:");
        PnProduto.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 106, -1, -1));

        TbEspecificacao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Especificação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbEspecificacao.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TbEspecificacao);
        if (TbEspecificacao.getColumnModel().getColumnCount() > 0) {
            TbEspecificacao.getColumnModel().getColumn(0).setResizable(false);
            TbEspecificacao.getColumnModel().getColumn(1).setResizable(false);
        }

        PnProduto.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 123, 316, 124));

        BtCadTabela2.setText("Cadastrar Característica");
        BtCadTabela2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadTabelaActionPerformed(evt);
            }
        });
        PnProduto.add(BtCadTabela2, new org.netbeans.lib.awtextra.AbsoluteConstraints(428, 254, -1, -1));

        BtIncluirEspecific.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirEspecific.setText("Incluir");
        BtIncluirEspecific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirEspecificActionPerformed(evt);
            }
        });
        PnProduto.add(BtIncluirEspecific, new org.netbeans.lib.awtextra.AbsoluteConstraints(272, 253, 116, -1));

        jLabel8.setText("Produto*:");
        PnProduto.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 284, -1, -1));

        TbProduto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cód. Característica", "Característica", "Cód. Especificação", "Especificação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbProduto.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(TbProduto);

        PnProduto.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 304, 578, 106));

        BtRemoverEspecific.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverEspecific.setText("Remover");
        BtRemoverEspecific.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverEspecificActionPerformed(evt);
            }
        });
        PnProduto.add(BtRemoverEspecific, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 421, -1, -1));

        TfPercentLucro.setEditable(false);
        TfPercentLucro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfPercentLucroKeyTyped(evt);
            }
        });
        PnProduto.add(TfPercentLucro, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 31, 92, -1));

        TfQtEstoqueMin.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQtEstoqueMinKeyTyped(evt);
            }
        });
        PnProduto.add(TfQtEstoqueMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(441, 78, 92, -1));

        TabbedPaneCadastro.addTab("Produto", PnProduto);

        PnFornecedor.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Código do Fornecedor*");
        PnFornecedor.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodFornecedor.setName("CD_FORNECEDOR"); // NOI18N
        TfCodFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TfCodFornecedorActionPerformed(evt);
            }
        });
        TfCodFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TfCodFornecedorKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodFornecedorKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfCodFornecedorKeyTyped(evt);
            }
        });
        PnFornecedor.add(TfCodFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 80, -1));

        BtAddFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtAddFornecedor.setText("Adicionar Fornecedor");
        BtAddFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAddFornecedorActionPerformed(evt);
            }
        });
        PnFornecedor.add(BtAddFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 68, -1, -1));

        TbFornecedoresProd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Fornecedor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbFornecedoresProd.getTableHeader().setReorderingAllowed(false);
        jScrollPane5.setViewportView(TbFornecedoresProd);

        PnFornecedor.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 102, 583, 344));

        BtPesqFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFornecedorActionPerformed(evt);
            }
        });
        PnFornecedor.add(BtPesqFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 32, -1, -1));

        TfFornecedor.setEditable(false);
        TfFornecedor.setName("NM_FANTASIA"); // NOI18N
        PnFornecedor.add(TfFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 33, 297, -1));

        jLabel4.setText("Fornecedor");
        PnFornecedor.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 11, -1, -1));

        BtCadFornecedor.setText("Cadastrar Fornecedor");
        BtCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadFornecedorActionPerformed(evt);
            }
        });
        PnFornecedor.add(BtCadFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(454, 32, -1, -1));

        BtDelFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtDelFornecedor.setText("Remover Fornecedor");
        BtDelFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtDelFornecedorActionPerformed(evt);
            }
        });
        PnFornecedor.add(BtDelFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 68, -1, -1));

        TabbedPaneCadastro.addTab("Fornecedor", PnFornecedor);

        PnCadastro.add(TabbedPaneCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 608, -1));

        LbNotificacao.setText(" ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(LbNotificacao)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacao)
        );

        PnCadastro.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 551, 608, -1));

        TabbedPaneProduto.addTab("Cadastro", PnCadastro);

        PnConsulta.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setText("Consulta por:");
        PnConsulta.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        CbPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Código", "Descrição", "Código do Tipo de Produto/Serviço" }));
        CbPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPesquisaActionPerformed(evt);
            }
        });
        PnConsulta.add(CbPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 150, -1));

        TfPesquisa.setEnabled(false);
        PnConsulta.add(TfPesquisa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 33, 344, -1));

        BtPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesquisar.setText("Pesquisar");
        BtPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisarActionPerformed(evt);
            }
        });
        PnConsulta.add(BtPesquisar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 31, 100, -1));

        TbConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição", "Tipo de Produto/Serviço", "Estoque mínimo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbConsulta.setComponentPopupMenu(jPopupMenu1);
        TbConsulta.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TbConsulta);

        PnConsulta.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, 610, 459));

        buttonGroup1.add(RbPesqProduto);
        RbPesqProduto.setSelected(true);
        RbPesqProduto.setText("Produto");
        PnConsulta.add(RbPesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        buttonGroup1.add(RbPesqServico);
        RbPesqServico.setText("Serviço");
        PnConsulta.add(RbPesqServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 81, -1, -1));

        TabbedPaneProduto.addTab("Consulta", PnConsulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneProduto)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TabbedPaneProduto)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadTipoProdutoActionPerformed
        final InterfaceTipoProduto tela = new InterfaceTipoProduto(getPrimeiratela(), true, getTelausuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());
            }
        });
    }//GEN-LAST:event_BtCadTipoProdutoActionPerformed

    private void BtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirActionPerformed
        limpar.Limpar(PnProduto);
        limpar.Limpar(PnFornecedor);
        limpar.Limpar(TbFornecedoresProd);
        limpar.Limpar(TbCarcteristica);
        limpar.Limpar(TbEspecificacao);
        limpar.Limpar(TbProduto);
        preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());
        valida.validacamposCadastrar(PnProduto, PnBotoes);
        valida.validacamposCadastrar(PnFornecedor, PnBotoes);
        msg.StatusNovo(LbNotificacao, "Insira os dados do novo Produto");
    }//GEN-LAST:event_BtIncluirActionPerformed

    private void BtAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAlterarActionPerformed
        if (!TfCodigo.getText().equals("")) {
            valida.validacamposCadastrar(PnProduto, PnBotoes);
            valida.validacamposCadastrar(PnFornecedor, PnBotoes);
            CbTipoProduto.setEnabled(false);
            BtCadTipoProduto.setEnabled(false);
            msg.StatusEditar(LbNotificacao, "Editando informações do Produto...");
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto na aba \"Consulta\" e carregue os dados para que a operação seja realizada!", "Selecione um produto", JOptionPane.YES_NO_OPTION);
            TabbedPaneProduto.setSelectedIndex(1);
            CbPesquisa.grabFocus();
        }
    }//GEN-LAST:event_BtAlterarActionPerformed

    private void BtCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadFornecedorActionPerformed
        final InterfaceFornecedor tela = new InterfaceFornecedor(getPrimeiratela(), true, getTelausuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadFornecedorActionPerformed

    private void TbCarcteristicaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbCarcteristicaMouseClicked
        int index = TbCarcteristica.getSelectedRow();
        if (index > -1) {
            especproduto.getTipoproduto().getTabela().setCodigo(Integer.parseInt(TbCarcteristica.getValueAt(index, 0).toString()));
            preenche.PreencherJtable(TbEspecificacao, especproduto.getTipoproduto().getTabela().buscarvalorestabela());
        }
    }//GEN-LAST:event_TbCarcteristicaMouseClicked

    private void BtIncluirEspecificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirEspecificActionPerformed
        if (TbEspecificacao.getSelectedRow() > -1) {
            DefaultTableModel tabela = (DefaultTableModel) TbProduto.getModel();
            int linhas = tabela.getRowCount();
            int index = TbCarcteristica.getSelectedRow();
            int posexclui = -1;
            boolean substitui = false;
            for (int i = 0; i < linhas; i++) {
                if (tabela.getValueAt(i, 0).toString().equals(TbCarcteristica.getValueAt(index, 0).toString())) {
                    substitui = true;
                    posexclui = i;
                }
            }
            int indexespecific = TbEspecificacao.getSelectedRow();
            if (substitui) {
                tabela.setNumRows(linhas + 1);
                tabela.setValueAt(TbEspecificacao.getValueAt(indexespecific, 0).toString(), linhas, 2);
                tabela.setValueAt(TbEspecificacao.getValueAt(indexespecific, 1).toString(), linhas, 3);
                tabela.setValueAt(TbCarcteristica.getValueAt(index, 0).toString(), linhas, 0);
                tabela.setValueAt(TbCarcteristica.getValueAt(index, 1).toString(), linhas, 1);
                tabela.removeRow(posexclui);
            } else {
                tabela.setNumRows(linhas + 1);
                tabela.setValueAt(TbEspecificacao.getValueAt(indexespecific, 0).toString(), linhas, 2);
                tabela.setValueAt(TbEspecificacao.getValueAt(indexespecific, 1).toString(), linhas, 3);
                tabela.setValueAt(TbCarcteristica.getValueAt(index, 0).toString(), linhas, 0);
                tabela.setValueAt(TbCarcteristica.getValueAt(index, 1).toString(), linhas, 1);
            }
            msg.Adicionado(LbNotificacao, "Especificação adicionada");
        }
    }//GEN-LAST:event_BtIncluirEspecificActionPerformed

    private void CbTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbTipoProdutoActionPerformed
        limpar.Limpar(TbEspecificacao);
        limpar.Limpar(TbProduto);
        if (CbTipoProduto.getSelectedItem() == null) {
            preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());
        }
        especproduto.getTipoproduto().setTipoproduto(CbTipoProduto.getSelectedItem().toString());
        especproduto.getTipoproduto().setCodigo(especproduto.getTipoproduto().retornacodigo());
        TfPercentLucro.setValue(BigDecimal.valueOf(especproduto.getTipoproduto().retornapercentuallucro()));
        if (especproduto.getTipoproduto().retornatiposervico().equals("S")){
            TfQtEstoqueMin.setEnabled(false);
        }else{
            TfQtEstoqueMin.setEditable(true);
        }
        preenche.PreencherJtable(TbCarcteristica, especproduto.getTipoproduto().buscartabelasdotipoproduto());
    }//GEN-LAST:event_CbTipoProdutoActionPerformed

    private void CbTipoProdutoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CbTipoProdutoMouseClicked

    }//GEN-LAST:event_CbTipoProdutoMouseClicked

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (camposobrigatoriospreenchidos()) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja gravar os dados deste produto?", "Deseja gravar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                enviardados();
                if (TfCodigo.getText().equals("")) {
                    if(especproduto.getProduto().incluir()) msg.Sucesso(LbNotificacao, "Dados do Produto gravados com sucesso!");
                    if(!especproduto.getTipoproduto().isServico()){
                        for (int i = 0; i < TbProduto.getRowCount(); i++) {
                            especproduto.getTipoproduto().getTabela().setCodigo(Integer.parseInt(TbProduto.getValueAt(i, 0).toString()));
                            especproduto.getTipoproduto().getTabela().getValor().setCodigo(Integer.parseInt(TbProduto.getValueAt(i, 2).toString()));
                            especproduto.incluirespecific();
                        }
                    }
                    forneproduto.getProduto().setCodigo(especproduto.getProduto().getCodigo());
                    for (int i = 0; i < TbFornecedoresProd.getRowCount(); i++) {
                        forneproduto.getFornecedor().setCodigo(Integer.parseInt(TbFornecedoresProd.getValueAt(i, 0).toString()));
                        forneproduto.incluirfornecedor();
                    }
                    JOptionPane.showMessageDialog(null, "Código: " + especproduto.getProduto().getCodigo() + "\n"
                            + "Produto: " + especproduto.getProduto().getDescricao().toUpperCase(), "Código do produto", JOptionPane.INFORMATION_MESSAGE);
                } else {
                    especproduto.getProduto().setCodigo(Integer.parseInt(TfCodigo.getText()));
                    forneproduto.getProduto().setCodigo(Integer.parseInt(TfCodigo.getText()));
                    if(especproduto.getProduto().alterar()) msg.Sucesso(LbNotificacao, "Dados do Produto alterados com sucesso!");
                    if(!especproduto.getTipoproduto().isServico()){
                        for (int i = 0; i < TbProduto.getRowCount(); i++) {
                            especproduto.getTipoproduto().getTabela().setCodigo(Integer.parseInt(TbProduto.getValueAt(i, 0).toString()));
                            especproduto.getTipoproduto().getTabela().getValor().setCodigo(Integer.parseInt(TbProduto.getValueAt(i, 2).toString()));
                            especproduto.alterarespecific();
                        }
                    }
                    forneproduto.excluirfornecedores();
                    for (int i = 0; i < TbFornecedoresProd.getRowCount(); i++) {
                        forneproduto.getFornecedor().setCodigo(Integer.parseInt(TbFornecedoresProd.getValueAt(i, 0).toString()));
                        forneproduto.incluirfornecedor();
                    }
                    BtPesquisarActionPerformed(evt);
                }
                limpar.Limpar(PnProduto);
                limpar.Limpar(PnFornecedor);
                limpar.Limpar(TbFornecedoresProd);
                limpar.Limpar(TbCarcteristica);
                limpar.Limpar(TbEspecificacao);
                limpar.Limpar(TbProduto);
                valida.validacamposCancelar(PnProduto, PnBotoes);
                valida.validacamposCancelar(PnFornecedor, PnBotoes);
            }
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtCadTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadTabelaActionPerformed
        final InterfaceTabelas tela = new InterfaceTabelas(getPrimeiratela(), true, getTelausuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                TbCarcteristicaMouseClicked(null);
            }
        });
    }//GEN-LAST:event_BtCadTabelaActionPerformed

    private void BtRemoverEspecificActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverEspecificActionPerformed
        if (TbProduto.getSelectedRow() > -1) {
            DefaultTableModel tabela = (DefaultTableModel) TbProduto.getModel();
            tabela.removeRow(TbProduto.getSelectedRow());
            msg.Removido(LbNotificacao, "Especificacao removida");
        }
    }//GEN-LAST:event_BtRemoverEspecificActionPerformed

    private void BtAddFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAddFornecedorActionPerformed
        if (!TfCodFornecedor.getText().equals("") && !TfFornecedor.getText().equals("")) {
            boolean inclui = true;
            for (int i = 0; i < TbFornecedoresProd.getRowCount(); i++) {
                if ((TfCodFornecedor.getText().equals(TbFornecedoresProd.getValueAt(i, 0).toString())) && (TfFornecedor.getText().equals(TbFornecedoresProd.getValueAt(i, 1).toString()))) {
                    inclui = false;
                }
            }
            if (inclui) {
                DefaultTableModel tabela = (DefaultTableModel) TbFornecedoresProd.getModel();
                int linha = tabela.getRowCount();
                tabela.setRowCount(linha + 1);
                tabela.setValueAt(TfCodFornecedor.getText(), linha, 0);
                tabela.setValueAt(TfFornecedor.getText(), linha, 1);
                TfCodFornecedor.setText("");
                TfFornecedor.setText("");
            }
            msg.Adicionado(LbNotificacao, "Fornecedor adicionado");
        }
    }//GEN-LAST:event_BtAddFornecedorActionPerformed

    private void TfCodFornecedorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFornecedorKeyTyped

    }//GEN-LAST:event_TfCodFornecedorKeyTyped

    private void TfCodFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TfCodFornecedorActionPerformed

    }//GEN-LAST:event_TfCodFornecedorActionPerformed

    private void TfCodFornecedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFornecedorKeyPressed

    }//GEN-LAST:event_TfCodFornecedorKeyPressed

    private void TfCodFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFornecedorKeyReleased
        if (!TfCodFornecedor.getText().equals("")) {
            forneproduto.getFornecedor().setCodigo(Integer.parseInt(TfCodFornecedor.getText()));
            if (forneproduto.getFornecedor().efornecedorativo()) {
                forneproduto.getFornecedor().getPessoajur().getPessoa().setCodigo(forneproduto.getFornecedor().retornacodigopessoafornecedor());
                TfFornecedor.setText(forneproduto.getFornecedor().getPessoajur().retornanomeporCodigo());
            } else {
                TfFornecedor.setText("");
            }
        } else {
            TfFornecedor.setText("");
        }
    }//GEN-LAST:event_TfCodFornecedorKeyReleased

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar esta operação?\n"
                + "(Caso queira, TODOS os dados serão limpos da tela)", "Deseja cancelar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpar.Limpar(PnProduto);
            limpar.Limpar(PnFornecedor);
            limpar.Limpar(TbFornecedoresProd);
            limpar.Limpar(TbCarcteristica);
            limpar.Limpar(TbEspecificacao);
            limpar.Limpar(TbProduto);
            valida.validacamposCancelar(PnProduto, PnBotoes);
            valida.validacamposCancelar(PnFornecedor, PnBotoes);
            msg.Limpar(LbNotificacao);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void BtExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtExcluirActionPerformed
        if (!TfCodigo.getText().equals("")) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja EXCLUIR os dados deste produto?", "Deseja excluir?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                especproduto.getProduto().setCodigo(Integer.parseInt(TfCodigo.getText()));
                if(especproduto.getProduto().excluir()) msg.StatusExcluido(LbNotificacao, "Produto excluído com sucesso!");
                BtPesquisarActionPerformed(evt);
                limpar.Limpar(PnProduto);
                limpar.Limpar(PnFornecedor);
                limpar.Limpar(TbFornecedoresProd);
                limpar.Limpar(TbCarcteristica);
                limpar.Limpar(TbEspecificacao);
                limpar.Limpar(TbProduto);
                valida.validacamposCancelar(PnProduto, PnBotoes);
                valida.validacamposCancelar(PnFornecedor, PnBotoes);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione um produto na aba \"Consulta\" e carregue os dados para que a operação seja realizada!", "Selecione um produto", JOptionPane.YES_NO_OPTION);
            TabbedPaneProduto.setSelectedIndex(1);
            CbPesquisa.grabFocus();
        }
    }//GEN-LAST:event_BtExcluirActionPerformed

    private void BtDelFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtDelFornecedorActionPerformed
        if (TbFornecedoresProd.getSelectedRow() > -1) {
            DefaultTableModel tabela = (DefaultTableModel) TbFornecedoresProd.getModel();
            tabela.removeRow(TbFornecedoresProd.getSelectedRow());
            msg.Removido(LbNotificacao, "Fornecedor removido");
        }
    }//GEN-LAST:event_BtDelFornecedorActionPerformed

    private void BtPesqFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFornecedorActionPerformed
        final ConsulSimplesFornecedor tela = new ConsulSimplesFornecedor(getPrimeiratela(), true, forneproduto.getFornecedor());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (forneproduto.getFornecedor().getCodigo() != 0) {
                    TfCodFornecedor.setText("" + forneproduto.getFornecedor().getCodigo());
                    TfCodFornecedorKeyReleased(null);
                } else {
                    TfCodFornecedor.setText("");
                    TfFornecedor.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqFornecedorActionPerformed

    private void CbPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPesquisaActionPerformed
        switch (CbPesquisa.getSelectedIndex()) {
            case 0: {
                TfPesquisa.setEnabled(false);
                TfPesquisa.setDocument(TfDescricao.getDocument());
                break;
            }
            case 1: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(new PermiteApenasNumeros());
                break;
            }
            case 2: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(TfDescricao.getDocument());
                break;
            }
            case 3: {
                TfPesquisa.setEnabled(true);
                TfPesquisa.setDocument(new PermiteApenasNumeros());
                break;
            }
        }
    }//GEN-LAST:event_CbPesquisaActionPerformed

    private void BtPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisarActionPerformed
        int[] tam = new int[4];
        tam[0] = 15;
        tam[1] = 100;
        tam[2] = 70;
        tam[3] = 20;
        preenche.FormataJtable(TbConsulta, tam);
        switch (CbPesquisa.getSelectedIndex()) {
            case 0: {
                preenche.PreencherJtable(TbConsulta, especproduto.getProduto().consultageral(RbPesqProduto.isSelected()));
                break;
            }
            case 1: {
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o código do produto que deseja consultar!", "Digite a informação", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    especproduto.getProduto().setCodigo(Integer.parseInt(TfPesquisa.getText()));
                    preenche.PreencherJtable(TbConsulta, especproduto.getProduto().consultacodigo(RbPesqProduto.isSelected()));
                }
                break;
            }
            case 2: {
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite a descrição do produto que deseja consultar!", "Digite a informação", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    especproduto.getProduto().setDescricao(TfPesquisa.getText());
                    preenche.PreencherJtable(TbConsulta, especproduto.getProduto().consultadescricao(RbPesqProduto.isSelected()));
                }
                break;
            }
            case 3: {
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o código do tipo de produto que deseja consultar!", "Digite a informação", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    especproduto.getTipoproduto().setCodigo(Integer.parseInt(TfPesquisa.getText()));
                    preenche.PreencherJtable(TbConsulta, especproduto.consultatipoproduto(RbPesqProduto.isSelected()));
                }
                break;
            }
        }
    }//GEN-LAST:event_BtPesquisarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if (TbConsulta.getSelectedRow() > -1) {
            especproduto.getProduto().setCodigo(Integer.parseInt(TbConsulta.getValueAt(TbConsulta.getSelectedRow(), 0).toString()));
            especproduto.retornaproduto();
            TfCodigo.setText("" + especproduto.getProduto().getCodigo());
            TfDescricao.setText(especproduto.getProduto().getDescricao());
            TfQtEstoqueMin.setValue(BigDecimal.valueOf(especproduto.getProduto().getEstoquemin()));
            if (CbTipoProduto.getSelectedItem() == null) {
                preenche.PreencheJComboBox(CbTipoProduto, especproduto.getTipoproduto().buscartipoprodutocombobox());
            }
            CbTipoProduto.setSelectedItem(especproduto.getTipoproduto().getTipoproduto());
            CbTipoProdutoActionPerformed(evt);

            limpar.Limpar(TbProduto);
            limpar.Limpar(TbFornecedoresProd);

            ResultSet rs = especproduto.retornacaracproduto();
            DefaultTableModel tabela = (DefaultTableModel) TbProduto.getModel();
            try {
                for (int i = 0; rs.next(); i++) {
                    especproduto.getTipoproduto().getTabela().setCodigo(rs.getInt(1));
                    especproduto.getTipoproduto().getTabela().getValor().setCodigoTabela(rs.getInt(1));
                    especproduto.getTipoproduto().getTabela().getValor().setCodigo(rs.getInt(2));
                    tabela.setRowCount(i + 1);
                    tabela.setValueAt(especproduto.getTipoproduto().getTabela().getCodigo(), i, 0);
                    tabela.setValueAt(especproduto.getTipoproduto().getTabela().retornatabela(), i, 1);
                    tabela.setValueAt(especproduto.getTipoproduto().getTabela().getValor().getCodigo(), i, 2);
                    tabela.setValueAt(especproduto.getTipoproduto().getTabela().getValor().retornavalor(), i, 3);
                }
            } catch (SQLException ex) {
            }

            forneproduto.getProduto().setCodigo(Integer.parseInt(TbConsulta.getValueAt(TbConsulta.getSelectedRow(), 0).toString()));
            rs = forneproduto.retornafornecedoresproduto();
            try {
                for (int i = 0; rs.next(); i++) {
                    TfCodFornecedor.setText(rs.getString(1));
                    TfCodFornecedorKeyReleased(null);
                    BtAddFornecedorActionPerformed(evt);
                }
            } catch (SQLException ex) {

            }

            TfCodFornecedor.setText("");
            TfFornecedor.setText("");

            valida.validacamposCancelar(PnProduto, PnBotoes);
            valida.validacamposCancelar(PnFornecedor, PnBotoes);
            TabbedPaneProduto.setSelectedIndex(0);
            TabbedPaneCadastro.setSelectedIndex(0);
            msg.StatusBusca(LbNotificacao, "Os dados do Produto estão carregados na tela...");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void TfDescricaoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescricaoKeyPressed
        valida.limitemaximo(evt, TfDescricao.getText(), 70);
    }//GEN-LAST:event_TfDescricaoKeyPressed

    private void TfPercentLucroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfPercentLucroKeyTyped
        
    }//GEN-LAST:event_TfPercentLucroKeyTyped

    private void TfQtEstoqueMinKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQtEstoqueMinKeyTyped
        valida.limitemaximo(evt, TfQtEstoqueMin.getText(), 10);
    }//GEN-LAST:event_TfQtEstoqueMinKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(PnBotoes.isVisible() && BtGravar.isEnabled()){
            if(JOptionPane.showConfirmDialog(null, "Você esta prestes a fechar esta janela.\nAo fechar esta janela tudo que você digitou será esquecido!", "Tem certeza que deseja fechar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
                dispose();
            }
        }else{
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAddFornecedor;
    private javax.swing.JButton BtAlterar;
    private javax.swing.JButton BtCadFornecedor;
    private javax.swing.JButton BtCadTabela2;
    private javax.swing.JButton BtCadTipoProduto;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtDelFornecedor;
    private javax.swing.JButton BtExcluir;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtIncluir;
    private javax.swing.JButton BtIncluirEspecific;
    private javax.swing.JButton BtPesqFornecedor;
    private javax.swing.JButton BtPesquisar;
    private javax.swing.JButton BtRemoverEspecific;
    private javax.swing.JComboBox CbPesquisa;
    private javax.swing.JComboBox CbTipoProduto;
    private javax.swing.JLabel LbNotificacao;
    private javax.swing.JPanel PnBotoes;
    private javax.swing.JPanel PnCadastro;
    private javax.swing.JPanel PnConsulta;
    private javax.swing.JPanel PnFornecedor;
    private javax.swing.JPanel PnProduto;
    private javax.swing.JRadioButton RbPesqProduto;
    private javax.swing.JRadioButton RbPesqServico;
    private javax.swing.JTabbedPane TabbedPaneCadastro;
    private javax.swing.JTabbedPane TabbedPaneProduto;
    private javax.swing.JTable TbCarcteristica;
    private javax.swing.JTable TbConsulta;
    private javax.swing.JTable TbEspecificacao;
    private javax.swing.JTable TbFornecedoresProd;
    private javax.swing.JTable TbProduto;
    private javax.swing.JTextField TfCodFornecedor;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfDescricao;
    private javax.swing.JTextField TfFornecedor;
    private JNumberField.JNumberField TfPercentLucro;
    private javax.swing.JTextField TfPesquisa;
    private JNumberField.JNumberField TfQtEstoqueMin;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    // End of variables declaration//GEN-END:variables

    public void analisausuario(){
        getTelausuario().getTela().setCodigo(11);
        if(!getTelausuario().eadmintela()){
            PnBotoes.setVisible(false);
        }
        
        getTelausuario().getTela().setCodigo(2);
        if(!getTelausuario().eadmintela()){
            BtCadFornecedor.setVisible(false);
        }
        
        getTelausuario().getTela().setCodigo(12);
        if(!getTelausuario().eadmintela()){
            BtCadTipoProduto.setVisible(false);
        }
        
        getTelausuario().getTela().setCodigo(13);
        if(!getTelausuario().eadmintela()){
            BtCadTabela2.setVisible(false);
        }
    }
    
    public boolean camposobrigatoriospreenchidos() {
        if (TfDescricao.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite a descrição do produto!");
            TfDescricao.grabFocus();
            return false;
        }

        if (!especproduto.getTipoproduto().isServico() && TfQtEstoqueMin.getValue() == BigDecimal.valueOf(0)) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite a quantidade mínima do estoque do produto!");
            TfQtEstoqueMin.grabFocus();
            return false;
        }
        if (CbTipoProduto.getSelectedItem() == null) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Selecione ou insira o tipo de produto deste produto!");
            CbTipoProduto.grabFocus();
            return false;
        }
        if (!especproduto.getTipoproduto().isServico() && TbProduto.getRowCount() == 0) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Selecione ou insira as características do produto!");
            return false;
        }
        if (!especproduto.getTipoproduto().isServico() && TbProduto.getRowCount() != TbCarcteristica.getRowCount()) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Selecione ou insira todas as características do produto!");
            return false;
        }
        if (TbFornecedoresProd.getRowCount() == 0) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Selecione ou insira o fornecedor do produto!");
            return false;
        }
        return true;
    }

    public void enviardados() {
        especproduto.getProduto().setDescricao(TfDescricao.getText());
        especproduto.getProduto().setEstoquemin(Float.parseFloat(TfQtEstoqueMin.getValue().toString()));
        especproduto.getTipoproduto().setTipoproduto(CbTipoProduto.getSelectedItem().toString());
        especproduto.getTipoproduto().setCodigo(especproduto.getTipoproduto().retornacodigo());
        if (especproduto.getTipoproduto().isServico()){
            especproduto.getProduto().getTiposervico().setCodigo(especproduto.getTipoproduto().getCodigo());
        } else {
            especproduto.getProduto().getTiposervico().setCodigo(0);
        }
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelausuario() {
        return telausuario;
    }

    public void setTelausuario(ClasseTelasUsuario telausuario) {
        this.telausuario = telausuario;
    }
}
