package br.com.lojadafatima.InterfacesProduto;

import br.com.lojadafatima.ClassesFerramentas.ClasseDatas;
import br.com.lojadafatima.ClassesFerramentas.GeraCodigos;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseProdutosCompraVenda;
import br.com.lojadafatima.ConexaoBDpostgre.ConexaoPostgre;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesDetalhesOperacao;
import br.com.lojadafatima.Produto.ClasseMvtoEstoque;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceEstoque extends javax.swing.JDialog {

    private java.awt.Frame primeiratela;
    Preenche preenche = new Preenche();
    ClasseMvtoEstoque mvtoestoque = new ClasseMvtoEstoque();
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    ClasseDatas datas = new ClasseDatas();
    MaskFormatter data;

    public InterfaceEstoque(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(usuario);
        analisausuario();
        CbPesqProdutoActionPerformed(null);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        int[] tam = new int[5];
        tam[0] = 80;
        tam[1] = 200;
        tam[2] = 100;
        tam[3] = 100;
        tam[4] = 80;
        preenche.FormataJtable(TbProdutos, tam);
        preenche.FormataJtable(TbAjuste, tam);
        TbAjuste.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TbProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        PnPesqEstoque = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CbPesqProduto = new javax.swing.JComboBox();
        TfPesqProduto = new javax.swing.JTextField();
        BtPesqProduto = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbProdutos = new javax.swing.JTable();
        PnAjusteEstoque = new javax.swing.JPanel();
        TfQuantEstoqueSistema = new JNumberField.JNumberField(2);
        ;
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TfQuantEstoqueFisico = new JNumberField.JNumberField(2);
        ;
        TfDsProduto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtAjustar = new javax.swing.JButton();
        BtIniciar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbAjuste = new javax.swing.JTable();
        BtEncerrar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        CbPesqProdutoHist = new javax.swing.JComboBox();
        TfPesqProdutoHist = new javax.swing.JTextField();
        BtPesqProdutoHist = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TbProdutosHist = new javax.swing.JTable();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel localizar");
        }
        TfDtInicial = new JFormattedTextField(data);
        jLabel6 = new javax.swing.JLabel();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel localizar");
        }
        TfDtFinal = new JFormattedTextField(data);
        BtSelecionar = new javax.swing.JButton();
        CbPeriodo = new javax.swing.JCheckBox();
        CbEntradas = new javax.swing.JCheckBox();
        CbSaidas = new javax.swing.JCheckBox();
        CbAjustes = new javax.swing.JCheckBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        TbHistorico = new javax.swing.JTable();
        BtImprimirHistorico = new javax.swing.JButton();

        jMenuItem1.setText("Detalhes...");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Estoque de Produtos - Software Loja da Fátima");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PnPesqEstoque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Pesquisar por:");
        PnPesqEstoque.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        CbPesqProduto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos os Produtos", "Código do Produto", "Descrição do Produto", "Produtos Abaixo da Quantidade Mínima", "Produtos Disponíveis" }));
        CbPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPesqProdutoActionPerformed(evt);
            }
        });
        PnPesqEstoque.add(CbPesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 33, 240, -1));
        PnPesqEstoque.add(TfPesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 33, 313, -1));

        BtPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqProduto.setText("Pesquisar");
        BtPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqProdutoActionPerformed(evt);
            }
        });
        PnPesqEstoque.add(BtPesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 31, -1, -1));

        TbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Produto", "Descrição do Produto", "Quant. Mínima de Estoque", "Quant. Estoque Atual", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbProdutos);

        PnPesqEstoque.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, 767, 393));

        jTabbedPane1.addTab("Pesquisa de Estoque", PnPesqEstoque);

        PnAjusteEstoque.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfQuantEstoqueSistema.setEditable(false);
        PnAjusteEstoque.add(TfQuantEstoqueSistema, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 432, 170, -1));

        jLabel2.setText("Quant. em Estoque no Sistema");
        PnAjusteEstoque.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, -1, -1));

        jLabel3.setText("Quant. em Estoque Fisicamente");
        PnAjusteEstoque.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 410, -1, -1));

        TfQuantEstoqueFisico.setEditable(false);
        PnAjusteEstoque.add(TfQuantEstoqueFisico, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 432, 180, -1));

        TfDsProduto.setEditable(false);
        PnAjusteEstoque.add(TfDsProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 384, 494, -1));

        jLabel4.setText("Descrição do Produto");
        PnAjusteEstoque.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 364, 767, -1));

        BtAjustar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sucesso2.png"))); // NOI18N
        BtAjustar.setText("Ajustar");
        BtAjustar.setEnabled(false);
        BtAjustar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAjustarActionPerformed(evt);
            }
        });
        PnAjusteEstoque.add(BtAjustar, new org.netbeans.lib.awtextra.AbsoluteConstraints(393, 430, 111, -1));

        BtIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIniciar.setText("Iniciar");
        BtIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIniciarActionPerformed(evt);
            }
        });
        PnAjusteEstoque.add(BtIniciar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 102, -1));

        TbAjuste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Descrição do Produto", "Quant. Mínima de Estoque", "Quant. Estoque Atual", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbAjuste.getTableHeader().setReorderingAllowed(false);
        TbAjuste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TbAjusteMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(TbAjuste);

        PnAjusteEstoque.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 42, 767, 315));

        BtEncerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sucesso2.png"))); // NOI18N
        BtEncerrar.setText("Encerrar");
        BtEncerrar.setEnabled(false);
        BtEncerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtEncerrarActionPerformed(evt);
            }
        });
        PnAjusteEstoque.add(BtEncerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(118, 11, 102, -1));

        jTabbedPane1.addTab("Ajuste de Estoque", PnAjusteEstoque);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CbPesqProdutoHist.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos os Produtos", "Código do Produto", "Descrição do Produto", "Produtos Abaixo da Quantidade Mínima", "Produtos Disponíveis" }));
        CbPesqProdutoHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPesqProdutoHistActionPerformed(evt);
            }
        });
        jPanel1.add(CbPesqProdutoHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 13, 240, -1));
        jPanel1.add(TfPesqProdutoHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(256, 13, 313, -1));

        BtPesqProdutoHist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqProdutoHist.setText("Pesquisar");
        BtPesqProdutoHist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqProdutoHistActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqProdutoHist, new org.netbeans.lib.awtextra.AbsoluteConstraints(575, 11, -1, -1));

        TbProdutosHist.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código do Produto", "Descrição do Produto", "Quant. Mínima de Estoque", "Quant. Estoque Atual", "Situação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbProdutosHist.getTableHeader().setReorderingAllowed(false);
        TbProdutosHist.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                TbProdutosHistMouseReleased(evt);
            }
        });
        jScrollPane3.setViewportView(TbProdutosHist);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 767, 176));

        TfDtInicial.setEditable(false);
        TfDtInicial.setName("DT_NASC"); // NOI18N
        TfDtInicial.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfDtInicialFocusLost(evt);
            }
        });
        jPanel1.add(TfDtInicial, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 226, 116, -1));

        jLabel6.setText("a");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(197, 229, -1, -1));

        TfDtFinal.setEditable(false);
        TfDtFinal.setName("DT_NASC"); // NOI18N
        TfDtFinal.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfDtFinalFocusLost(evt);
            }
        });
        jPanel1.add(TfDtFinal, new org.netbeans.lib.awtextra.AbsoluteConstraints(207, 226, 116, -1));

        BtSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sucesso2.png"))); // NOI18N
        BtSelecionar.setText("Selecionar");
        BtSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSelecionarActionPerformed(evt);
            }
        });
        jPanel1.add(BtSelecionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(329, 224, 110, -1));

        CbPeriodo.setText("Período:");
        CbPeriodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPeriodoActionPerformed(evt);
            }
        });
        jPanel1.add(CbPeriodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 225, -1, -1));

        CbEntradas.setSelected(true);
        CbEntradas.setText("Entradas");
        jPanel1.add(CbEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 251, -1, -1));

        CbSaidas.setSelected(true);
        CbSaidas.setText("Saídas");
        jPanel1.add(CbSaidas, new org.netbeans.lib.awtextra.AbsoluteConstraints(81, 251, -1, -1));

        CbAjustes.setSelected(true);
        CbAjustes.setText("Ajustes");
        jPanel1.add(CbAjustes, new org.netbeans.lib.awtextra.AbsoluteConstraints(142, 251, -1, -1));

        TbHistorico.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nro. Mvto.", "Nro. Operação", "Cód. Operação", "Data Mvto.", "Qtde. Antes", "Qtde. Mvto.", "Qtde. Depois", "Tipo Mvto."
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbHistorico.setComponentPopupMenu(jPopupMenu1);
        TbHistorico.getTableHeader().setReorderingAllowed(false);
        jScrollPane4.setViewportView(TbHistorico);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 281, 767, 174));

        BtImprimirHistorico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/imprimir.png"))); // NOI18N
        BtImprimirHistorico.setText("Imprimir Histórico");
        BtImprimirHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtImprimirHistoricoActionPerformed(evt);
            }
        });
        jPanel1.add(BtImprimirHistorico, new org.netbeans.lib.awtextra.AbsoluteConstraints(445, 224, 134, -1));

        jTabbedPane1.addTab("Histórico de Movimentação de Estoque", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CbPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPesqProdutoActionPerformed
        switch (CbPesqProduto.getSelectedIndex()) {
            case 0: {
                TfPesqProduto.setEnabled(false);
                break;
            }
            case 1: {
                TfPesqProduto.setEnabled(true);
                TfPesqProduto.setDocument(new PermiteApenasNumeros());
                break;
            }
            case 2: {
                TfPesqProduto.setEnabled(true);
                TfPesqProduto.setDocument(new NaoPermiteAspasSimples());
                break;
            }
            case 3: {
                TfPesqProduto.setEnabled(false);
                break;
            }
            case 4: {
                TfPesqProduto.setEnabled(false);
                break;
            }
        }
    }//GEN-LAST:event_CbPesqProdutoActionPerformed

    private void BtPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqProdutoActionPerformed
        switch (CbPesqProduto.getSelectedIndex()) {
            case 0: {
                preenche.PreencherJtable(TbProdutos, mvtoestoque.consultaestoquetodososprodutos());
                break;
            }
            case 1: {
                if (!TfPesqProduto.getText().equals("")) {
                    mvtoestoque.getProduto().setCodigo(Integer.parseInt(TfPesqProduto.getText()));
                    preenche.PreencherJtable(TbProdutos, mvtoestoque.consultaestoqueporcodigo());
                } else {
                    JOptionPane.showMessageDialog(null, "Digite o código do produto para consulta!", "Digite o código", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            }
            case 2: {
                if (!TfPesqProduto.getText().equals("")) {
                    mvtoestoque.getProduto().setDescricao(TfPesqProduto.getText().toUpperCase());
                    preenche.PreencherJtable(TbProdutos, mvtoestoque.consultaestoquepordescricao());
                } else {
                    JOptionPane.showMessageDialog(null, "Digite a descrição do produto para consulta!", "Digite a descrição", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            }
            case 3: {
                preenche.PreencherJtable(TbProdutos, mvtoestoque.consultaestoquebaixo());
                break;
            }
            case 4: {
                preenche.PreencherJtable(TbProdutos, mvtoestoque.consultaestoquedisponivel());
                break;
            }
        }
    }//GEN-LAST:event_BtPesqProdutoActionPerformed

    private void BtIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIniciarActionPerformed
        mvtoestoque.getCompravenda().getFuncionario().setCodigo(0);
        final InterfacePerguntaFuncionarioAjusteEstoque tela = new InterfacePerguntaFuncionarioAjusteEstoque(getPrimeiratela(), true, mvtoestoque.getCompravenda().getFuncionario(), getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (mvtoestoque.getCompravenda().getFuncionario().getCodigo() != 0) {
                    mvtoestoque.getCompravenda().getCondicao().setCodigo(0);
                    mvtoestoque.getCompravenda().getOperacao().setCodigo(3);
                    ClasseDatas datas = new ClasseDatas();
                    mvtoestoque.getCompravenda().setData(datas.retornadataehora());
                    mvtoestoque.getCompravenda().setCodigopessoa(0);
                    GeraCodigos geracodigos = new GeraCodigos();
                    mvtoestoque.getCompravenda().setDescricao("AJUSTE DE ESTOQUE NRO. " + geracodigos.gerasequencia("COMPRA_VENDA", "CD_COMPRA_VENDA", "CD_OPERACAO", 3) + ", REALIZADO DIA: " + mvtoestoque.getCompravenda().getData());
                    mvtoestoque.getCompravenda().incluir();
                    preenche.PreencherJtable(TbAjuste, mvtoestoque.consultaestoquetodososprodutos());
                    BtEncerrar.setEnabled(true);
                    BtIniciar.setEnabled(false);
                    TfQuantEstoqueFisico.setEditable(true);
                    jTabbedPane1.setEnabledAt(0, false);
                    jTabbedPane1.setEnabledAt(2, false);
                }
            }
        });
    }//GEN-LAST:event_BtIniciarActionPerformed

    private void TbAjusteMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbAjusteMouseReleased
        if (TbAjuste.getSelectedRow() > -1) {
            TfDsProduto.setText(TbAjuste.getValueAt(TbAjuste.getSelectedRow(), 1).toString());
            TfQuantEstoqueSistema.setText(TbAjuste.getValueAt(TbAjuste.getSelectedRow(), 3).toString());
            BtAjustar.setEnabled(true);
        }
    }//GEN-LAST:event_TbAjusteMouseReleased

    private void BtEncerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtEncerrarActionPerformed
        preenche.PreencherJtable(TbAjuste, mvtoestoque.consultaestoquetodososprodutos());
        BtEncerrar.setEnabled(false);
        BtIniciar.setEnabled(true);
        TfQuantEstoqueFisico.setEditable(false);
        jTabbedPane1.setEnabledAt(0, true);
        jTabbedPane1.setEnabledAt(2, true);
        TfDsProduto.setText("");
        TfQuantEstoqueSistema.setValue(BigDecimal.ZERO);
        TfQuantEstoqueFisico.setValue(BigDecimal.ZERO);
        LimpaCamposTela limpa = new LimpaCamposTela();
        limpa.Limpar(TbAjuste);
        if (TbProdutos.getRowCount() > 0) {
            BtPesqProdutoActionPerformed(evt);
        }
    }//GEN-LAST:event_BtEncerrarActionPerformed

    private void BtAjustarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAjustarActionPerformed
        if (TfQuantEstoqueFisico.getValue() != BigDecimal.valueOf(0)) {
            mvtoestoque.setTpmvto("A");
            mvtoestoque.getProduto().setCodigo(Integer.parseInt(TbAjuste.getValueAt(TbAjuste.getSelectedRow(), 0).toString()));
            mvtoestoque.setQtatual(Float.parseFloat(TfQuantEstoqueFisico.getValue().toString()));
            mvtoestoque.setDtmvto(mvtoestoque.getCompravenda().getData());
            mvtoestoque.setQtmvto(0);
            mvtoestoque.incluirmvto();
            ClasseProdutosCompraVenda prodcompravenda = new ClasseProdutosCompraVenda();
            prodcompravenda.setCompravenda(mvtoestoque.getCompravenda());
            prodcompravenda.getForneproduto().setProduto(mvtoestoque.getProduto());
            prodcompravenda.setQuantidade(Float.parseFloat(TfQuantEstoqueFisico.getValue().toString()));
            prodcompravenda.setPromocao("");
            prodcompravenda.incluirprodutocompravenda();
            BtAjustar.setEnabled(false);
            preenche.PreencherJtable(TbAjuste, mvtoestoque.consultaestoquetodososprodutos());
            TfDsProduto.setText("");
            TfQuantEstoqueFisico.setText("");
            TfQuantEstoqueSistema.setText("");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente zerar o estoque deste produto?", "Zerar estoque", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                mvtoestoque.setTpmvto("A");
                mvtoestoque.getProduto().setCodigo(Integer.parseInt(TbAjuste.getValueAt(TbAjuste.getSelectedRow(), 0).toString()));
                mvtoestoque.setQtatual(Float.parseFloat(TfQuantEstoqueFisico.getValue().toString()));
                mvtoestoque.setDtmvto(mvtoestoque.getCompravenda().getData());
                mvtoestoque.setQtmvto(0);
                mvtoestoque.incluirmvto();
                ClasseProdutosCompraVenda prodcompravenda = new ClasseProdutosCompraVenda();
                prodcompravenda.setCompravenda(mvtoestoque.getCompravenda());
                prodcompravenda.getForneproduto().setProduto(mvtoestoque.getProduto());
                prodcompravenda.setQuantidade(Float.parseFloat(TfQuantEstoqueFisico.getValue().toString()));
                prodcompravenda.setPromocao("");
                prodcompravenda.incluirprodutocompravenda();
                BtAjustar.setEnabled(false);
                preenche.PreencherJtable(TbAjuste, mvtoestoque.consultaestoquetodososprodutos());
                TfDsProduto.setText("");
                TfQuantEstoqueFisico.setText("");
                TfQuantEstoqueSistema.setText("");
            }
        }
    }//GEN-LAST:event_BtAjustarActionPerformed

    private void CbPesqProdutoHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPesqProdutoHistActionPerformed
        switch (CbPesqProdutoHist.getSelectedIndex()) {
            case 0: {
                TfPesqProdutoHist.setEnabled(false);
                break;
            }
            case 1: {
                TfPesqProdutoHist.setEnabled(true);
                TfPesqProdutoHist.setDocument(new PermiteApenasNumeros());
                break;
            }
            case 2: {
                TfPesqProdutoHist.setEnabled(true);
                TfPesqProdutoHist.setDocument(new NaoPermiteAspasSimples());
                break;
            }
            case 3: {
                TfPesqProdutoHist.setEnabled(false);
                break;
            }
            case 4: {
                TfPesqProdutoHist.setEnabled(false);
                break;
            }
        }
    }//GEN-LAST:event_CbPesqProdutoHistActionPerformed

    private void BtPesqProdutoHistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqProdutoHistActionPerformed
        switch (CbPesqProdutoHist.getSelectedIndex()) {
            case 0: {
                preenche.PreencherJtable(TbProdutosHist, mvtoestoque.consultaestoquetodososprodutos());
                break;
            }
            case 1: {
                if (!TfPesqProdutoHist.getText().equals("")) {
                    mvtoestoque.getProduto().setCodigo(Integer.parseInt(TfPesqProdutoHist.getText()));
                    preenche.PreencherJtable(TbProdutosHist, mvtoestoque.consultaestoqueporcodigo());
                } else {
                    JOptionPane.showMessageDialog(null, "Digite o código do produto para consulta!", "Digite o código", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            }
            case 2: {
                if (!TfPesqProdutoHist.getText().equals("")) {
                    mvtoestoque.getProduto().setDescricao(TfPesqProdutoHist.getText().toUpperCase());
                    preenche.PreencherJtable(TbProdutosHist, mvtoestoque.consultaestoquepordescricao());
                } else {
                    JOptionPane.showMessageDialog(null, "Digite a descrição do produto para consulta!", "Digite a descrição", JOptionPane.INFORMATION_MESSAGE);
                }
                break;
            }
            case 3: {
                preenche.PreencherJtable(TbProdutosHist, mvtoestoque.consultaestoquebaixo());
                break;
            }
            case 4: {
                preenche.PreencherJtable(TbProdutosHist, mvtoestoque.consultaestoquedisponivel());
                break;
            }
        }
    }//GEN-LAST:event_BtPesqProdutoHistActionPerformed

    private void TfDtInicialFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfDtInicialFocusLost
        if (valida.CampoTotalmentePreenchido(TfDtInicial.getText())) {
            if (datas.validadatas(TfDtInicial.getText())) {

            } else {
                TfDtInicial.setValue(null);
            }
        }
    }//GEN-LAST:event_TfDtInicialFocusLost

    private void TfDtFinalFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfDtFinalFocusLost
        if (valida.CampoTotalmentePreenchido(TfDtFinal.getText())) {
            if (datas.validadatas(TfDtFinal.getText())) {

            } else {
                TfDtFinal.setValue(null);
            }
        }
    }//GEN-LAST:event_TfDtFinalFocusLost

    private void BtSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSelecionarActionPerformed
        int linha = TbProdutosHist.getSelectedRow();
        if(linha > -1){
            String data_ini, data_fim, pesq1, pesq2, pesq3;
            if(CbPeriodo.isSelected() && (!TfDtInicial.getText().equals("  /  /    ") && !TfDtFinal.getText().equals("  /  /    ")) && datascorretas() && datas.validadatas(TfDtInicial.getText()) && datas.validadatas(TfDtFinal.getText())){
                data_ini = TfDtInicial.getText();
                data_fim = TfDtFinal.getText();
            }else{
                data_ini = "";
                data_fim = "";
                if(CbPeriodo.isSelected()) JOptionPane.showMessageDialog(null, "Digite as datas corretamente!", "Datas incorretas", JOptionPane.INFORMATION_MESSAGE);
            }
            if(CbEntradas.isSelected()) pesq1 = "E";
            else pesq1 = "";
            
            if(CbSaidas.isSelected()) pesq2 = "S";
            else pesq2 = "";
            
            if(CbAjustes.isSelected()) pesq3 = "A";
            else pesq3 = "";
            
            mvtoestoque.getProduto().setCodigo(Integer.parseInt(TbProdutosHist.getValueAt(linha, 0).toString()));
            preenche.PreencherJtable(TbHistorico, mvtoestoque.consultahistoricomvto(pesq1, pesq2, pesq3, data_ini, data_fim));
        }
    }//GEN-LAST:event_BtSelecionarActionPerformed

    private void TbProdutosHistMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbProdutosHistMouseReleased
        BtSelecionarActionPerformed(null);
    }//GEN-LAST:event_TbProdutosHistMouseReleased

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        int linha = TbHistorico.getSelectedRow();
        if(linha > -1){
            ClasseProdutosCompraVenda prodcompravenda = new ClasseProdutosCompraVenda();
            prodcompravenda.getCompravenda().setCodigo(Integer.parseInt(TbHistorico.getValueAt(linha, 1).toString()));
            prodcompravenda.getCompravenda().getOperacao().setCodigo(Integer.parseInt(TbHistorico.getValueAt(linha, 2).toString()));
            prodcompravenda.getCompravenda().getOperacao().setDescricao(prodcompravenda.getCompravenda().getOperacao().retornadescricaooperacao());
            
            final ConsulSimplesDetalhesOperacao tela = new ConsulSimplesDetalhesOperacao(getPrimeiratela(), true, prodcompravenda);
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {

                }
            });
        
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void CbPeriodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPeriodoActionPerformed
        TfDtInicial.setEditable(CbPeriodo.isSelected());
        TfDtFinal.setEditable(CbPeriodo.isSelected());
        if(TfDtInicial.isEditable()) TfDtInicial.grabFocus();
    }//GEN-LAST:event_CbPeriodoActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if(BtEncerrar.isEnabled()){
            JOptionPane.showMessageDialog(null, "Encerre o ajuste de estoque antes de fechar a janela!", "Ajuste de estoque não encerrado", JOptionPane.INFORMATION_MESSAGE);
        }else{
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void BtImprimirHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtImprimirHistoricoActionPerformed
        if(TbHistorico.getRowCount() > 0){
            HashMap par = new HashMap();
            String relatorio, desc = "";
            
            if(CbPeriodo.isSelected()){
                relatorio = "relatorios\\relatoriohistoricomvtocaixacomdata.jasper";
                SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
                try {
                    par.put("DT_INICIAL", format.parse(TfDtInicial.getText()));
                    par.put("DT_FINAL", format.parse(TfDtFinal.getText()));
                } catch (ParseException ex) {
                
                }
                if(TfDtInicial.getText().equals(TfDtFinal.getText())){
                    par.put("DS_RELATORIO", "Movimentações ocorridas no dia "+TfDtInicial.getText());
                }else{
                    par.put("DS_RELATORIO", "Movimentaçções ocorridas entre os dias "+TfDtInicial.getText() +" e "+TfDtFinal.getText());
                }
            }else{
                relatorio = "relatorios\\relatoriohistoricomvtocaixasemdata.jasper";
            }
            
            if(CbEntradas.isSelected()) par.put("TP1", "E");
            else par.put("TP1", "");
            
            if(CbSaidas.isSelected()) par.put("TP2", "S");
            else par.put("TP2", "");
            
            if(CbAjustes.isSelected()) par.put("TP3", "A");
            else par.put("TP3", "");
            par.put("CD_PRODUTO", Integer.parseInt(TbProdutosHist.getValueAt(TbProdutosHist.getSelectedRow(), 0).toString()));
            ConexaoPostgre conexao = new ConexaoPostgre();
            JDialog dialog = new JDialog(new javax.swing.JFrame(), "Visualização - Software Loja da Fátima", true);
                        dialog.setSize(1000, 700);
            dialog.setLocationRelativeTo(null);
            try {
                JasperPrint print = JasperFillManager.fillReport(relatorio, par, conexao.conecta());
                            
                JasperViewer viewer = new JasperViewer(print, true);
                dialog.getContentPane().add(viewer.getContentPane());
                dialog.setVisible(true);
            } catch (Exception ex) {
                System.out.println(ex);
            }
        }
    }//GEN-LAST:event_BtImprimirHistoricoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAjustar;
    private javax.swing.JButton BtEncerrar;
    private javax.swing.JButton BtImprimirHistorico;
    private javax.swing.JButton BtIniciar;
    private javax.swing.JButton BtPesqProduto;
    private javax.swing.JButton BtPesqProdutoHist;
    private javax.swing.JButton BtSelecionar;
    private javax.swing.JCheckBox CbAjustes;
    private javax.swing.JCheckBox CbEntradas;
    private javax.swing.JCheckBox CbPeriodo;
    private javax.swing.JComboBox CbPesqProduto;
    private javax.swing.JComboBox CbPesqProdutoHist;
    private javax.swing.JCheckBox CbSaidas;
    private javax.swing.JPanel PnAjusteEstoque;
    private javax.swing.JPanel PnPesqEstoque;
    private javax.swing.JTable TbAjuste;
    private javax.swing.JTable TbHistorico;
    private javax.swing.JTable TbProdutos;
    private javax.swing.JTable TbProdutosHist;
    private javax.swing.JTextField TfDsProduto;
    private javax.swing.JFormattedTextField TfDtFinal;
    private javax.swing.JFormattedTextField TfDtInicial;
    private javax.swing.JTextField TfPesqProduto;
    private javax.swing.JTextField TfPesqProdutoHist;
    private JNumberField.JNumberField TfQuantEstoqueFisico;
    private JNumberField.JNumberField TfQuantEstoqueSistema;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario(){
        getTelasusuario().getTela().setCodigo(14);
        if(!getTelasusuario().eadmintela()){
            BtIniciar.setVisible(false);
            BtEncerrar.setVisible(false);
            BtAjustar.setVisible(false);
        }
    }
    
    public boolean datascorretas() {
        SimpleDateFormat format = new SimpleDateFormat("dd/MM/yyyy");
        format.setLenient(false);
        Date date1 = null, date2 = null;
        String data1, data2;
        data1 = TfDtInicial.getText();
        data2 = TfDtFinal.getText();           
        try {
            date1 = format.parse(data1);
            date2 = format.parse(data2);
        } catch (ParseException ex) {
            return false;
        }
        if(date1.equals(date2)) return false;
        if (date1.after(date2)) {
            return false;
        }
        
        return true;
    }
    
    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
