package br.com.lojadafatima.InterfacesOperacoes;

import br.com.lojadafatima.ClassesFerramentas.ClasseDatas;
import br.com.lojadafatima.ClassesFerramentas.GeraCodigos;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseProdutosCompraVenda;
import br.com.lojadafatima.ConexaoBDpostgre.ConexaoPostgre;
import br.com.lojadafatima.Financeiro.ClasseParcelas;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesCondicaoPgto;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFornecedor;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFuncionario;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesProduto;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceCondicaoPagto;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFornecedor;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFuncionario;
import br.com.lojadafatima.InterfacesProduto.InterfaceProduto;
import br.com.lojadafatima.Produto.ClasseMvtoEstoque;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import java.math.BigDecimal;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceCompra extends javax.swing.JDialog {

    MaskFormatter valor;
    MaskFormatter data;
    private java.awt.Frame primeiratela;
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    ClasseProdutosCompraVenda prodcompravenda = new ClasseProdutosCompraVenda();
    ClasseDatas datas = new ClasseDatas();
    LimpaCamposTela limpar = new LimpaCamposTela();
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    MensagensUsuario msg = new MensagensUsuario();

    /**
     * Creates new form InterfaceCompra
     */
    public InterfaceCompra(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(usuario);
        analisausuario();
        TfCodCondicaoPgto.setDocument(new PermiteApenasNumeros());
        TfCodFornecedor.setDocument(new PermiteApenasNumeros());
        TfCodProduto.setDocument(new PermiteApenasNumeros());
        TfCodFuncionario.setDocument(new PermiteApenasNumeros());
        TfCodServico.setDocument(new PermiteApenasNumeros());
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        TfDescNotaCompra.setDocument(new PermiteApenasNumeros());
        valida.validacamposCancelar(jPanel1, PnBotoes);
        valida.validacamposCancelar(jPanel3, PnBotoes);
        valida.validacamposCancelar(jPanel4, PnBotoes);
        TbCompra.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel montar mascara no campo de Data");
        }
        TfData = new JFormattedTextField(data);
        jLabel3 = new javax.swing.JLabel();
        TfCodFuncionario = new javax.swing.JTextField();
        BtPesqFuncionario = new javax.swing.JButton();
        TfFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtCadFuncionario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TfCodFornecedor = new javax.swing.JTextField();
        BtPesqFornecedor = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TfFornecedor = new javax.swing.JTextField();
        BtCadFornecedor = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TfCodCondicaoPgto = new javax.swing.JTextField();
        BtPesqFormaPgto = new javax.swing.JButton();
        TfCondicaoPgto = new javax.swing.JTextField();
        BtCadCondicaoPgto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        PnBotoes = new javax.swing.JPanel();
        BtGravar = new javax.swing.JButton();
        BtIncluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        TfDescNotaCompra = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LbNotificacao = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        TfCodProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtPesqProduto = new javax.swing.JButton();
        TfProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtCadProduto = new javax.swing.JButton();
        TfQuantidade = new JNumberField.JNumberField(2);
        ;
        jLabel11 = new javax.swing.JLabel();
        TfValorUnitario = new JNumberField.JNumberField();
        jLabel12 = new javax.swing.JLabel();
        TfDesconto = new JNumberField.JNumberField(2);
        jLabel15 = new javax.swing.JLabel();
        TfValorProduto = new JNumberField.JNumberField();
        jLabel14 = new javax.swing.JLabel();
        CbPromocao = new javax.swing.JCheckBox();
        BtIncluirProdutoCompra = new javax.swing.JButton();
        BtRemoverProdutoCompra = new javax.swing.JButton();
        TfValorTotalCompra = new JNumberField.JNumberField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbCompra = new javax.swing.JTable();
        jLabel25 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TfCodServico = new javax.swing.JTextField();
        BtPesqServico = new javax.swing.JButton();
        TfServico = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        BtCadServico = new javax.swing.JButton();
        TfQuantidadeServ = new JNumberField.JNumberField(2);
        ;
        jLabel20 = new javax.swing.JLabel();
        CbPromocaoServ = new javax.swing.JCheckBox();
        BtIncluirServicoCompra = new javax.swing.JButton();
        BtRemoverServicoCompra = new javax.swing.JButton();
        TfValorUnitarioServ = new JNumberField.JNumberField();
        jLabel21 = new javax.swing.JLabel();
        TfDescontoServ = new JNumberField.JNumberField(2);
        jLabel22 = new javax.swing.JLabel();
        TfValorProdutoServ = new JNumberField.JNumberField();
        jLabel23 = new javax.swing.JLabel();
        TfValorTotalCompraServ = new JNumberField.JNumberField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbCompraServ = new javax.swing.JTable();
        jLabel26 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Compra - Software Loja da Fátima");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodigo.setEditable(false);
        jPanel1.add(TfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 81, -1));

        jLabel2.setText("Data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(102, 11, -1, -1));

        TfData.setEditable(false);
        jPanel1.add(TfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 31, 111, -1));

        jLabel3.setText("Cód. Funcionário");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        TfCodFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodFuncionarioFocusLost(evt);
            }
        });
        TfCodFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodFuncionarioKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 115, -1));

        BtPesqFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 77, -1, -1));

        TfFuncionario.setEditable(false);
        jPanel1.add(TfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 78, 268, -1));

        jLabel4.setText("Funcionário");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 57, -1, -1));

        BtCadFuncionario.setText("Cadastrar Funcionário");
        BtCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 77, 199, -1));

        jLabel5.setText("Cód. Fornecedor");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, -1));

        TfCodFornecedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodFornecedorFocusLost(evt);
            }
        });
        TfCodFornecedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodFornecedorKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 115, -1));

        BtPesqFornecedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 128, -1, -1));

        jLabel6.setText("Fornecedor");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 108, -1, -1));

        TfFornecedor.setEditable(false);
        jPanel1.add(TfFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 129, 268, -1));

        BtCadFornecedor.setText("Cadastrar Fornecedor");
        BtCadFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadFornecedorActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadFornecedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 128, 199, -1));

        jLabel7.setText("Cód. Condicao de Pagamento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        TfCodCondicaoPgto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodCondicaoPgtoFocusLost(evt);
            }
        });
        TfCodCondicaoPgto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodCondicaoPgtoKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 115, -1));

        BtPesqFormaPgto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqFormaPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFormaPgtoActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqFormaPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 179, -1, -1));

        TfCondicaoPgto.setEditable(false);
        jPanel1.add(TfCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 180, 268, -1));

        BtCadCondicaoPgto.setText("Cadastrar Condição de Pagamento");
        BtCadCondicaoPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadCondicaoPgtoActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 179, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, 649, 10));

        BtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/salvar.png"))); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.setName("Gravar"); // NOI18N
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/carrinho.png"))); // NOI18N
        BtIncluir.setText("Nova Compra");
        BtIncluir.setName("Incluir"); // NOI18N
        BtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirActionPerformed(evt);
            }
        });

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/cancelar.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.setName("Cancelar"); // NOI18N
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotoesLayout = new javax.swing.GroupLayout(PnBotoes);
        PnBotoes.setLayout(PnBotoesLayout);
        PnBotoesLayout.setHorizontalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotoesLayout.createSequentialGroup()
                .addComponent(BtIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnBotoesLayout.setVerticalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(BtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(PnBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 557, 649, -1));

        jLabel18.setText("Código da Nota do Fornecedor");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 11, -1, -1));

        TfDescNotaCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescNotaCompraKeyTyped(evt);
            }
        });
        jPanel1.add(TfDescNotaCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 31, 437, -1));

        jLabel13.setText("Condição de Pagamento");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 159, -1, -1));

        LbNotificacao.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LbNotificacao)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacao)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 601, 649, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodProdutoKeyReleased(evt);
            }
        });
        jPanel3.add(TfCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 116, -1));

        jLabel9.setText("Cód. Produto");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        BtPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(BtPesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 31, -1, -1));

        TfProduto.setEditable(false);
        jPanel3.add(TfProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 32, 273, -1));

        jLabel10.setText("Produto");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 11, -1, -1));

        BtCadProduto.setText("Cadastrar Produto");
        BtCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(BtCadProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 31, 167, -1));

        TfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyTyped(evt);
            }
        });
        jPanel3.add(TfQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 91, -1));

        jLabel11.setText("Quantidade");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        TfValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfValorUnitarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfValorUnitarioKeyTyped(evt);
            }
        });
        jPanel3.add(TfValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 82, 92, -1));

        jLabel12.setText("Valor Unitário");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(121, 62, -1, -1));

        TfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfDescontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescontoKeyTyped(evt);
            }
        });
        jPanel3.add(TfDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 82, 96, -1));

        jLabel15.setText("Desconto");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(231, 62, -1, -1));

        TfValorProduto.setEditable(false);
        jPanel3.add(TfValorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 82, 96, -1));

        jLabel14.setText("Valor Total do Produto");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(353, 62, -1, -1));

        CbPromocao.setText("Promoção");
        jPanel3.add(CbPromocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));

        BtIncluirProdutoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirProdutoCompra.setText("Incluir Produto na Compra");
        BtIncluirProdutoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirProdutoCompraActionPerformed(evt);
            }
        });
        jPanel3.add(BtIncluirProdutoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, -1, -1));

        BtRemoverProdutoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverProdutoCompra.setText("Remover Produto");
        BtRemoverProdutoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverProdutoCompraActionPerformed(evt);
            }
        });
        jPanel3.add(BtRemoverProdutoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 129, -1, -1));

        TfValorTotalCompra.setEditable(false);
        jPanel3.add(TfValorTotalCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 134, 106, -1));

        jLabel16.setText("Valor Total da Compra");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 114, -1, -1));

        TbCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Compra", "Cód. Produto", "Produto", "Quantidade", "Valor Unitário", "Desconto", "Valor Total do Produto na Venda", "Promoção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbCompra.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbCompra);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 624, 121));

        jLabel25.setText("%");
        jPanel3.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(331, 85, -1, -1));

        jTabbedPane1.addTab("Produtos", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Cód. Serviço");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodServicoKeyReleased(evt);
            }
        });
        jPanel4.add(TfCodServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 116, -1));

        BtPesqServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqServicoActionPerformed(evt);
            }
        });
        jPanel4.add(BtPesqServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 31, -1, -1));

        TfServico.setEditable(false);
        jPanel4.add(TfServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 32, 273, -1));

        jLabel19.setText("Serviço");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 11, -1, -1));

        BtCadServico.setText("Cadastrar Serviço");
        BtCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadServicoActionPerformed(evt);
            }
        });
        jPanel4.add(BtCadServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(467, 31, 167, -1));

        TfQuantidadeServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfQuantidadeServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeServKeyTyped(evt);
            }
        });
        jPanel4.add(TfQuantidadeServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 91, -1));

        jLabel20.setText("Quantidade");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        CbPromocaoServ.setText("Promoção");
        jPanel4.add(CbPromocaoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 104, -1, -1));

        BtIncluirServicoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirServicoCompra.setText("Incluir Serviço na Compra");
        BtIncluirServicoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirServicoCompraActionPerformed(evt);
            }
        });
        jPanel4.add(BtIncluirServicoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, -1, -1));

        BtRemoverServicoCompra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverServicoCompra.setText("Remover Serviço");
        BtRemoverServicoCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverServicoCompraActionPerformed(evt);
            }
        });
        jPanel4.add(BtRemoverServicoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(191, 129, -1, -1));

        TfValorUnitarioServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfValorUnitarioServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfValorUnitarioServKeyTyped(evt);
            }
        });
        jPanel4.add(TfValorUnitarioServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 82, 92, -1));

        jLabel21.setText("Valor Unitário");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(124, 62, -1, -1));

        TfDescontoServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfDescontoServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescontoServKeyTyped(evt);
            }
        });
        jPanel4.add(TfDescontoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 82, 96, -1));

        jLabel22.setText("Desconto");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(234, 62, -1, -1));

        TfValorProdutoServ.setEditable(false);
        jPanel4.add(TfValorProdutoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 82, 96, -1));

        jLabel23.setText("Valor Total do Serviço");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 62, -1, -1));

        TfValorTotalCompraServ.setEditable(false);
        jPanel4.add(TfValorTotalCompraServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 134, 106, -1));

        jLabel24.setText("Valor Total da Compra");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(528, 114, -1, -1));

        TbCompraServ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Compra", "Cód. Serviço", "Serviço", "Quantidade", "Valor Unitário", "Desconto", "Valor Total do Serviço", "Promoção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbCompraServ.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TbCompraServ);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 624, 121));

        jLabel26.setText("%");
        jPanel4.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 85, -1, -1));

        jTabbedPane1.addTab("Serviços", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadFuncionarioActionPerformed
        final InterfaceFuncionario tela = new InterfaceFuncionario(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadFuncionarioActionPerformed

    private void BtCadCondicaoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadCondicaoPgtoActionPerformed
        final InterfaceCondicaoPagto tela = new InterfaceCondicaoPagto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadCondicaoPgtoActionPerformed

    private void BtCadFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadFornecedorActionPerformed
        final InterfaceFornecedor tela = new InterfaceFornecedor(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadFornecedorActionPerformed

    private void TfCodCondicaoPgtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodCondicaoPgtoKeyReleased
        if (!TfCodCondicaoPgto.getText().equals("")) {
            prodcompravenda.getCompravenda().getCondicao().setCodigo(Integer.parseInt(TfCodCondicaoPgto.getText()));
            TfCondicaoPgto.setText(prodcompravenda.getCompravenda().getCondicao().retornadescricaocondicao());
        } else {
            TfCondicaoPgto.setText("");
        }
    }//GEN-LAST:event_TfCodCondicaoPgtoKeyReleased

    private void BtPesqFormaPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFormaPgtoActionPerformed
        final ConsulSimplesCondicaoPgto tela = new ConsulSimplesCondicaoPgto(getPrimeiratela(), true, prodcompravenda.getCompravenda().getCondicao());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getCondicao().getCodigo() == 0) {
                    TfCodCondicaoPgto.setText("");
                } else {
                    TfCodCondicaoPgto.setText("" + prodcompravenda.getCompravenda().getCondicao().getCodigo());
                }
                TfCodCondicaoPgtoKeyReleased(null);
            }
        });
    }//GEN-LAST:event_BtPesqFormaPgtoActionPerformed

    private void TfCodFornecedorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFornecedorKeyReleased
        if (!TfCodFornecedor.getText().equals("")) {
            limpar.Limpar(jPanel3);
            limpar.Limpar(jPanel4);
            limpar.Limpar(TbCompra);
            limpar.Limpar(TbCompraServ);
            prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodFornecedor.getText()));
            if (prodcompravenda.getForneproduto().getFornecedor().efornecedorativo()) {
                prodcompravenda.getForneproduto().getFornecedor().getPessoajur().getPessoa().setCodigo(prodcompravenda.getForneproduto().getFornecedor().retornacodigopessoafornecedor());
                TfFornecedor.setText(prodcompravenda.getForneproduto().getFornecedor().getPessoajur().retornanomeporCodigo());
            } else {
                TfFornecedor.setText("");
            }
        } else {
            TfFornecedor.setText("");
        }
    }//GEN-LAST:event_TfCodFornecedorKeyReleased

    private void BtPesqFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFornecedorActionPerformed
        final ConsulSimplesFornecedor tela = new ConsulSimplesFornecedor(getPrimeiratela(), true, prodcompravenda.getForneproduto().getFornecedor());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getFornecedor().getCodigo() != 0) {
                    TfCodFornecedor.setText("" + prodcompravenda.getForneproduto().getFornecedor().getCodigo());
                    TfCodFornecedorKeyReleased(null);
                } else {
                    TfCodFornecedor.setText("");
                    TfFornecedor.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqFornecedorActionPerformed

    private void TfCodFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFuncionarioKeyReleased
        if (!TfCodFuncionario.getText().equals("")) {
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
            if (prodcompravenda.getCompravenda().getFuncionario().efuncionarioativo()) {
                prodcompravenda.getCompravenda().getFuncionario().getPessoafis().getPessoa().setCodigo(prodcompravenda.getCompravenda().getFuncionario().retornacodigopessoafuncionario());
                TfFuncionario.setText(prodcompravenda.getCompravenda().getFuncionario().getPessoafis().retornanomeporCodigo());
            } else {
                TfFuncionario.setText("");
            }
        } else {
            TfFuncionario.setText("");
        }
    }//GEN-LAST:event_TfCodFuncionarioKeyReleased

    private void BtPesqFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFuncionarioActionPerformed
        final ConsulSimplesFuncionario tela = new ConsulSimplesFuncionario(getPrimeiratela(), true, prodcompravenda.getCompravenda().getFuncionario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getFuncionario().getCodigo() != 0) {
                    TfCodFuncionario.setText("" + prodcompravenda.getCompravenda().getFuncionario().getCodigo());
                    TfCodFuncionarioKeyReleased(null);
                } else {
                    TfCodFuncionario.setText("");
                    TfFuncionario.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqFuncionarioActionPerformed

    private void TfDescNotaCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescNotaCompraKeyTyped
        valida.limitemaximo(evt, TfDescNotaCompra.getText(), 50);
    }//GEN-LAST:event_TfDescNotaCompraKeyTyped

    private void TfCodProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodProdutoKeyReleased
        if (!TfCodProduto.getText().equals("")) {
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
            if (!TfCodFornecedor.getText().equals("")){
                if (prodcompravenda.getForneproduto().getProduto().eprodutoativo() && prodcompravenda.getForneproduto().produtodestefornecedor() && !prodcompravenda.getForneproduto().getProduto().eservico()) {
                    TfProduto.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                    TfValorUnitario.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto()));
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                    TfValorProduto.setValue(BigDecimal.valueOf(0));
                } else{
                    TfProduto.setText("");
                    TfValorUnitario.setValue(BigDecimal.valueOf(0));
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                    TfValorProduto.setValue(BigDecimal.valueOf(0));
                    if(!prodcompravenda.getForneproduto().produtodestefornecedor() && prodcompravenda.getForneproduto().getProduto().eprodutoativo() && !prodcompravenda.getForneproduto().getProduto().eservico()){
                        msg.CampoNaoPreenchido(LbNotificacao, "Este produto não pode ser comprado com este fornecedor");
                    }
                }
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Insira o Fornecedor da Compra para que o sistema faça a busca dos Produtos!");
                TfCodFornecedor.grabFocus();
            }
        } else {
            TfProduto.setText("");
            TfValorUnitario.setValue(BigDecimal.valueOf(0));
            TfQuantidade.setValue(BigDecimal.valueOf(0));
            TfValorProduto.setValue(BigDecimal.valueOf(0));
        }
    }//GEN-LAST:event_TfCodProdutoKeyReleased

    private void BtPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqProdutoActionPerformed
        final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto(), "P");
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodProduto.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodProdutoKeyReleased(null);
                } else {
                    TfCodProduto.setText("");
                    TfCodProdutoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqProdutoActionPerformed

    private void BtIncluirProdutoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirProdutoCompraActionPerformed
        boolean inclui = true;
        limpar.Limpar(TbCompraServ);
        TfQuantidadeKeyReleased(null);
        TfValorTotalCompraServ.setValue(BigDecimal.ZERO);
        if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
            if (TfValorProduto.getValue() != BigDecimal.valueOf(0)) {
                for (int i = 0; i < TbCompra.getRowCount(); i++) {
                    if (Integer.parseInt(TbCompra.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodProduto.getText())) {
                        inclui = false;
                        if (JOptionPane.showConfirmDialog(null, "Este produto já foi adicionado a esta compra!\n"
                                + "Deseja substituir a quantidade adquirida deste produto?", "Produto adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                            TbCompra.setValueAt(TfQuantidade.getText(), i, 3);
                            TbCompra.setValueAt(TfValorUnitario.getText(), i, 4);
                            TbCompra.setValueAt(TfDesconto.getText(), i, 5);
                            TbCompra.setValueAt(TfValorProduto.getText(), i, 6);
                            String promoc;
                            if (CbPromocao.isSelected()) promoc = "S";
                            else                       promoc = "N";
                            TbCompra.setValueAt(promoc, i, 7);
                        }
                    }
                }
                if (inclui) {
                    DefaultTableModel tabela = (DefaultTableModel) TbCompra.getModel();
                    int linha = tabela.getRowCount();
                    tabela.setNumRows(linha + 1);
                    tabela.setValueAt(TfCodigo.getText(), linha, 0);
                    tabela.setValueAt(TfCodProduto.getText(), linha, 1);
                    tabela.setValueAt(TfProduto.getText(), linha, 2);
                    tabela.setValueAt(TfQuantidade.getText(), linha, 3);
                    tabela.setValueAt(TfValorUnitario.getText(), linha, 4);
                    tabela.setValueAt(TfDesconto.getText(), linha, 5);
                    tabela.setValueAt(TfValorProduto.getText(), linha, 6);
                    String promoc;
                    if (CbPromocao.isSelected()) promoc = "S";
                    else                       promoc = "N";
                    tabela.setValueAt(promoc, linha, 7);
                }
                TfCodProduto.setText("");
                TfProduto.setText("");
                TfQuantidade.setValue(BigDecimal.valueOf(0));
                TfValorUnitario.setValue(BigDecimal.valueOf(0));
                TfValorProduto.setValue(BigDecimal.valueOf(0));
                TfDesconto.setValue(BigDecimal.valueOf(0));
                CbPromocao.setSelected(false);
                atualizavalortotal();
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do produto e a quantidade corretamente!");
            }
        } else {
            msg.CampoNaoPreenchido(LbNotificacao, "Informe o produto a ser adicionado nesta compra!");
            TfCodProduto.grabFocus();
        }
    }//GEN-LAST:event_BtIncluirProdutoCompraActionPerformed

    private void BtRemoverProdutoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverProdutoCompraActionPerformed
        int linha = TbCompra.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este produto da compra?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbCompra.getModel();
                tabela.removeRow(linha);
                atualizavalortotal();
            }
        }
    }//GEN-LAST:event_BtRemoverProdutoCompraActionPerformed

    private void BtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirActionPerformed
        TfData.setText(datas.retornadataatual());
        GeraCodigos geracodigos = new GeraCodigos();
        TfCodigo.setText("" + geracodigos.gerasequencia("COMPRA_VENDA", "CD_COMPRA_VENDA", "CD_OPERACAO", 1));
        valida.validacamposCadastrar(jPanel1, PnBotoes);
        valida.validacamposCadastrar(jPanel3, PnBotoes);
        valida.validacamposCadastrar(jPanel4, PnBotoes);
    }//GEN-LAST:event_BtIncluirActionPerformed

    private void BtCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadProdutoActionPerformed
        final InterfaceProduto tela = new InterfaceProduto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadProdutoActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (camposobrigatoriospreenchidos()) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Gravar esta compra e de que todas as informações estão corretas?", "Deseja gravar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                enviardados();
                prodcompravenda.getCompravenda().incluir();

                ClasseMvtoEstoque mvestoque = new ClasseMvtoEstoque();
                final ClasseParcelas parcelas = new ClasseParcelas();
                mvestoque.setCompravenda(prodcompravenda.getCompravenda());
                mvestoque.setDtmvto(datas.retornadataehora());
                mvestoque.setTpmvto("E");
                
                if (TbCompra.getRowCount() > 0){
                        for (int i = 0; i < TbCompra.getRowCount(); i++) {
                        prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbCompra.getValueAt(i, 1).toString()));
                        TfQuantidade.setText(TbCompra.getValueAt(i, 3).toString());
                        prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidade.getValue().toString()));
                        TfValorUnitario.setText(TbCompra.getValueAt(i, 4).toString());
                        prodcompravenda.setValorunit(Float.parseFloat(TfValorUnitario.getValue().toString()));
                        TfDesconto.setText(TbCompra.getValueAt(i, 5).toString());
                        prodcompravenda.setDesconto(Float.parseFloat(TfDesconto.getValue().toString()));
                        TfValorProduto.setText(TbCompra.getValueAt(i, 6).toString());
                        prodcompravenda.setValorprodut(Float.parseFloat(TfValorProduto.getValue().toString()));
                        prodcompravenda.setPromocao(TbCompra.getValueAt(i, 7).toString());
                        prodcompravenda.incluirprodutocompravenda();

                        mvestoque.getProduto().setCodigo(Integer.parseInt(TbCompra.getValueAt(i, 1).toString()));
                        if (!mvestoque.getProduto().eservico()){
                            TfQuantidade.setText(TbCompra.getValueAt(i, 3).toString());
                            mvestoque.setQtmvto(Float.parseFloat(TfQuantidade.getValue().toString()));
                            mvestoque.incluirmvto();
                        }
                    }
                    parcelas.getConta().setTotal(Float.parseFloat(TfValorTotalCompra.getValue().toString()));
                } else if (TbCompraServ.getRowCount() > 0){
                    for (int i = 0; i < TbCompraServ.getRowCount(); i++) {
                        prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbCompraServ.getValueAt(i, 1).toString()));
                        TfQuantidadeServ.setText(TbCompraServ.getValueAt(i, 3).toString());
                        prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidadeServ.getValue().toString()));
                        TfValorUnitarioServ.setText(TbCompraServ.getValueAt(i, 4).toString());
                        prodcompravenda.setValorunit(Float.parseFloat(TfValorUnitarioServ.getValue().toString()));
                        TfDescontoServ.setText(TbCompraServ.getValueAt(i, 5).toString());
                        prodcompravenda.setDesconto(Float.parseFloat(TfDescontoServ.getValue().toString()));
                        TfValorProdutoServ.setText(TbCompraServ.getValueAt(i, 6).toString());
                        prodcompravenda.setValorprodut(Float.parseFloat(TfValorProdutoServ.getValue().toString()));
                        prodcompravenda.setPromocao(TbCompraServ.getValueAt(i, 7).toString());
                        prodcompravenda.incluirprodutocompravenda();
                    }
                    parcelas.getConta().setTotal(Float.parseFloat(TfValorTotalCompraServ.getValue().toString()));
                }
                
                parcelas.getConta().setCompravenda(prodcompravenda.getCompravenda());
                parcelas.getConta().setCondicao(prodcompravenda.getCompravenda().getCondicao());
                parcelas.getConta().setOperacao(prodcompravenda.getCompravenda().getOperacao());
                parcelas.getConta().setDescricao(prodcompravenda.getCompravenda().getDescricao());
                parcelas.getConta().setDtconta(TfData.getText());
                parcelas.getConta().setCodigopessoa(prodcompravenda.getCompravenda().getCodigopessoa());
                parcelas.getConta().incluir();

                parcelas.gerarparcelas();

                final InterfaceAjusteDatasEPrecos tela = new InterfaceAjusteDatasEPrecos(getPrimeiratela(), true, parcelas);
                tela.setVisible(true);
                tela.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosed(java.awt.event.WindowEvent evt) {
                        HashMap filtro = new HashMap();
                        filtro.put("CD_COMPRA_VENDA", prodcompravenda.getCompravenda().getCodigo());
                        filtro.put("CD_OPERACAO", prodcompravenda.getCompravenda().getOperacao().getCodigo());
                        filtro.put("CD_CONTA", parcelas.getConta().getCodigo());
                        filtro.put("DS_NOTA", "EXTRATO DE COMPRA");
                        filtro.put("TP_PESSOA", "Fornecedor:");
                        ConexaoPostgre conexao = new ConexaoPostgre();
                        JDialog dialog = new JDialog(new javax.swing.JFrame(), "Visualização - Software Loja da Fátima", true);
                        dialog.setSize(1000, 700);
                        dialog.setLocationRelativeTo(null);
                        try {
                            JasperPrint print = JasperFillManager.fillReport("relatorios\\notaoperacaoestoquefinanceiro.jasper", filtro, conexao.conecta());
                            
                            JasperViewer viewer = new JasperViewer(print, true);
                            dialog.getContentPane().add(viewer.getContentPane());
                            dialog.setVisible(true);
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                    }
                });

                limpar.Limpar(jPanel1);
                limpar.Limpar(jPanel3);
                limpar.Limpar(jPanel4);
                limpar.Limpar(TbCompra);
                valida.validacamposCancelar(jPanel1, PnBotoes);
                valida.validacamposCancelar(jPanel3, PnBotoes);
                valida.validacamposCancelar(jPanel4, PnBotoes);
            }
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar esta compra?\n"
                + "(Caso sim, TODOS os dados digitados serão limpos da tela)", "Deseja cancelar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpar.Limpar(jPanel1);
            limpar.Limpar(TbCompra);
            valida.validacamposCancelar(jPanel1, PnBotoes);
            valida.validacamposCancelar(jPanel3, PnBotoes);
            valida.validacamposCancelar(jPanel4, PnBotoes);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void TfQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyReleased
        if (TfDesconto.getValue() == BigDecimal.ZERO) TfValorProduto.setValue(TfQuantidade.getValue().multiply(TfValorUnitario.getValue()));
        else {
            TfValorProduto.setValue(TfQuantidade.getValue().multiply(TfValorUnitario.getValue()));
            TfValorProduto.setValue(TfValorProduto.getValue().subtract((TfValorProduto.getValue().multiply(TfDesconto.getValue())).divide(BigDecimal.valueOf(100))));
        }
    }//GEN-LAST:event_TfQuantidadeKeyReleased

    private void TfValorUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioKeyReleased
        TfQuantidadeKeyReleased(evt);
    }//GEN-LAST:event_TfValorUnitarioKeyReleased

    private void TfQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyTyped
        valida.limitemaximo(evt, TfQuantidade.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeKeyTyped

    private void TfValorUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioKeyTyped
        valida.limitemaximo(evt, TfValorUnitario.getText(), 13);
    }//GEN-LAST:event_TfValorUnitarioKeyTyped

    private void TfCodFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodFuncionarioFocusLost
        if (TfFuncionario.getText().equals("")) {
            TfCodFuncionario.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código do funcionário corretamente!");
            TfDesconto.setEditable(false);
        } else {
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
            TfDesconto.setEditable(true);
        }
    }//GEN-LAST:event_TfCodFuncionarioFocusLost

    private void TfCodFornecedorFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodFornecedorFocusLost
        if (TfFornecedor.getText().equals("")) {
            TfCodFornecedor.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código do fornecedor corretamente!");
        } else {
            prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodFornecedor.getText().toString()));
        }
    }//GEN-LAST:event_TfCodFornecedorFocusLost

    private void TfCodCondicaoPgtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodCondicaoPgtoFocusLost
        if (TfCondicaoPgto.getText().equals("")) {
            TfCodCondicaoPgto.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código da condição de pagamento corretamente!");
        }
    }//GEN-LAST:event_TfCodCondicaoPgtoFocusLost

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (PnBotoes.isVisible() && BtGravar.isEnabled()) {
            if (JOptionPane.showConfirmDialog(null, "Você está prestes a fechar esta janela.\nAo fechar esta janela, tudo que você digitou será esquecido!", "Tem certeza que deseja fechar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void TfDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoKeyReleased
        if (TfValorUnitario.getValue() != BigDecimal.valueOf(0)){
            if (TfQuantidade.getValue() != BigDecimal.valueOf(0)){
                TfQuantidadeKeyReleased(evt);
            }else{
                msg.CampoNaoPreenchido(LbNotificacao, "Digite a quantidade do produto!");
                TfDesconto.setValue(BigDecimal.ZERO);
                TfQuantidade.grabFocus();
            }
        }else{
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do produto!");
            TfDesconto.setValue(BigDecimal.ZERO);
            TfValorUnitario.grabFocus();
        }
    }//GEN-LAST:event_TfDescontoKeyReleased

    private void TfCodServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodServicoKeyReleased
        if (!TfCodServico.getText().equals("")) {
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodServico.getText()));
            if (!TfCodFornecedor.getText().equals("")){
                if (prodcompravenda.getForneproduto().getProduto().eprodutoativo() && prodcompravenda.getForneproduto().produtodestefornecedor() && prodcompravenda.getForneproduto().getProduto().eservico()) {
                    TfServico.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                    TfValorUnitarioServ.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto()));
                    TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                    TfValorProdutoServ.setValue(BigDecimal.valueOf(0));
                } else {
                    TfServico.setText("");
                    TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
                    TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                    TfValorProdutoServ.setValue(BigDecimal.valueOf(0));
                    if(prodcompravenda.getForneproduto().getProduto().eprodutoativo() && !prodcompravenda.getForneproduto().produtodestefornecedor() && prodcompravenda.getForneproduto().getProduto().eservico()){
                        msg.CampoNaoPreenchido(LbNotificacao, "Este serviço não pode ser adquirido com este fornecedor!");
                    }
                }
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Insira o Fornecedor da Compra para que o sistema faça a busca dos Serviços!");
                TfCodFornecedor.grabFocus();
            }
        } else {
            TfServico.setText("");
            TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
            TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
            TfValorProdutoServ.setValue(BigDecimal.valueOf(0));
        }
    }//GEN-LAST:event_TfCodServicoKeyReleased

    private void BtPesqServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqServicoActionPerformed
        final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto(), "S");
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodServico.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodServicoKeyReleased(null);
                } else {
                    TfCodServico.setText("");
                    TfCodServicoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqServicoActionPerformed

    private void BtCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadServicoActionPerformed
        BtCadProdutoActionPerformed(evt);
    }//GEN-LAST:event_BtCadServicoActionPerformed

    private void TfQuantidadeServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeServKeyReleased
        if (TfDescontoServ.getValue() == BigDecimal.ZERO) TfValorProdutoServ.setValue(TfQuantidadeServ.getValue().multiply(TfValorUnitarioServ.getValue()));
        else {
            TfValorProdutoServ.setValue(TfQuantidadeServ.getValue().multiply(TfValorUnitarioServ.getValue()));
            TfValorProdutoServ.setValue(TfValorProdutoServ.getValue().subtract((TfValorProdutoServ.getValue().multiply(TfDescontoServ.getValue())).divide(BigDecimal.valueOf(100))));
        }
    }//GEN-LAST:event_TfQuantidadeServKeyReleased

    private void TfQuantidadeServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeServKeyTyped
        valida.limitemaximo(evt, TfQuantidadeServ.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeServKeyTyped

    private void BtIncluirServicoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirServicoCompraActionPerformed
        boolean inclui = true;
        limpar.Limpar(TbCompra);
        TfQuantidadeServKeyReleased(null);
        TfValorTotalCompra.setValue(BigDecimal.ZERO);
        if (!TfCodServico.getText().equals("") && !TfServico.getText().equals("")) {
            if (TfValorProdutoServ.getValue() != BigDecimal.valueOf(0)) {
                for (int i = 0; i < TbCompraServ.getRowCount(); i++) {
                    if (Integer.parseInt(TbCompraServ.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodServico.getText())) {
                        inclui = false;
                        if (JOptionPane.showConfirmDialog(null, "Este serviço já foi adiconado a esta compra!\n"
                                + "Deseja substituir a quantidade adquirida deste serviço?", "Serviço adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                            TbCompraServ.setValueAt(TfQuantidadeServ.getText(), i, 3);
                            TbCompraServ.setValueAt(TfValorUnitarioServ.getText(), i, 4);
                            TbCompraServ.setValueAt(TfDescontoServ.getText(), i, 5);
                            TbCompraServ.setValueAt(TfValorProdutoServ.getText(), i, 6);
                            String promoc;
                            if (CbPromocaoServ.isSelected()) promoc = "S";
                            else                       promoc = "N";
                            TbCompraServ.setValueAt(promoc, i, 7);
                        }
                    }
                }
                if (inclui) {
                    DefaultTableModel tabela = (DefaultTableModel) TbCompraServ.getModel();
                    int linha = tabela.getRowCount();
                    tabela.setNumRows(linha + 1);
                    tabela.setValueAt(TfCodigo.getText(), linha, 0);
                    tabela.setValueAt(TfCodServico.getText(), linha, 1);
                    tabela.setValueAt(TfServico.getText(), linha, 2);
                    tabela.setValueAt(TfQuantidadeServ.getText(), linha, 3);
                    tabela.setValueAt(TfValorUnitarioServ.getText(), linha, 4);
                    tabela.setValueAt(TfDescontoServ.getText(), linha, 5);
                    tabela.setValueAt(TfValorProdutoServ.getText(), linha, 6);
                    String promoc;
                    if (CbPromocaoServ.isSelected()) promoc = "S";
                    else                       promoc = "N";
                    tabela.setValueAt(promoc, linha, 7);
                }
                TfCodServico.setText("");
                TfServico.setText("");
                TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
                TfDesconto.setValue(BigDecimal.valueOf(0));
                TfValorProdutoServ.setValue(BigDecimal.valueOf(0));
                CbPromocaoServ.setSelected(false);
                atualizavalortotalserv();
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do serviço e a quantidade corretamente!");
            }
        } else {
            msg.CampoNaoPreenchido(LbNotificacao, "Informe o serviço a ser adicionado nesta compra!");
            TfCodServico.grabFocus();
        }
    }//GEN-LAST:event_BtIncluirServicoCompraActionPerformed

    private void BtRemoverServicoCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverServicoCompraActionPerformed
        int linha = TbCompraServ.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este serviço da compra?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbCompraServ.getModel();
                tabela.removeRow(linha);
                atualizavalortotalserv();
            }
        }
    }//GEN-LAST:event_BtRemoverServicoCompraActionPerformed

    private void TfValorUnitarioServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioServKeyReleased
        TfQuantidadeServKeyReleased(evt);
    }//GEN-LAST:event_TfValorUnitarioServKeyReleased

    private void TfValorUnitarioServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioServKeyTyped
        valida.limitemaximo(evt, TfValorUnitarioServ.getText(), 13);
    }//GEN-LAST:event_TfValorUnitarioServKeyTyped

    private void TfDescontoServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoServKeyReleased
        if (TfValorUnitarioServ.getValue() != BigDecimal.valueOf(0)){
            if (TfQuantidadeServ.getValue() != BigDecimal.valueOf(0)){
                TfQuantidadeServKeyReleased(evt);
            }else{
                msg.CampoNaoPreenchido(LbNotificacao, "Digite a quantidade do serviço!");
                TfDescontoServ.setValue(BigDecimal.ZERO);
                TfQuantidadeServ.grabFocus();
            }
        }else{
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do serviço!");
            TfDescontoServ.setValue(BigDecimal.ZERO);
            TfValorUnitarioServ.grabFocus();
        }
    }//GEN-LAST:event_TfDescontoServKeyReleased

    private void TfDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoKeyTyped
        valida.limitemaximo(evt, TfDesconto.getText(), 10);
    }//GEN-LAST:event_TfDescontoKeyTyped

    private void TfDescontoServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoServKeyTyped
        valida.limitemaximo(evt, TfDescontoServ.getText(), 10);
    }//GEN-LAST:event_TfDescontoServKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadCondicaoPgto;
    private javax.swing.JButton BtCadFornecedor;
    private javax.swing.JButton BtCadFuncionario;
    private javax.swing.JButton BtCadProduto;
    private javax.swing.JButton BtCadServico;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtIncluir;
    private javax.swing.JButton BtIncluirProdutoCompra;
    private javax.swing.JButton BtIncluirServicoCompra;
    private javax.swing.JButton BtPesqFormaPgto;
    private javax.swing.JButton BtPesqFornecedor;
    private javax.swing.JButton BtPesqFuncionario;
    private javax.swing.JButton BtPesqProduto;
    private javax.swing.JButton BtPesqServico;
    private javax.swing.JButton BtRemoverProdutoCompra;
    private javax.swing.JButton BtRemoverServicoCompra;
    private javax.swing.JCheckBox CbPromocao;
    private javax.swing.JCheckBox CbPromocaoServ;
    private javax.swing.JLabel LbNotificacao;
    private javax.swing.JPanel PnBotoes;
    private javax.swing.JTable TbCompra;
    private javax.swing.JTable TbCompraServ;
    private javax.swing.JTextField TfCodCondicaoPgto;
    private javax.swing.JTextField TfCodFornecedor;
    private javax.swing.JTextField TfCodFuncionario;
    private javax.swing.JTextField TfCodProduto;
    private javax.swing.JTextField TfCodServico;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfCondicaoPgto;
    private javax.swing.JFormattedTextField TfData;
    private javax.swing.JTextField TfDescNotaCompra;
    private JNumberField.JNumberField TfDesconto;
    private JNumberField.JNumberField TfDescontoServ;
    private javax.swing.JTextField TfFornecedor;
    private javax.swing.JTextField TfFuncionario;
    private javax.swing.JTextField TfProduto;
    private JNumberField.JNumberField TfQuantidade;
    private JNumberField.JNumberField TfQuantidadeServ;
    private javax.swing.JTextField TfServico;
    private JNumberField.JNumberField TfValorProduto;
    private JNumberField.JNumberField TfValorProdutoServ;
    private JNumberField.JNumberField TfValorTotalCompra;
    private JNumberField.JNumberField TfValorTotalCompraServ;
    private JNumberField.JNumberField TfValorUnitario;
    private JNumberField.JNumberField TfValorUnitarioServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario() {
        getTelasusuario().getTela().setCodigo(16);
        if (!getTelasusuario().eadmintela()) {
            PnBotoes.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(2);
        if (!getTelasusuario().eadmintela()) {
            BtCadFornecedor.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(3);
        if (!getTelasusuario().eadmintela()) {
            BtCadFuncionario.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(11);
        if (!getTelasusuario().eadmintela()) {
            BtCadProduto.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(6);
        if (!getTelasusuario().eadmintela()) {
            BtCadCondicaoPgto.setVisible(false);
        }
    }

    public void atualizavalortotal() {
        float valor = 0;
        for (int i = 0; i < TbCompra.getRowCount(); i++) {
            TfValorTotalCompra.setText(TbCompra.getValueAt(i, 6).toString());
            valor = valor + Float.parseFloat(TfValorTotalCompra.getValue().toString());
        }
        TfValorTotalCompra.setValue(BigDecimal.valueOf(valor));
    }
    
    public void atualizavalortotalserv() {
        float valor = 0;
        for (int i = 0; i < TbCompraServ.getRowCount(); i++) {
            TfValorTotalCompraServ.setText(TbCompraServ.getValueAt(i, 6).toString());
            valor = valor + Float.parseFloat(TfValorTotalCompraServ.getValue().toString());
        }
        TfValorTotalCompraServ.setValue(BigDecimal.valueOf(valor));
    }

    public boolean camposobrigatoriospreenchidos() {
        if (TfDescNotaCompra.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite o código da nota do fornecedor!");
            TfDescNotaCompra.grabFocus();
            return false;
        }
        if (TfCodFuncionario.getText().equals("") || TfFuncionario.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira o Funcionário que esta realizando o antendimento nesta compra!");
            TfCodFuncionario.grabFocus();
            return false;
        }
        if (TfCodFornecedor.getText().equals("") || TfFornecedor.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira qual o Fornecedor desta compra!");
            TfCodFornecedor.grabFocus();
            return false;
        }
        if (TfCodCondicaoPgto.getText().equals("") || TfCondicaoPgto.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira a condição de pagamento escolhida para esta compra!");
            TfCodCondicaoPgto.grabFocus();
            return false;
        }
        if (TbCompra.getRowCount() < 1 && TbCompraServ.getRowCount() < 1) {            
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira os produtos ou serviços desta compra!");
            return false;
        }
        return true;
    }

    public void enviardados() {
        prodcompravenda.getCompravenda().setData(datas.retornadataehora());
        prodcompravenda.getCompravenda().setDescricao("COMPRA COM O FORNECEDOR " + TfFornecedor.getText() + " - " + TfDescNotaCompra.getText()+ " - CÓDIGO DO SISTEMA: "+TfCodigo.getText());
        prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodFornecedor.getText()));
        prodcompravenda.getCompravenda().setCodigopessoa(prodcompravenda.getForneproduto().getFornecedor().retornacodigopessoafornecedor());
        prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
        prodcompravenda.getCompravenda().getOperacao().setCodigo(1);
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
