package br.com.lojadafatima.InterfacesOperacoes;

import br.com.lojadafatima.ClassesFerramentas.ClasseDatas;
import br.com.lojadafatima.ClassesFerramentas.GeraCodigos;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseOperacoes;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseProdutosCompraVenda;
import br.com.lojadafatima.ConexaoBDpostgre.ConexaoPostgre;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesCliente;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFornecedor;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFuncionario;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesProduto;
import br.com.lojadafatima.InterfacesPessoa.InterfaceCliente;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFornecedor;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFuncionario;
import br.com.lojadafatima.InterfacesProduto.InterfaceProduto;
import br.com.lojadafatima.Pessoa.ClasseCliente;
import br.com.lojadafatima.Produto.ClasseMvtoEstoque;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import java.math.BigDecimal;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceOperacaoEstoque extends javax.swing.JDialog {

    MaskFormatter data, valor;
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    ClasseCliente cliente = new ClasseCliente();
    ClasseProdutosCompraVenda prodcompravenda = new ClasseProdutosCompraVenda();
    ClasseDatas datas = new ClasseDatas();
    LimpaCamposTela limpar = new LimpaCamposTela();
    private java.awt.Frame primeiratela;
    boolean estoqueok = false;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    MensagensUsuario msg = new MensagensUsuario();

    public InterfaceOperacaoEstoque(java.awt.Frame telaorigem, boolean modal, ClasseOperacoes ope, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(telasusuario);
        prodcompravenda.getCompravenda().setOperacao(ope);
        TfData.setText(datas.retornadataatual());
        TfCodFuncionario.setDocument(new PermiteApenasNumeros());
        TfCodPessoa.setDocument(new PermiteApenasNumeros());
        TfCodProduto.setDocument(new PermiteApenasNumeros());
        TfCodServico.setDocument(new PermiteApenasNumeros());
        TfDescOperacao.setDocument(new NaoPermiteAspasSimples());
        valida.validacamposCancelar(jPanel1, PnBotoes);
        valida.validacamposCancelar(jPanel3, PnBotoes);
        valida.validacamposCancelar(jPanel4, PnBotoes);
        analisausuario();
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        TbProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        CbPessoaActionPerformed(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel montar mascara no campo de Data");
        }
        TfData = new JFormattedTextField(data);
        TfDescOperacao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CbPessoa = new javax.swing.JComboBox();
        LbCodPessoa = new javax.swing.JLabel();
        TfCodPessoa = new javax.swing.JTextField();
        BtPesqPessoa = new javax.swing.JButton();
        TfPessoa = new javax.swing.JTextField();
        LbNomePessoa = new javax.swing.JLabel();
        BtCadPessoa = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        TfCodFuncionario = new javax.swing.JTextField();
        BtPesqFuncionario = new javax.swing.JButton();
        TfFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtCadFuncionario = new javax.swing.JButton();
        PnBotoes = new javax.swing.JPanel();
        BtGravar = new javax.swing.JButton();
        BtIncluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LbNotificacao = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbProdutos = new javax.swing.JTable();
        BtIncluirProdutoTabela = new javax.swing.JButton();
        BtRemoverProdutoTabela = new javax.swing.JButton();
        TfQuantidade = new JNumberField.JNumberField(2);
        ;
        jLabel11 = new javax.swing.JLabel();
        TfCodProduto = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        BtPesqProduto = new javax.swing.JButton();
        TfProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtCadProduto = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        TfCodServico = new javax.swing.JTextField();
        BtPesqServico = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        TfServico = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        BtCadServico = new javax.swing.JButton();
        TfQuantidadeServ = new JNumberField.JNumberField(2);
        ;
        jLabel14 = new javax.swing.JLabel();
        BtIncluirServicoTabela = new javax.swing.JButton();
        BtRemoverServicoTabela = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbServicos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operação de Estoque - Software Loja da Fátima");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfCodigo.setEditable(false);
        jPanel1.add(TfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 80, -1));

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jLabel2.setText("Data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 11, -1, -1));

        TfData.setEditable(false);
        jPanel1.add(TfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 31, 79, -1));

        TfDescOperacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescOperacaoKeyTyped(evt);
            }
        });
        jPanel1.add(TfDescOperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 31, 230, -1));

        jLabel18.setText("Descrição da Operação");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(189, 11, -1, -1));

        jLabel5.setText("Quem está envolvido nesta operação?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        CbPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Fornecedor" }));
        CbPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(CbPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 75, 184, -1));

        LbCodPessoa.setText("Cód. Pessoa");
        jPanel1.add(LbCodPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 106, -1, -1));

        TfCodPessoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodPessoaFocusLost(evt);
            }
        });
        TfCodPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodPessoaKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 127, 117, -1));

        BtPesqPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 126, -1, -1));

        TfPessoa.setEditable(false);
        jPanel1.add(TfPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 127, 303, -1));

        LbNomePessoa.setText("Nome/Nome Fantasia");
        jPanel1.add(LbNomePessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 106, -1, -1));

        BtCadPessoa.setText("Cadastrar Pessoa");
        BtCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 126, 139, -1));

        jLabel3.setText("Cód. Funcionário");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 157, 200, -1));

        TfCodFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodFuncionarioFocusLost(evt);
            }
        });
        TfCodFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodFuncionarioKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 178, 117, -1));

        BtPesqFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(133, 177, -1, -1));

        TfFuncionario.setEditable(false);
        jPanel1.add(TfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 178, 303, -1));

        jLabel4.setText("Funcionário");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(188, 157, -1, -1));

        BtCadFuncionario.setText("Cadastrar Funcionário");
        BtCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(498, 177, -1, -1));

        BtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/salvar.png"))); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.setName("Gravar"); // NOI18N
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluir.setText("Nova Operação");
        BtIncluir.setName("Incluir"); // NOI18N
        BtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirActionPerformed(evt);
            }
        });

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/cancelar.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.setName("Cancelar"); // NOI18N
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotoesLayout = new javax.swing.GroupLayout(PnBotoes);
        PnBotoes.setLayout(PnBotoesLayout);
        PnBotoesLayout.setHorizontalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotoesLayout.createSequentialGroup()
                .addComponent(BtIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnBotoesLayout.setVerticalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(BtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(PnBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 527, 627, -1));

        LbNotificacao.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LbNotificacao)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacao)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 571, 627, -1));

        TbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Operação", "Cód. Produto", "Produto", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbProdutos);

        BtIncluirProdutoTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirProdutoTabela.setText("Incluir Produto");
        BtIncluirProdutoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirProdutoTabelaActionPerformed(evt);
            }
        });

        BtRemoverProdutoTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverProdutoTabela.setText("Remover Produto");
        BtRemoverProdutoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverProdutoTabelaActionPerformed(evt);
            }
        });

        TfQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfQuantidadeFocusLost(evt);
            }
        });
        TfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyTyped(evt);
            }
        });

        jLabel11.setText("Quantidade");

        TfCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodProdutoKeyReleased(evt);
            }
        });

        jLabel9.setText("Cód. Produto");

        BtPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqProdutoActionPerformed(evt);
            }
        });

        TfProduto.setEditable(false);

        jLabel10.setText("Produto");

        BtCadProduto.setText("Cadastrar Produto");
        BtCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel11)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(BtIncluirProdutoTabela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtRemoverProdutoTabela))
                            .addComponent(TfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(TfCodProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtPesqProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(TfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtCadProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtPesqProduto)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtCadProduto)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtIncluirProdutoTabela)
                    .addComponent(BtRemoverProdutoTabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Produtos", jPanel3);

        TfCodServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodServicoKeyReleased(evt);
            }
        });

        BtPesqServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqServicoActionPerformed(evt);
            }
        });

        jLabel12.setText("Cód. Serviço");

        TfServico.setEditable(false);

        jLabel13.setText("Serviço");

        BtCadServico.setText("Cadastrar Serviço");
        BtCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadServicoActionPerformed(evt);
            }
        });

        TfQuantidadeServ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfQuantidadeServFocusLost(evt);
            }
        });
        TfQuantidadeServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeServKeyTyped(evt);
            }
        });

        jLabel14.setText("Quantidade");

        BtIncluirServicoTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirServicoTabela.setText("Incluir Serviço");
        BtIncluirServicoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirServicoTabelaActionPerformed(evt);
            }
        });

        BtRemoverServicoTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverServicoTabela.setText("Remover Serviço");
        BtRemoverServicoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverServicoTabelaActionPerformed(evt);
            }
        });

        TbServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Operação", "Cód. Serviço", "Serviço", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbServicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TbServicos);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel14)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(BtIncluirServicoTabela)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtRemoverServicoTabela))
                            .addComponent(TfQuantidadeServ, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(TfCodServico, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtPesqServico, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13)
                                    .addGroup(jPanel4Layout.createSequentialGroup()
                                        .addComponent(TfServico, javax.swing.GroupLayout.PREFERRED_SIZE, 304, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(BtCadServico, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addContainerGap())))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtPesqServico)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TfCodServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(TfServico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BtCadServico)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TfQuantidadeServ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtIncluirServicoTabela)
                    .addComponent(BtRemoverServicoTabela))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Serviços", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 208, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TfDescOperacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescOperacaoKeyTyped
        valida.limitemaximo(evt, TfDescOperacao.getText(), 50);
    }//GEN-LAST:event_TfDescOperacaoKeyTyped

    private void CbPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPessoaActionPerformed
        limpar.Limpar(TbProdutos);
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            LbCodPessoa.setText("Cód. Cliente");
            LbNomePessoa.setText("Cliente");
            BtCadPessoa.setText("Cadastrar Cliente");
        } else {
            LbCodPessoa.setText("Cód. Fornecedor");
            LbNomePessoa.setText("Fornecedor");
            BtCadPessoa.setText("Cadastrar Fornecedor");
        }
        analisausuario();
        TfCodPessoaKeyReleased(null);
    }//GEN-LAST:event_CbPessoaActionPerformed

    private void TfCodPessoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodPessoaKeyReleased
        limpar.Limpar(TbProdutos);
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            if (!TfCodPessoa.getText().equals("")) {
                cliente.setCodigo(Integer.parseInt(TfCodPessoa.getText()));
                if (cliente.eativo()) {
                    TfPessoa.setText(cliente.retornanomecliente());
                } else {
                    TfPessoa.setText("");
                }
            } else {
                TfPessoa.setText("");
            }
        } else {
            if (!TfCodPessoa.getText().equals("")) {
                prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodPessoa.getText()));
                if (prodcompravenda.getForneproduto().getFornecedor().efornecedorativo()) {
                    prodcompravenda.getForneproduto().getFornecedor().getPessoajur().getPessoa().setCodigo(prodcompravenda.getForneproduto().getFornecedor().retornacodigopessoafornecedor());
                    TfPessoa.setText(prodcompravenda.getForneproduto().getFornecedor().getPessoajur().retornanomeporCodigo());
                } else {
                    TfPessoa.setText("");
                }
            } else {
                TfPessoa.setText("");
            }
        }
    }//GEN-LAST:event_TfCodPessoaKeyReleased

    private void BtPesqPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqPessoaActionPerformed
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            final ConsulSimplesCliente tela = new ConsulSimplesCliente(getPrimeiratela(), true, cliente);
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    if (cliente.getCodigo() != 0) {
                        TfCodPessoa.setText("" + cliente.getCodigo());
                        TfCodPessoaKeyReleased(null);
                    } else {
                        TfCodPessoa.setText("");
                        TfPessoa.setText("");
                    }
                }
            });
        } else {
            final ConsulSimplesFornecedor tela = new ConsulSimplesFornecedor(getPrimeiratela(), true, prodcompravenda.getForneproduto().getFornecedor());
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    if (prodcompravenda.getForneproduto().getFornecedor().getCodigo() != 0) {
                        TfCodPessoa.setText("" + prodcompravenda.getForneproduto().getFornecedor().getCodigo());
                        TfCodPessoaKeyReleased(null);
                    } else {
                        TfCodPessoa.setText("");
                        TfPessoa.setText("");
                    }
                }
            });
        }
    }//GEN-LAST:event_BtPesqPessoaActionPerformed

    private void BtCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadPessoaActionPerformed
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            final InterfaceCliente tela = new InterfaceCliente(getPrimeiratela(), true, getTelasusuario());
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {

                }
            });
        } else {
            final InterfaceFornecedor tela = new InterfaceFornecedor(getPrimeiratela(), true, getTelasusuario());
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {

                }
            });
        }
    }//GEN-LAST:event_BtCadPessoaActionPerformed

    private void TfCodFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFuncionarioKeyReleased
        if (!TfCodFuncionario.getText().equals("")) {
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
            if (prodcompravenda.getCompravenda().getFuncionario().efuncionarioativo()) {
                prodcompravenda.getCompravenda().getFuncionario().getPessoafis().getPessoa().setCodigo(prodcompravenda.getCompravenda().getFuncionario().retornacodigopessoafuncionario());
                TfFuncionario.setText(prodcompravenda.getCompravenda().getFuncionario().getPessoafis().retornanomeporCodigo());
            } else {
                TfFuncionario.setText("");
            }
        } else {
            TfFuncionario.setText("");
        }
    }//GEN-LAST:event_TfCodFuncionarioKeyReleased

    private void BtPesqFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFuncionarioActionPerformed
        final ConsulSimplesFuncionario tela = new ConsulSimplesFuncionario(getPrimeiratela(), true, prodcompravenda.getCompravenda().getFuncionario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getFuncionario().getCodigo() != 0) {
                    TfCodFuncionario.setText("" + prodcompravenda.getCompravenda().getFuncionario().getCodigo());
                    TfCodFuncionarioKeyReleased(null);
                } else {
                    TfCodFuncionario.setText("");
                    TfFuncionario.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqFuncionarioActionPerformed

    private void BtCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadFuncionarioActionPerformed
        final InterfaceFuncionario tela = new InterfaceFuncionario(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadFuncionarioActionPerformed

    private void TfCodProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodProdutoKeyReleased
        if (!TfCodProduto.getText().equals("")) {
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
            if (prodcompravenda.getForneproduto().getProduto().eprodutoativo() && !prodcompravenda.getForneproduto().getProduto().eservico()) {
                if (CbPessoa.getSelectedItem().toString().equals("Fornecedor") && prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("E")){
                    if(!TfCodPessoa.getText().equals("") && !TfPessoa.getText().equals("")){
                        if(prodcompravenda.getForneproduto().produtodestefornecedor()){
                            TfProduto.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                            TfQuantidade.setValue(BigDecimal.valueOf(0));
                        }else{
                            TfProduto.setText("");
                            TfQuantidade.setValue(BigDecimal.valueOf(0));
                            msg.CampoNaoPreenchido(LbNotificacao, "Este produto não pode ser adquirido com este fornecedor!");
                        }
                    }else{
                        msg.CampoNaoPreenchido(LbNotificacao, "Digite o Fornecedor para que o sistema busque os produtos apenas deste Fornecedor!");
                        limpar.Limpar(jPanel3);
                        TfCodPessoa.grabFocus();
                    }
                }else{
                    TfProduto.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                }
            } else {
                TfProduto.setText("");
                TfQuantidade.setValue(BigDecimal.valueOf(0));
            }
        } else {
            TfProduto.setText("");
            TfQuantidade.setValue(BigDecimal.valueOf(0));
        }
    }//GEN-LAST:event_TfCodProdutoKeyReleased

    private void BtPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqProdutoActionPerformed
        final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto(), "P");
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodProduto.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodProdutoKeyReleased(null);
                } else {
                    TfCodProduto.setText("");
                    TfCodProdutoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqProdutoActionPerformed

    private void BtCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadProdutoActionPerformed
        final InterfaceProduto tela = new InterfaceProduto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadProdutoActionPerformed

    private void BtIncluirProdutoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirProdutoTabelaActionPerformed
        boolean inclui = true;
        limpar.Limpar(TbServicos);
        if (prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("S") || prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("E")) {
            if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
                if (TfQuantidade.getValue() != BigDecimal.valueOf(0) && estoqueok) {
                    for (int i = 0; i < TbProdutos.getRowCount(); i++) {
                        if (Integer.parseInt(TbProdutos.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodProduto.getText())) {
                            inclui = false;
                            if (JOptionPane.showConfirmDialog(null, "Este produto já foi adiconado!\n"
                                    + "Deseja substituir a quantidade deste produto?", "Produto adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                TbProdutos.setValueAt(TfQuantidade.getText(), i, 3);
                            }
                        }
                    }
                    if (inclui) {
                        DefaultTableModel tabela = (DefaultTableModel) TbProdutos.getModel();
                        int linha = tabela.getRowCount();
                        tabela.setNumRows(linha + 1);
                        tabela.setValueAt(TfCodigo.getText(), linha, 0);
                        tabela.setValueAt(TfCodProduto.getText(), linha, 1);
                        tabela.setValueAt(TfProduto.getText(), linha, 2);
                        tabela.setValueAt(TfQuantidade.getText(), linha, 3);
                    }
                    TfCodProduto.setText("");
                    TfProduto.setText("");
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                } else {
                    msg.CampoNaoPreenchido(LbNotificacao, "Digite a quantidade corretamente!");
                }
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Informe o produto a ser adicionado!");
                TfCodProduto.grabFocus();
            }
        }
    }//GEN-LAST:event_BtIncluirProdutoTabelaActionPerformed

    private void BtRemoverProdutoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverProdutoTabelaActionPerformed
        int linha = TbProdutos.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este produto da operação?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbProdutos.getModel();
                tabela.removeRow(linha);
            }
        }
    }//GEN-LAST:event_BtRemoverProdutoTabelaActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (camposobrigatoriospreenchidos()) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Gravar esta operação e de que todas as informações estao corretas?", "Deseja gravar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                enviardados();
                prodcompravenda.getCompravenda().incluir();

                ClasseMvtoEstoque mvestoque = new ClasseMvtoEstoque();
                mvestoque.setCompravenda(prodcompravenda.getCompravenda());
                mvestoque.setDtmvto(datas.retornadataehora());
                mvestoque.setTpmvto(prodcompravenda.getCompravenda().getOperacao().getTpestoque());
                
                if(TbProdutos.getRowCount() > 0){
                    for (int i = 0; i < TbProdutos.getRowCount(); i++) {
                        prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbProdutos.getValueAt(i, 1).toString()));
                        TfQuantidade.setText(TbProdutos.getValueAt(i, 3).toString());
                        prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidade.getValue().toString()));
                        prodcompravenda.setValorunit(0);
                        prodcompravenda.setValorprodut(0);
                        prodcompravenda.setPromocao("");
                        prodcompravenda.incluirprodutocompravenda();

                        mvestoque.getProduto().setCodigo(Integer.parseInt(TbProdutos.getValueAt(i, 1).toString()));
                        TfQuantidade.setText(TbProdutos.getValueAt(i, 3).toString());
                        mvestoque.setQtmvto(Float.parseFloat(TfQuantidade.getValue().toString()));
                        mvestoque.incluirmvto();
                    }
                } else if(TbServicos.getRowCount() > 0){
                    for (int i = 0; i < TbServicos.getRowCount(); i++) {
                        prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbServicos.getValueAt(i, 1).toString()));
                        TfQuantidadeServ.setText(TbServicos.getValueAt(i, 3).toString());
                        prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidadeServ.getValue().toString()));
                        prodcompravenda.setValorunit(0);
                        prodcompravenda.setValorprodut(0);
                        prodcompravenda.setPromocao("");
                        prodcompravenda.incluirprodutocompravenda();
                    }
                }
                
                HashMap filtro = new HashMap();
                filtro.put("CD_COMPRA_VENDA", prodcompravenda.getCompravenda().getCodigo());
                filtro.put("CD_OPERACAO", prodcompravenda.getCompravenda().getOperacao().getCodigo());
                filtro.put("DS_NOTA", "EXTRATO DE "+prodcompravenda.getCompravenda().getOperacao().getDescricao());
                if(CbPessoa.getSelectedItem().toString().equals("Fornecedor:")) filtro.put("TP_PESSOA", "Fornecedor:");
                else                                                            filtro.put("TP_PESSOA", "Cliente:");
                ConexaoPostgre conexao = new ConexaoPostgre();
                JDialog dialog = new JDialog(new javax.swing.JFrame(), "Visualização - Software Loja da Fátima", true);
                dialog.setSize(1000, 700);
                dialog.setLocationRelativeTo(null);
                try {
                    JasperPrint print = JasperFillManager.fillReport("relatorios\\notaoperacaoestoque.jasper", filtro, conexao.conecta());
                    
                    JasperViewer viewer = new JasperViewer(print, true);
                    dialog.getContentPane().add(viewer.getContentPane());
                    dialog.setVisible(true);
                } catch (Exception ex) {
                    System.out.println(ex);
                }

                limpar.Limpar(jPanel1);
                limpar.Limpar(jPanel3);
                limpar.Limpar(jPanel4);
                limpar.Limpar(TbServicos);
                limpar.Limpar(TbProdutos);
                valida.validacamposCancelar(jPanel1, PnBotoes);
                valida.validacamposCancelar(jPanel3, PnBotoes);
                valida.validacamposCancelar(jPanel4, PnBotoes);
            }
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirActionPerformed
        TfData.setText(datas.retornadataatual());
        GeraCodigos geracodigos = new GeraCodigos();
        TfCodigo.setText("" + geracodigos.gerasequencia("COMPRA_VENDA", "CD_COMPRA_VENDA", "CD_OPERACAO", prodcompravenda.getCompravenda().getOperacao().getCodigo()));
        valida.validacamposCadastrar(jPanel1, PnBotoes);
        valida.validacamposCadastrar(jPanel3, PnBotoes);
        valida.validacamposCadastrar(jPanel4, PnBotoes);
        TfDescOperacao.setText(prodcompravenda.getCompravenda().getOperacao().getDescricao());
    }//GEN-LAST:event_BtIncluirActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar esta compra?\n"
                + "(Caso sim, TODOS os dados digitados serão limpos da tela)", "Deseja cancelar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpar.Limpar(jPanel1);
            limpar.Limpar(jPanel3);
            limpar.Limpar(jPanel4);
            limpar.Limpar(TbProdutos);
            limpar.Limpar(TbServicos);
            valida.validacamposCancelar(jPanel1, PnBotoes);
            valida.validacamposCancelar(jPanel3, PnBotoes);
            valida.validacamposCancelar(jPanel4, PnBotoes);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void TfQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfQuantidadeFocusLost
        
            estoqueok = false;
            if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
                ClasseMvtoEstoque estoque = new ClasseMvtoEstoque();
                estoque.getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
                if (Float.parseFloat(TfQuantidade.getValue().toString()) > estoque.retornaestoqueatual()) {
                    JOptionPane.showMessageDialog(null, "A quantidade digitada é maior que o estoque atual disponível deste produto!\nEstoque atual: " + estoque.retornaestoqueatual(), "Estoque indiponivel", JOptionPane.INFORMATION_MESSAGE);
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                } else {
                    estoqueok = true;
                }
            }
        
    }//GEN-LAST:event_TfQuantidadeFocusLost

    private void TfQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyTyped
        valida.limitemaximo(evt, TfQuantidade.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (PnBotoes.isVisible() && BtGravar.isEnabled()) {
            if (JOptionPane.showConfirmDialog(null, "Você está prestes a fechar esta janela.\nAo fechar esta janela tudo que você digitou será esquecido!", "Tem certeza que deseja fechar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void TfCodPessoaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodPessoaFocusLost
        if (TfPessoa.getText().equals("")) {
            TfCodPessoa.setText("");
        } else {
            if (CbPessoa.getSelectedItem().toString().equals("Fornecedor") && prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("E")) {
                prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodPessoa.getText()));
            }
        }
    }//GEN-LAST:event_TfCodPessoaFocusLost

    private void TfCodFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodFuncionarioFocusLost
        if (TfFuncionario.getText().equals("")) {
            TfCodFuncionario.setText("");
        }
    }//GEN-LAST:event_TfCodFuncionarioFocusLost

    private void TfCodServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodServicoKeyReleased
        if (!TfCodServico.getText().equals("")) {
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodServico.getText()));
            if (prodcompravenda.getForneproduto().getProduto().eprodutoativo() && prodcompravenda.getForneproduto().getProduto().eservico()) {
                if (CbPessoa.getSelectedItem().toString().equals("Fornecedor") && prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("E")){
                    if(!TfCodPessoa.getText().equals("") && !TfPessoa.getText().equals("")){
                        if(prodcompravenda.getForneproduto().produtodestefornecedor()){
                            TfServico.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                            TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                        }else{
                            TfServico.setText("");
                            TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                            msg.CampoNaoPreenchido(LbNotificacao, "Este serviço não pode ser adquirido com este fornecedor!");
                        }
                    } else{
                        msg.CampoNaoPreenchido(LbNotificacao, "Digite o Fornecedor para que o sistema busque os serviços apenas deste Fornecedor!");
                        limpar.Limpar(jPanel4);
                        TfCodPessoa.grabFocus();
                    }
                }else{
                    TfServico.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                    TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                }
            } else {
                TfServico.setText("");
                TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
            }
        } else {
            TfServico.setText("");
            TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
        }
    }//GEN-LAST:event_TfCodServicoKeyReleased

    private void BtPesqServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqServicoActionPerformed
        final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto(), "S");
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodServico.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodServicoKeyReleased(null);
                } else {
                    TfCodServico.setText("");
                    TfCodServicoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqServicoActionPerformed

    private void BtCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadServicoActionPerformed
        BtCadProdutoActionPerformed(evt);
    }//GEN-LAST:event_BtCadServicoActionPerformed

    private void TfQuantidadeServFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfQuantidadeServFocusLost
        estoqueok = true;
    }//GEN-LAST:event_TfQuantidadeServFocusLost

    private void TfQuantidadeServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeServKeyTyped
        valida.limitemaximo(evt, TfQuantidadeServ.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeServKeyTyped

    private void BtIncluirServicoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirServicoTabelaActionPerformed
        boolean inclui = true;
        TfQuantidadeServFocusLost(null);
        limpar.Limpar(TbProdutos);
        if (estoqueok) {
            if (!TfCodServico.getText().equals("") && !TfServico.getText().equals("")) {
                if (TfQuantidadeServ.getValue() != BigDecimal.valueOf(0)) {
                    for (int i = 0; i < TbServicos.getRowCount(); i++) {
                        if (Integer.parseInt(TbServicos.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodServico.getText())) {
                            inclui = false;
                            if (JOptionPane.showConfirmDialog(null, "Este serviço já foi adiconado!\n"
                                    + "Deseja substituir a quantidade deste serviço?", "Serviço adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                TbServicos.setValueAt(TfQuantidadeServ.getText(), i, 3);
                            }
                        }
                    }
                    if (inclui) {
                        DefaultTableModel tabela = (DefaultTableModel) TbServicos.getModel();
                        int linha = tabela.getRowCount();
                        tabela.setNumRows(linha + 1);
                        tabela.setValueAt(TfCodigo.getText(), linha, 0);
                        tabela.setValueAt(TfCodServico.getText(), linha, 1);
                        tabela.setValueAt(TfServico.getText(), linha, 2);
                        tabela.setValueAt(TfQuantidadeServ.getText(), linha, 3);
                    }
                    TfCodServico.setText("");
                    TfServico.setText("");
                    TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                } else {
                    msg.CampoNaoPreenchido(LbNotificacao, "Digite a quantidade corretamente!");
                }
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Informe o serviço a ser adicionado!");
                TfCodServico.grabFocus();
            }
        }
    }//GEN-LAST:event_BtIncluirServicoTabelaActionPerformed

    private void BtRemoverServicoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverServicoTabelaActionPerformed
        int linha = TbServicos.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este serviço da operação?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbServicos.getModel();
                tabela.removeRow(linha);
            }
        }
    }//GEN-LAST:event_BtRemoverServicoTabelaActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadFuncionario;
    private javax.swing.JButton BtCadPessoa;
    private javax.swing.JButton BtCadProduto;
    private javax.swing.JButton BtCadServico;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtIncluir;
    private javax.swing.JButton BtIncluirProdutoTabela;
    private javax.swing.JButton BtIncluirServicoTabela;
    private javax.swing.JButton BtPesqFuncionario;
    private javax.swing.JButton BtPesqPessoa;
    private javax.swing.JButton BtPesqProduto;
    private javax.swing.JButton BtPesqServico;
    private javax.swing.JButton BtRemoverProdutoTabela;
    private javax.swing.JButton BtRemoverServicoTabela;
    private javax.swing.JComboBox CbPessoa;
    private javax.swing.JLabel LbCodPessoa;
    private javax.swing.JLabel LbNomePessoa;
    private javax.swing.JLabel LbNotificacao;
    private javax.swing.JPanel PnBotoes;
    private javax.swing.JTable TbProdutos;
    private javax.swing.JTable TbServicos;
    private javax.swing.JTextField TfCodFuncionario;
    private javax.swing.JTextField TfCodPessoa;
    private javax.swing.JTextField TfCodProduto;
    private javax.swing.JTextField TfCodServico;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JFormattedTextField TfData;
    private javax.swing.JTextField TfDescOperacao;
    private javax.swing.JTextField TfFuncionario;
    private javax.swing.JTextField TfPessoa;
    private javax.swing.JTextField TfProduto;
    private JNumberField.JNumberField TfQuantidade;
    private JNumberField.JNumberField TfQuantidadeServ;
    private javax.swing.JTextField TfServico;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario() {
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            getTelasusuario().getTela().setCodigo(1);
            if (getTelasusuario().eadmintela()) {
                BtCadPessoa.setVisible(false);
            } else {
                BtCadPessoa.setVisible(true);
            }
        } else {
            getTelasusuario().getTela().setCodigo(2);
            if (getTelasusuario().eadmintela()) {
                BtCadPessoa.setVisible(false);
            } else {
                BtCadPessoa.setVisible(true);
            }
        }

        getTelasusuario().getTela().setCodigo(3);
        if (getTelasusuario().eadmintela()) {
            BtCadFuncionario.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(11);
        if (getTelasusuario().eadmintela()) {
            BtCadProduto.setVisible(false);
        }
    }

    public boolean camposobrigatoriospreenchidos() {
        if (TfDescOperacao.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite a descrição desta operação!");
            TfDescOperacao.grabFocus();
            return false;
        }
        if (TfCodFuncionario.getText().equals("") || TfFuncionario.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira o Funcionário que está realizando o antendimento nesta operaçao!");
            TfCodFuncionario.grabFocus();
            return false;
        }
        if (TfCodPessoa.getText().equals("") || TfPessoa.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira qual a pessoa envolvida nesta operação!");
            TfCodPessoa.grabFocus();
            return false;
        }
        if (TbProdutos.getRowCount() < 1 && TbServicos.getRowCount() < 1) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira os produtos ou serviços que fazem parte desta operação!");
            TfCodProduto.grabFocus();
            return false;
        }
        return true;
    }

    public void enviardados() {
        prodcompravenda.getCompravenda().setData(datas.retornadataehora());
        prodcompravenda.getCompravenda().setDescricao(prodcompravenda.getCompravenda().getOperacao().getDescricao() + " NRO. " + TfCodigo.getText() + " - " + TfDescOperacao.getText());
        prodcompravenda.getCompravenda().getCondicao().setCodigo(0);
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            cliente.setCodigo(Integer.parseInt(TfCodPessoa.getText()));
            prodcompravenda.getCompravenda().setCodigopessoa(cliente.retornacodigopessoacliente());
        } else {
            prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodPessoa.getText()));
            prodcompravenda.getCompravenda().setCodigopessoa(prodcompravenda.getForneproduto().getFornecedor().retornacodigopessoafornecedor());
        }
        prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
