package br.com.lojadafatima.InterfacesOperacoes;

import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseOperacoes;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceOperacoes extends javax.swing.JDialog {

    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    ClasseOperacoes operacao = new ClasseOperacoes();
    Preenche preenche = new Preenche();
    LimpaCamposTela limpar = new LimpaCamposTela();
    private java.awt.Frame primeiratela;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    MensagensUsuario msg = new MensagensUsuario();

    public InterfaceOperacoes(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super (telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(usuario);
        analisausuario();
        ChkEstoqueActionPerformed(null);
        ChkFinanceiroActionPerformed(null);
        int[] tam = new int[2];
        tam[0] = 70;
        tam[1] = 200;
        preenche.FormataJtable(TbOperacoes, tam);
        preenche.PreencherJtable(TbOperacoes, operacao.consultaoperacoes());
        TbOperacoes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        TfOperacao.setDocument(new NaoPermiteAspasSimples());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TfOperacao = new javax.swing.JTextField();
        ChkEstoque = new javax.swing.JCheckBox();
        RbEntEstoque = new javax.swing.JRadioButton();
        RbSaiEstoque = new javax.swing.JRadioButton();
        ChkFinanceiro = new javax.swing.JCheckBox();
        RbEntFinanceiro = new javax.swing.JRadioButton();
        RbSaiFinanceiro = new javax.swing.JRadioButton();
        BtGravar = new javax.swing.JButton();
        BtLimpar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbOperacoes = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        LbNotificacao = new javax.swing.JLabel();

        jMenuItem1.setText("Carregar dados");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodigo.setEnabled(false);
        jPanel1.add(TfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 70, -1));

        jLabel2.setText("Operação");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 11, -1, -1));

        TfOperacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfOperacaoKeyTyped(evt);
            }
        });
        jPanel1.add(TfOperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 31, 295, -1));

        ChkEstoque.setText("Modifica estoques de produtos");
        ChkEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(ChkEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 58, -1, -1));

        buttonGroup1.add(RbEntEstoque);
        RbEntEstoque.setSelected(true);
        RbEntEstoque.setText("Entrada no estoque");
        jPanel1.add(RbEntEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 81, -1, -1));

        buttonGroup1.add(RbSaiEstoque);
        RbSaiEstoque.setText("Saída no estoque");
        RbSaiEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RbSaiEstoqueActionPerformed(evt);
            }
        });
        jPanel1.add(RbSaiEstoque, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 104, -1, -1));

        ChkFinanceiro.setText("Modifica valores financeiros");
        ChkFinanceiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ChkFinanceiroActionPerformed(evt);
            }
        });
        jPanel1.add(ChkFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 58, -1, -1));

        buttonGroup2.add(RbEntFinanceiro);
        RbEntFinanceiro.setSelected(true);
        RbEntFinanceiro.setText("Entrada");
        jPanel1.add(RbEntFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 81, -1, -1));

        buttonGroup2.add(RbSaiFinanceiro);
        RbSaiFinanceiro.setText("Saída");
        jPanel1.add(RbSaiFinanceiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 104, -1, -1));

        BtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sucesso2.png"))); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });
        jPanel1.add(BtGravar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, 96, 35));

        BtLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtLimpar.setText("Limpar");
        BtLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtLimparActionPerformed(evt);
            }
        });
        jPanel1.add(BtLimpar, new org.netbeans.lib.awtextra.AbsoluteConstraints(112, 134, 90, 35));

        jLabel3.setText("Operações cadastradas:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        TbOperacoes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Operação"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbOperacoes.setComponentPopupMenu(jPopupMenu1);
        TbOperacoes.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbOperacoes);
        if (TbOperacoes.getColumnModel().getColumnCount() > 0) {
            TbOperacoes.getColumnModel().getColumn(0).setResizable(false);
            TbOperacoes.getColumnModel().getColumn(1).setResizable(false);
        }

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 200, 383, 160));

        LbNotificacao.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LbNotificacao)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacao)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 366, 383, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ChkEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkEstoqueActionPerformed
        if (ChkEstoque.isSelected()) {
            RbEntEstoque.setEnabled(true);
            RbSaiEstoque.setEnabled(true);
        } else {
            RbEntEstoque.setEnabled(false);
            RbSaiEstoque.setEnabled(false);
        }
    }//GEN-LAST:event_ChkEstoqueActionPerformed

    private void ChkFinanceiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ChkFinanceiroActionPerformed
        if (ChkFinanceiro.isSelected()) {
            RbEntFinanceiro.setEnabled(true);
            RbSaiFinanceiro.setEnabled(true);
        } else {
            RbEntFinanceiro.setEnabled(false);
            RbSaiFinanceiro.setEnabled(false);
        }
    }//GEN-LAST:event_ChkFinanceiroActionPerformed

    private void TfOperacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfOperacaoKeyTyped
        valida.limitemaximo(evt, TfOperacao.getText(), 50);
    }//GEN-LAST:event_TfOperacaoKeyTyped

    private void BtLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtLimparActionPerformed
        limpar.Limpar(jPanel1);
        ChkEstoqueActionPerformed(evt);
        ChkFinanceiroActionPerformed(evt);
    }//GEN-LAST:event_BtLimparActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (!TfOperacao.getText().equals("")) {
            if (!ChkEstoque.isSelected() && !ChkFinanceiro.isSelected()) {
                JOptionPane.showMessageDialog(null, "A operação deve fazer alguma modificação no sistema!", "Campos obrigatórios", JOptionPane.INFORMATION_MESSAGE);
            } else {
                if (JOptionPane.showConfirmDialog(null, "Deseja realmente gravar os dados desta operação?", "Deseja gravar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                    enviardados();
                    if (TfCodigo.getText().equals("")) {
                        if(operacao.incluir()){
                            msg.Sucesso(LbNotificacao, "Dados da Operação gravados com sucesso!");
                        }
                    } else {
                        operacao.setCodigo(Integer.parseInt(TfCodigo.getText()));
                        if(operacao.alterar()){
                            msg.Sucesso(LbNotificacao, "Dados da Operação alterados com sucesso!");
                        }
                    }
                    limpar.Limpar(jPanel1);
                    ChkEstoqueActionPerformed(evt);
                    ChkFinanceiroActionPerformed(evt);
                    preenche.PreencherJtable(TbOperacoes, operacao.consultaoperacoes());
                }
            }
        } else {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite um \"nome\" para a operação!");
            TfOperacao.grabFocus();
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        if(TbOperacoes.getSelectedRow() > 3){
            operacao.setCodigo(Integer.parseInt(TbOperacoes.getValueAt(TbOperacoes.getSelectedRow(), 0).toString()));
            operacao.retornaoperacao();
            TfCodigo.setText(""+operacao.getCodigo());
            TfOperacao.setText(operacao.getDescricao());
            if(operacao.getInestoque().equals("S")){
                ChkEstoque.setSelected(true);
                if(operacao.getTpestoque().equals("E")){
                    RbEntEstoque.setSelected(true);
                }else{
                    RbSaiEstoque.setSelected(true);
                }
            }else{
                ChkEstoque.setSelected(false);
            }
            if(operacao.getInfinanceiro().equals("S")){
                ChkFinanceiro.setSelected(true);
                if(operacao.getTpfinanceiro().equals("E")){
                    RbEntFinanceiro.setSelected(true);
                }else{
                    RbSaiFinanceiro.setSelected(true);
                }
            }else{
                ChkFinanceiro.setSelected(false);
            }
            ChkEstoqueActionPerformed(evt);
            ChkFinanceiroActionPerformed(evt);
            msg.StatusEditar(LbNotificacao, "Editando informações...");
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void RbSaiEstoqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RbSaiEstoqueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RbSaiEstoqueActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtLimpar;
    private javax.swing.JCheckBox ChkEstoque;
    private javax.swing.JCheckBox ChkFinanceiro;
    private javax.swing.JLabel LbNotificacao;
    private javax.swing.JRadioButton RbEntEstoque;
    private javax.swing.JRadioButton RbEntFinanceiro;
    private javax.swing.JRadioButton RbSaiEstoque;
    private javax.swing.JRadioButton RbSaiFinanceiro;
    private javax.swing.JTable TbOperacoes;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfOperacao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario(){
        getTelasusuario().getTela().setCodigo(10);
        if(!getTelasusuario().eadmintela()){
            BtGravar.setVisible(false);
        }
    }
    
    public void enviardados() {
        operacao.setDescricao(TfOperacao.getText());
        if (ChkEstoque.isSelected()) {
            operacao.setInestoque("S");
            if (RbEntEstoque.isSelected()) {
                operacao.setTpestoque("E");
            } else {
                operacao.setTpestoque("S");
            }
        } else {
            operacao.setInestoque("N");
            operacao.setTpestoque("N");
        }

        if (ChkFinanceiro.isSelected()) {
            operacao.setInfinanceiro("S");
            if (RbEntFinanceiro.isSelected()) {
                operacao.setTpfinanceiro("E");
            } else {
                operacao.setTpfinanceiro("S");
            }
        } else {
            operacao.setInfinanceiro("N");
            operacao.setTpfinanceiro("N");
        }
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }

}
