package br.com.lojadafatima.InterfacesOperacoes;

import br.com.lojadafatima.ClassesFerramentas.ClasseDatas;
import br.com.lojadafatima.ClassesFerramentas.GeraCodigos;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseProdutosCompraVenda;
import br.com.lojadafatima.ConexaoBDpostgre.ConexaoPostgre;
import br.com.lojadafatima.Financeiro.ClasseContasPagarReceber;
import br.com.lojadafatima.Financeiro.ClasseParcelas;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesCliente;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesCondicaoPgto;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFuncionario;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesProduto;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceCondicaoPagto;
import br.com.lojadafatima.InterfacesPessoa.InterfaceCliente;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFuncionario;
import br.com.lojadafatima.InterfacesProduto.InterfaceProduto;
import br.com.lojadafatima.Pessoa.ClasseCliente;
import br.com.lojadafatima.Produto.ClasseMvtoEstoque;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import java.math.BigDecimal;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceVenda extends javax.swing.JDialog {

    MaskFormatter data;
    MaskFormatter valor;
    private java.awt.Frame primeiratela;
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    ClasseProdutosCompraVenda prodcompravenda = new ClasseProdutosCompraVenda();
    ClasseDatas datas = new ClasseDatas();
    LimpaCamposTela limpar = new LimpaCamposTela();
    ClasseCliente cliente = new ClasseCliente();
    boolean estoqueok = false;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    ClasseParcelas parcelas = new ClasseParcelas();
    MensagensUsuario msg = new MensagensUsuario();

    /**
     * Creates new form InterfaceVenda
     */
    public InterfaceVenda(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(usuario);
        analisausuario();
        TfCodCliente.setDocument(new PermiteApenasNumeros());
        TfCodCondicaoPgto.setDocument(new PermiteApenasNumeros());
        TfCodFuncionario.setDocument(new PermiteApenasNumeros());
        TfCodProduto.setDocument(new PermiteApenasNumeros());
        TfCodServico.setDocument(new PermiteApenasNumeros());
        valida.validacamposCancelar(jPanel1, PnBotoes);
        valida.validacamposCancelar(jPanel3, PnBotoes);
        valida.validacamposCancelar(jPanel3, PnBotoes);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        TbVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel montar mascara no campo de Data");
        }
        TfData = new JFormattedTextField(data);
        jLabel3 = new javax.swing.JLabel();
        TfCodFuncionario = new javax.swing.JTextField();
        BtPesqFuncionario = new javax.swing.JButton();
        TfFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtCadFuncionario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TfCodCliente = new javax.swing.JTextField();
        BtPesqCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TfCliente = new javax.swing.JTextField();
        BtCadCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TfCodCondicaoPgto = new javax.swing.JTextField();
        BtPesqCondicaoPgto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TfCondicaoPgto = new javax.swing.JTextField();
        BtCadCondicaoPgto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        PnBotoes = new javax.swing.JPanel();
        BtGravar = new javax.swing.JButton();
        BtIncluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LbNotificacao = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TfCodProduto = new javax.swing.JTextField();
        BtPesqProduto = new javax.swing.JButton();
        TfProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtCadProduto = new javax.swing.JButton();
        TfValorProduto = new JNumberField.JNumberField();
        jLabel14 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        TfDesconto = new JNumberField.JNumberField(2);
        ;
        jLabel15 = new javax.swing.JLabel();
        TfValorUnitario = new JNumberField.JNumberField();
        jLabel12 = new javax.swing.JLabel();
        TfQuantidade = new JNumberField.JNumberField(2);
        ;
        jLabel11 = new javax.swing.JLabel();
        CbPromocao = new javax.swing.JCheckBox();
        BtIncluirProdutoVenda = new javax.swing.JButton();
        BtRemoverProdutoVenda = new javax.swing.JButton();
        TfValorTotalVenda = new JNumberField.JNumberField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbVenda = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        TfCodServico = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        TfQuantidadeServ = new JNumberField.JNumberField(2);
        ;
        CbPromocaoServ = new javax.swing.JCheckBox();
        BtIncluirServicoVenda = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbVendaServ = new javax.swing.JTable();
        BtRemoverServicoVenda = new javax.swing.JButton();
        TfValorUnitarioServ = new JNumberField.JNumberField();
        jLabel19 = new javax.swing.JLabel();
        BtPesqServico = new javax.swing.JButton();
        TfServico = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        BtCadServico = new javax.swing.JButton();
        TfDescontoServ = new JNumberField.JNumberField(2);
        ;
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        TfValorServ = new JNumberField.JNumberField();
        jLabel23 = new javax.swing.JLabel();
        TfValorTotalVendaServ = new JNumberField.JNumberField();
        jLabel24 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda - Software Loja da Fátima");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodigo.setEditable(false);
        jPanel1.add(TfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 111, -1));

        jLabel2.setText("Data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 11, -1, -1));

        TfData.setEditable(false);
        jPanel1.add(TfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(127, 31, 110, -1));

        jLabel3.setText("Cód. Funcionário");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        TfCodFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodFuncionarioFocusLost(evt);
            }
        });
        TfCodFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodFuncionarioKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 78, 130, -1));

        BtPesqFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 77, -1, -1));

        TfFuncionario.setEditable(false);
        jPanel1.add(TfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 78, 251, -1));

        jLabel4.setText("Funcionário");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 57, -1, -1));

        BtCadFuncionario.setText("Cadastrar Funcionário");
        BtCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 77, 199, -1));

        jLabel5.setText("Cód. Cliente");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 108, -1, -1));

        TfCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodClienteFocusLost(evt);
            }
        });
        TfCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodClienteKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 129, 130, -1));

        BtPesqCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 128, -1, -1));

        jLabel6.setText("Cliente");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 108, -1, -1));

        TfCliente.setEditable(false);
        jPanel1.add(TfCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 129, 251, -1));

        BtCadCliente.setText("Cadastrar Cliente");
        BtCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadClienteActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 128, 199, -1));

        jLabel7.setText("Cód. Condição de Pagamento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 159, -1, -1));

        TfCodCondicaoPgto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodCondicaoPgtoFocusLost(evt);
            }
        });
        TfCodCondicaoPgto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodCondicaoPgtoKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, 130, -1));

        BtPesqCondicaoPgto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqCondicaoPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqCondicaoPgtoActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 179, -1, -1));

        jLabel8.setText("Condição de Pagamento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 159, -1, -1));

        TfCondicaoPgto.setEditable(false);
        jPanel1.add(TfCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(201, 180, 251, -1));

        BtCadCondicaoPgto.setText("Cadastrar Condição de Pagamento");
        BtCadCondicaoPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadCondicaoPgtoActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(458, 179, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 215, 647, 10));

        BtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/salvar.png"))); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.setName("Gravar"); // NOI18N
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/carrinho.png"))); // NOI18N
        BtIncluir.setText("Nova Venda");
        BtIncluir.setName("Incluir"); // NOI18N
        BtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirActionPerformed(evt);
            }
        });

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/cancelar.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.setName("Cancelar"); // NOI18N
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotoesLayout = new javax.swing.GroupLayout(PnBotoes);
        PnBotoes.setLayout(PnBotoesLayout);
        PnBotoesLayout.setHorizontalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotoesLayout.createSequentialGroup()
                .addComponent(BtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnBotoesLayout.setVerticalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(BtGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(PnBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 542, 647, -1));

        LbNotificacao.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LbNotificacao)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacao)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 586, 647, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Cód. Produto");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodProdutoKeyReleased(evt);
            }
        });
        jPanel3.add(TfCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 130, -1));

        BtPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(BtPesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 31, -1, -1));

        TfProduto.setEditable(false);
        jPanel3.add(TfProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 32, 280, -1));

        jLabel10.setText("Produto");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 11, -1, -1));

        BtCadProduto.setText("Cadastrar Produto");
        BtCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(BtCadProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 31, 144, -1));

        TfValorProduto.setEditable(false);
        jPanel3.add(TfValorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 82, 96, -1));

        jLabel14.setText("Valor Total do Produto");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 62, -1, -1));

        jLabel13.setText("%");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 85, -1, -1));

        TfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfDescontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescontoKeyTyped(evt);
            }
        });
        jPanel3.add(TfDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 82, 86, -1));

        jLabel15.setText("Desconto");
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 62, -1, -1));

        TfValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfValorUnitarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfValorUnitarioKeyTyped(evt);
            }
        });
        jPanel3.add(TfValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 82, 98, -1));

        jLabel12.setText("Valor Unitário");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 62, -1, -1));

        TfQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfQuantidadeFocusLost(evt);
            }
        });
        TfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyTyped(evt);
            }
        });
        jPanel3.add(TfQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 99, -1));

        jLabel11.setText("Quantidade");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        CbPromocao.setText("Promoção");
        jPanel3.add(CbPromocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        BtIncluirProdutoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirProdutoVenda.setText("Incluir Produto na Venda");
        BtIncluirProdutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirProdutoVendaActionPerformed(evt);
            }
        });
        jPanel3.add(BtIncluirProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, -1, -1));

        BtRemoverProdutoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverProdutoVenda.setText("Remover Produto");
        BtRemoverProdutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverProdutoVendaActionPerformed(evt);
            }
        });
        jPanel3.add(BtRemoverProdutoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(187, 134, -1, -1));

        TfValorTotalVenda.setEditable(false);
        jPanel3.add(TfValorTotalVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 136, 99, -1));

        jLabel16.setText("Valor Total da Venda");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 113, -1, -1));

        TbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Venda", "Cód. Produto", "Produto", "Quantidade", "Valor Unitário", "Desconto", "Valor Total do Produto na Venda", "Promoção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbVenda);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 622, 106));

        jTabbedPane1.addTab("Produtos", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setText("Cód. Serviço");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodServicoKeyReleased(evt);
            }
        });
        jPanel4.add(TfCodServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 32, 130, -1));

        jLabel18.setText("Quantidade");
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        TfQuantidadeServ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfQuantidadeServFocusLost(evt);
            }
        });
        TfQuantidadeServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfQuantidadeServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeServKeyTyped(evt);
            }
        });
        jPanel4.add(TfQuantidadeServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 99, -1));

        CbPromocaoServ.setText("Promoção");
        jPanel4.add(CbPromocaoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        BtIncluirServicoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirServicoVenda.setText("Incluir Serviço na Venda");
        BtIncluirServicoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirServicoVendaActionPerformed(evt);
            }
        });
        jPanel4.add(BtIncluirServicoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, -1, -1));

        TbVendaServ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Venda", "Cód. Serviço", "Serviço", "Quantidade", "Valor Unitário", "Desconto", "Valor Total do Servico na Venda", "Promoção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbVendaServ.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TbVendaServ);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 622, 106));

        BtRemoverServicoVenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverServicoVenda.setText("Remover Serviço");
        BtRemoverServicoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverServicoVendaActionPerformed(evt);
            }
        });
        jPanel4.add(BtRemoverServicoVenda, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 134, -1, -1));

        TfValorUnitarioServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfValorUnitarioServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfValorUnitarioServKeyTyped(evt);
            }
        });
        jPanel4.add(TfValorUnitarioServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 82, 98, -1));

        jLabel19.setText("Valor Unitário");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(115, 62, -1, -1));

        BtPesqServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqServicoActionPerformed(evt);
            }
        });
        jPanel4.add(BtPesqServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(147, 31, -1, -1));

        TfServico.setEditable(false);
        jPanel4.add(TfServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 32, 280, -1));

        jLabel20.setText("Serviço");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 11, -1, -1));

        BtCadServico.setText("Cadastrar Serviço");
        BtCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadServicoActionPerformed(evt);
            }
        });
        jPanel4.add(BtCadServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(488, 31, 144, -1));

        TfDescontoServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfDescontoServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescontoServKeyTyped(evt);
            }
        });
        jPanel4.add(TfDescontoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 82, 86, -1));

        jLabel21.setText("%");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 85, -1, -1));

        jLabel22.setText("Desconto");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(223, 62, -1, -1));

        TfValorServ.setEditable(false);
        jPanel4.add(TfValorServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 82, 96, -1));

        jLabel23.setText("Valor Total do Serviço");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 62, -1, -1));

        TfValorTotalVendaServ.setEditable(false);
        jPanel4.add(TfValorTotalVendaServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 136, 99, -1));

        jLabel24.setText("Valor Total da Venda");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(518, 113, -1, -1));

        jTabbedPane1.addTab("Serviços", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 231, -1, 305));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadFuncionarioActionPerformed
        final InterfaceFuncionario tela = new InterfaceFuncionario(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadFuncionarioActionPerformed

    private void BtCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadClienteActionPerformed
        final InterfaceCliente tela = new InterfaceCliente(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadClienteActionPerformed

    private void BtCadCondicaoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadCondicaoPgtoActionPerformed
        final InterfaceCondicaoPagto tela = new InterfaceCondicaoPagto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadCondicaoPgtoActionPerformed

    private void TfCodFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFuncionarioKeyReleased
        if (!TfCodFuncionario.getText().equals("")) {
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
            if (prodcompravenda.getCompravenda().getFuncionario().efuncionarioativo()) {
                prodcompravenda.getCompravenda().getFuncionario().getPessoafis().getPessoa().setCodigo(prodcompravenda.getCompravenda().getFuncionario().retornacodigopessoafuncionario());
                TfFuncionario.setText(prodcompravenda.getCompravenda().getFuncionario().getPessoafis().retornanomeporCodigo());
            } else {
                TfFuncionario.setText("");
            }
        } else {
            TfFuncionario.setText("");
        }
    }//GEN-LAST:event_TfCodFuncionarioKeyReleased

    private void BtPesqFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFuncionarioActionPerformed
        final ConsulSimplesFuncionario tela = new ConsulSimplesFuncionario(getPrimeiratela(), true, prodcompravenda.getCompravenda().getFuncionario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getFuncionario().getCodigo() != 0) {
                    TfCodFuncionario.setText("" + prodcompravenda.getCompravenda().getFuncionario().getCodigo());
                    TfCodFuncionarioKeyReleased(null);
                } else {
                    TfCodFuncionario.setText("");
                    TfFuncionario.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqFuncionarioActionPerformed

    private void TfCodCondicaoPgtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodCondicaoPgtoKeyReleased
        if (!TfCodCondicaoPgto.getText().equals("")) {
            prodcompravenda.getCompravenda().getCondicao().setCodigo(Integer.parseInt(TfCodCondicaoPgto.getText()));
            TfCondicaoPgto.setText(prodcompravenda.getCompravenda().getCondicao().retornadescricaocondicao());
        } else {
            TfCondicaoPgto.setText("");
        }
    }//GEN-LAST:event_TfCodCondicaoPgtoKeyReleased

    private void BtPesqCondicaoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqCondicaoPgtoActionPerformed
        final ConsulSimplesCondicaoPgto tela = new ConsulSimplesCondicaoPgto(getPrimeiratela(), true, prodcompravenda.getCompravenda().getCondicao());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getCondicao().getCodigo() == 0) {
                    TfCodCondicaoPgto.setText("");
                } else {
                    TfCodCondicaoPgto.setText("" + prodcompravenda.getCompravenda().getCondicao().getCodigo());
                }
                TfCodCondicaoPgtoKeyReleased(null);
            }
        });
    }//GEN-LAST:event_BtPesqCondicaoPgtoActionPerformed

    private void TfCodProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodProdutoKeyReleased
        if (!TfCodProduto.getText().equals("")) {
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
            if (prodcompravenda.getForneproduto().getProduto().eprodutoativo() && !prodcompravenda.getForneproduto().getProduto().eservico()) {
                TfProduto.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                TfValorUnitario.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() + ((prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() * prodcompravenda.getForneproduto().getProduto().retornapercentuallucro())/100)));
                TfQuantidade.setValue(BigDecimal.valueOf(0));
                TfValorProduto.setValue(BigDecimal.valueOf(0));
            } else {
                TfProduto.setText("");
                TfValorUnitario.setValue(BigDecimal.valueOf(0));
                TfQuantidade.setValue(BigDecimal.valueOf(0));
                TfValorProduto.setValue(BigDecimal.valueOf(0));
            }
        } else {
            TfProduto.setText("");
            TfValorUnitario.setValue(BigDecimal.valueOf(0));
            TfQuantidade.setValue(BigDecimal.valueOf(0));
            TfValorProduto.setValue(BigDecimal.valueOf(0));
        }
    }//GEN-LAST:event_TfCodProdutoKeyReleased

    private void BtPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqProdutoActionPerformed
        final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto(), "P");
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodProduto.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodProdutoKeyReleased(null);
                } else {
                    TfCodProduto.setText("");
                    TfCodProdutoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqProdutoActionPerformed

    private void BtCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadProdutoActionPerformed
        final InterfaceProduto tela = new InterfaceProduto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadProdutoActionPerformed

    private void BtIncluirProdutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirProdutoVendaActionPerformed
        boolean inclui = true;
        TfQuantidadeFocusLost(null);
        limpar.Limpar(TbVendaServ);
        TfValorTotalVendaServ.setValue(BigDecimal.ZERO);
        if (estoqueok) {
            if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
                if (TfValorProduto.getValue() != BigDecimal.valueOf(0)) {
                    for (int i = 0; i < TbVenda.getRowCount(); i++) {
                        if (Integer.parseInt(TbVenda.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodProduto.getText())) {
                            inclui = false;
                            if (JOptionPane.showConfirmDialog(null, "Este produto já foi adiconado a esta venda!\n"
                                    + "Deseja substituir a quantidade adquirida deste produto?", "Produto adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                TbVenda.setValueAt(TfQuantidade.getText(), i, 3);
                                TbVenda.setValueAt(TfValorUnitario.getText(), i, 4);
                                TbVenda.setValueAt(TfDesconto.getText(), i, 5);
                                TbVenda.setValueAt(TfValorProduto.getText(), i, 6);
                                if (CbPromocao.isSelected()) TbVenda.setValueAt('S', i, 7);
                                else                         TbVenda.setValueAt('N', i, 7);
                            }
                        }
                    }
                    if (inclui) {
                        DefaultTableModel tabela = (DefaultTableModel) TbVenda.getModel();
                        int linha = tabela.getRowCount();
                        tabela.setNumRows(linha + 1);
                        tabela.setValueAt(TfCodigo.getText(), linha, 0);
                        tabela.setValueAt(TfCodProduto.getText(), linha, 1);
                        tabela.setValueAt(TfProduto.getText(), linha, 2);
                        tabela.setValueAt(TfQuantidade.getText(), linha, 3);
                        tabela.setValueAt(TfValorUnitario.getText(), linha, 4);
                        tabela.setValueAt(TfDesconto.getText(), linha, 5);
                        tabela.setValueAt(TfValorProduto.getText(), linha, 6);
                        if (CbPromocao.isSelected()) tabela.setValueAt('S', linha, 7);
                        else                         tabela.setValueAt('N', linha, 7);
                    }
                    TfCodProduto.setText("");
                    TfProduto.setText("");
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                    TfValorUnitario.setValue(BigDecimal.valueOf(0));
                    TfDesconto.setValue(BigDecimal.valueOf(0));
                    TfValorProduto.setValue(BigDecimal.valueOf(0));
                    CbPromocao.setSelected(false);
                    atualizavalortotal();
                } else {
                    msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do produto e a quantidade corretamente!");
                }
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Informe o produto a ser adicionado nesta venda!");
                TfCodProduto.grabFocus();
            }
        }
    }//GEN-LAST:event_BtIncluirProdutoVendaActionPerformed

    private void BtRemoverProdutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverProdutoVendaActionPerformed
        int linha = TbVenda.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este produto da venda?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbVenda.getModel();
                tabela.removeRow(linha);
                atualizavalortotal();
            }
        }
    }//GEN-LAST:event_BtRemoverProdutoVendaActionPerformed

    private void BtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirActionPerformed
        TfData.setText(datas.retornadataatual());
        GeraCodigos geracodigos = new GeraCodigos();
        TfCodigo.setText("" + geracodigos.gerasequencia("COMPRA_VENDA", "CD_COMPRA_VENDA", "CD_OPERACAO", 2));
        valida.validacamposCadastrar(jPanel1, PnBotoes);
        valida.validacamposCadastrar(jPanel3, PnBotoes);
        valida.validacamposCadastrar(jPanel4, PnBotoes);
    }//GEN-LAST:event_BtIncluirActionPerformed

    private void TfCodClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodClienteKeyReleased
        if (!TfCodCliente.getText().equals("")) {
            cliente.setCodigo(Integer.parseInt(TfCodCliente.getText()));
            if (cliente.eativo()) {
                TfCliente.setText(cliente.retornanomecliente());
            } else {
                TfCliente.setText("");
            }
        } else {
            TfCliente.setText("");
        }
    }//GEN-LAST:event_TfCodClienteKeyReleased

    private void BtPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqClienteActionPerformed
        final ConsulSimplesCliente tela = new ConsulSimplesCliente(getPrimeiratela(), true, cliente);
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (cliente.getCodigo() != 0) {
                    TfCodCliente.setText("" + cliente.getCodigo());
                    TfCodClienteKeyReleased(null);
                } else {
                    TfCodCliente.setText("");
                    TfCliente.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqClienteActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (camposobrigatoriospreenchidos()) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Gravar esta venda e de que todas as informações estão corretas?", "Deseja gravar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                enviardados();
                prodcompravenda.getCompravenda().incluir();

                ClasseMvtoEstoque mvestoque = new ClasseMvtoEstoque();
                mvestoque.setCompravenda(prodcompravenda.getCompravenda());
                mvestoque.setDtmvto(datas.retornadataehora());
                mvestoque.setTpmvto("S");
                
                if(TbVenda.getRowCount() > 0){
                    for (int i = 0; i < TbVenda.getRowCount(); i++) {
                        prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbVenda.getValueAt(i, 1).toString()));
                        TfQuantidade.setText(TbVenda.getValueAt(i, 3).toString());
                        prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidade.getValue().toString()));
                        TfValorUnitario.setText(TbVenda.getValueAt(i, 4).toString());
                        prodcompravenda.setValorunit(Float.parseFloat(TfValorUnitario.getValue().toString()));
                        TfDesconto.setText(TbVenda.getValueAt(i, 5).toString());
                        prodcompravenda.setDesconto(Float.parseFloat(TfDesconto.getValue().toString()));
                        TfValorProduto.setText(TbVenda.getValueAt(i, 6).toString());
                        prodcompravenda.setValorprodut(Float.parseFloat(TfValorProduto.getValue().toString()));
                        prodcompravenda.setPromocao(TbVenda.getValueAt(i, 7).toString());
                        prodcompravenda.incluirprodutocompravenda();

                        mvestoque.getProduto().setCodigo(Integer.parseInt(TbVenda.getValueAt(i, 1).toString()));
                        TfQuantidade.setText(TbVenda.getValueAt(i, 3).toString());
                        mvestoque.setQtmvto(Float.parseFloat(TfQuantidade.getValue().toString()));
                        mvestoque.incluirmvto();
                    }
                    parcelas.getConta().setTotal(Float.parseFloat(TfValorTotalVenda.getValue().toString()));
                } else if (TbVendaServ.getRowCount() > 0){
                    for (int i = 0; i < TbVendaServ.getRowCount(); i++) {
                        prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbVendaServ.getValueAt(i, 1).toString()));
                        TfQuantidadeServ.setText(TbVendaServ.getValueAt(i, 3).toString());
                        prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidadeServ.getValue().toString()));
                        TfValorUnitarioServ.setText(TbVendaServ.getValueAt(i, 4).toString());
                        prodcompravenda.setValorunit(Float.parseFloat(TfValorUnitarioServ.getValue().toString()));
                        TfDescontoServ.setText(TbVendaServ.getValueAt(i, 5).toString());
                        prodcompravenda.setDesconto(Float.parseFloat(TfDescontoServ.getValue().toString()));
                        TfValorServ.setText(TbVendaServ.getValueAt(i, 6).toString());
                        prodcompravenda.setValorprodut(Float.parseFloat(TfValorServ.getValue().toString()));
                        prodcompravenda.setPromocao(TbVendaServ.getValueAt(i, 7).toString());
                        prodcompravenda.incluirprodutocompravenda();
                    }
                    parcelas.getConta().setTotal(Float.parseFloat(TfValorTotalVendaServ.getValue().toString()));
                }
                
                parcelas.getConta().setCompravenda(prodcompravenda.getCompravenda());
                parcelas.getConta().setCondicao(prodcompravenda.getCompravenda().getCondicao());
                parcelas.getConta().setOperacao(prodcompravenda.getCompravenda().getOperacao());
                parcelas.getConta().setDescricao(prodcompravenda.getCompravenda().getDescricao());
                parcelas.getConta().setDtconta(TfData.getText());
                parcelas.getConta().setCodigopessoa(prodcompravenda.getCompravenda().getCodigopessoa());
                parcelas.getConta().incluir();

                parcelas.gerarparcelas();

                final InterfaceAjusteDatasEPrecos tela = new InterfaceAjusteDatasEPrecos(getPrimeiratela(), true, parcelas);
                tela.setVisible(true);
                tela.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosed(java.awt.event.WindowEvent evt) {
                        
                        HashMap filtro = new HashMap();
                        filtro.put("CD_COMPRA_VENDA", prodcompravenda.getCompravenda().getCodigo());
                        filtro.put("CD_OPERACAO", prodcompravenda.getCompravenda().getOperacao().getCodigo());
                        filtro.put("CD_CONTA", parcelas.getConta().getCodigo());
                        filtro.put("DS_NOTA", "EXTRATO DE VENDA");
                        filtro.put("TP_PESSOA", "Cliente:");
                        ConexaoPostgre conexao = new ConexaoPostgre();
                        JDialog dialog = new JDialog(new javax.swing.JFrame(), "Visualização - Software Loja da Fátima", true);
                        dialog.setSize(1000, 700);
                        dialog.setLocationRelativeTo(null);
                        try {
                            JasperPrint print = JasperFillManager.fillReport("relatorios\\notaoperacaoestoquefinanceiro.jasper", filtro, conexao.conecta());
                            
                            JasperViewer viewer = new JasperViewer(print, true);
                            dialog.getContentPane().add(viewer.getContentPane());
                            dialog.setVisible(true);
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                    }
                });

                limpar.Limpar(jPanel1);
                limpar.Limpar(jPanel3);
                limpar.Limpar(jPanel4);
                limpar.Limpar(TbVenda);
                limpar.Limpar(TbVendaServ);
                valida.validacamposCancelar(jPanel1, PnBotoes);
                valida.validacamposCancelar(jPanel3, PnBotoes);
                valida.validacamposCancelar(jPanel4, PnBotoes);
            }
        }
    }//GEN-LAST:event_BtGravarActionPerformed
        
    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar esta venda?\n"
                + "(Caso sim, TODOS os dados digitados serão limpos da tela)", "Deseja cancelar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpar.Limpar(jPanel1);
            limpar.Limpar(jPanel3);
            limpar.Limpar(jPanel4);
            limpar.Limpar(TbVenda);
            valida.validacamposCancelar(jPanel1, PnBotoes);
            valida.validacamposCancelar(jPanel3, PnBotoes);
            valida.validacamposCancelar(jPanel4, PnBotoes);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void TfQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyReleased
        if (TfDesconto.getValue() == BigDecimal.ZERO) TfValorProduto.setValue(TfQuantidade.getValue().multiply(TfValorUnitario.getValue()));
        else{
            TfValorProduto.setValue(TfQuantidade.getValue().multiply(TfValorUnitario.getValue()));
            TfValorProduto.setValue(TfValorProduto.getValue().subtract((TfValorProduto.getValue().multiply(TfDesconto.getValue())).divide(BigDecimal.valueOf(100))));
        }
    }//GEN-LAST:event_TfQuantidadeKeyReleased

    private void TfValorUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioKeyReleased
        TfQuantidadeKeyReleased(evt);
    }//GEN-LAST:event_TfValorUnitarioKeyReleased

    private void TfQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfQuantidadeFocusLost
        estoqueok = false;
        if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
            ClasseMvtoEstoque estoque = new ClasseMvtoEstoque();
            estoque.getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
            if (Float.parseFloat(TfQuantidade.getValue().toString()) > estoque.retornaestoqueatual()) {
                JOptionPane.showMessageDialog(null, "A quantidade digitada é maior que o estoque atual disponível deste produto!\nEstoque atual: " + estoque.retornaestoqueatual(), "Estoque indiponivel", JOptionPane.INFORMATION_MESSAGE);
                TfValorProduto.setValue(BigDecimal.valueOf(0));
            } else {
                estoqueok = true;
            }
        }
    }//GEN-LAST:event_TfQuantidadeFocusLost

    private void TfQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyTyped
        valida.limitemaximo(evt, TfQuantidade.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeKeyTyped

    private void TfValorUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioKeyTyped
        valida.limitemaximo(evt, TfValorUnitario.getText(), 13);
    }//GEN-LAST:event_TfValorUnitarioKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (PnBotoes.isVisible() && BtGravar.isEnabled()) {
            if (JOptionPane.showConfirmDialog(null, "Você está prestes a fechar esta janela.\nAo fechar esta janela, tudo que você digitou será esquecido!", "Tem certeza que deseja fechar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void TfCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodClienteFocusLost
        if (TfCliente.getText().equals("")) {
            TfCodCliente.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código do cliente corretamente!");
        } else {
            ClasseContasPagarReceber contas = new ClasseContasPagarReceber();
            cliente.setCodigo(Integer.parseInt(TfCodCliente.getText()));
            contas.setCodigopessoa(cliente.retornacodigopessoacliente());
            contas.setCodigopessoa(cliente.retornacodigopessoacliente());
            if (contas.epessoainadimplente()) {
                if (JOptionPane.showConfirmDialog(null, "Existem contas a receber em aberto ou vencidas desta pessoa, deseja continuar?", "Pessoa inadimplente", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
                    TfCodCliente.setText("");
                    TfCodClienteKeyReleased(null);
                }
            }
        }
    }//GEN-LAST:event_TfCodClienteFocusLost

    private void TfCodFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodFuncionarioFocusLost
        if (TfFuncionario.getText().equals("")) {
            TfCodFuncionario.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código do funcionário corretamente!");
        }else{
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
        }
    }//GEN-LAST:event_TfCodFuncionarioFocusLost

    private void TfCodCondicaoPgtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodCondicaoPgtoFocusLost
        if (TfCondicaoPgto.getText().equals("")) {
            TfCodCondicaoPgto.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código da condicao de pagamento corretamente!");
        }
    }//GEN-LAST:event_TfCodCondicaoPgtoFocusLost

    private void TfDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoKeyReleased
        if(TfValorUnitario.getValue() != BigDecimal.ZERO){
            if(TfQuantidade.getValue() != BigDecimal.ZERO){
                if(!TfCodFuncionario.getText().equals("") && !TfFuncionario.getText().equals("")){
                    if(prodcompravenda.getCompravenda().getFuncionario().percentmaxdesconto() >= Float.parseFloat(TfDesconto.getValue().toString())){
                        TfQuantidadeKeyReleased(evt);
                    }else{
                        msg.CampoNaoPreenchido(LbNotificacao, "Desconto digitado maior que o permitido!");
                        TfDesconto.setValue(BigDecimal.ZERO);
                    }
                }else{
                    msg.CampoNaoPreenchido(LbNotificacao, "Digite o funcionário para permitir desconto!");
                    TfDesconto.setValue(BigDecimal.ZERO);
                    TfCodFuncionario.grabFocus();
                }
            }else{
                msg.CampoNaoPreenchido(LbNotificacao, "Digite a quantidade do produto!");
                TfDesconto.setValue(BigDecimal.ZERO);
                TfQuantidade.grabFocus();
            }
        }else{
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitario do produto!");
            TfDesconto.setValue(BigDecimal.ZERO);
            TfValorUnitario.grabFocus();
        }
    }//GEN-LAST:event_TfDescontoKeyReleased

    private void TfCodServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodServicoKeyReleased
        if (!TfCodServico.getText().equals("")) {
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodServico.getText()));
            if (prodcompravenda.getForneproduto().getProduto().eprodutoativo() && prodcompravenda.getForneproduto().getProduto().eservico()) {
                TfServico.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                TfValorUnitarioServ.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() + ((prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() * prodcompravenda.getForneproduto().getProduto().retornapercentuallucro())/100)));
                TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                TfValorServ.setValue(BigDecimal.valueOf(0));
            } else {
                TfServico.setText("");
                TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
                TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                TfValorServ.setValue(BigDecimal.valueOf(0));
            }
        } else {
            TfServico.setText("");
            TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
            TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
            TfValorServ.setValue(BigDecimal.valueOf(0));
        }
    }//GEN-LAST:event_TfCodServicoKeyReleased

    private void TfQuantidadeServFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfQuantidadeServFocusLost
        estoqueok = true;
    }//GEN-LAST:event_TfQuantidadeServFocusLost

    private void TfQuantidadeServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeServKeyReleased
        if (TfDescontoServ.getValue() == BigDecimal.ZERO) TfValorServ.setValue(TfQuantidadeServ.getValue().multiply(TfValorUnitarioServ.getValue()));
        else{
            TfValorServ.setValue(TfQuantidadeServ.getValue().multiply(TfValorUnitarioServ.getValue()));
            TfValorServ.setValue(TfValorServ.getValue().subtract((TfValorServ.getValue().multiply(TfDescontoServ.getValue())).divide(BigDecimal.valueOf(100))));
        }
    }//GEN-LAST:event_TfQuantidadeServKeyReleased

    private void TfQuantidadeServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeServKeyTyped
        valida.limitemaximo(evt, TfQuantidadeServ.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeServKeyTyped

    private void BtIncluirServicoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirServicoVendaActionPerformed
        boolean inclui = true;
        TfQuantidadeServFocusLost(null);
        limpar.Limpar(TbVenda);
        TfValorTotalVenda.setValue(BigDecimal.ZERO);
        if (estoqueok) {
            if (!TfCodServico.getText().equals("") && !TfServico.getText().equals("")) {
                if (TfValorServ.getValue() != BigDecimal.valueOf(0)) {
                    for (int i = 0; i < TbVendaServ.getRowCount(); i++) {
                        if (Integer.parseInt(TbVendaServ.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodServico.getText())) {
                            inclui = false;
                            if (JOptionPane.showConfirmDialog(null, "Este serviço ja foi adiconado a esta venda!\n"
                                    + "Deseja substituir a quantidade adquirida deste serviço?", "Serviço adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                TbVendaServ.setValueAt(TfQuantidadeServ.getText(), i, 3);
                                TbVendaServ.setValueAt(TfValorUnitarioServ.getText(), i, 4);
                                TbVendaServ.setValueAt(TfDescontoServ.getText(), i, 5);
                                TbVendaServ.setValueAt(TfValorServ.getText(), i, 6);
                                if (CbPromocaoServ.isSelected()) TbVendaServ.setValueAt('S', i, 7);
                                else                         TbVendaServ.setValueAt('N', i, 7);
                            }
                        }
                    }
                    if (inclui) {
                        DefaultTableModel tabela = (DefaultTableModel) TbVendaServ.getModel();
                        int linha = tabela.getRowCount();
                        tabela.setNumRows(linha + 1);
                        tabela.setValueAt(TfCodigo.getText(), linha, 0);
                        tabela.setValueAt(TfCodServico.getText(), linha, 1);
                        tabela.setValueAt(TfServico.getText(), linha, 2);
                        tabela.setValueAt(TfQuantidadeServ.getText(), linha, 3);
                        tabela.setValueAt(TfValorUnitarioServ.getText(), linha, 4);
                        tabela.setValueAt(TfDescontoServ.getText(), linha, 5);
                        tabela.setValueAt(TfValorServ.getText(), linha, 6);
                        if (CbPromocaoServ.isSelected()) tabela.setValueAt('S', linha, 7);
                        else                         tabela.setValueAt('N', linha, 7);
                    }
                    TfCodServico.setText("");
                    TfServico.setText("");
                    TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                    TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
                    TfDescontoServ.setValue(BigDecimal.valueOf(0));
                    TfValorServ.setValue(BigDecimal.valueOf(0));
                    CbPromocaoServ.setSelected(false);
                    atualizavalortotalserv();
                } else {
                    msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do serviço e a quantidade corretamente!");
                }
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Informe o serviço a ser adicionado nesta venda!");
                TfCodServico.grabFocus();
            }
        }
    }//GEN-LAST:event_BtIncluirServicoVendaActionPerformed

    private void BtRemoverServicoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverServicoVendaActionPerformed
        int linha = TbVendaServ.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este serviço da venda?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbVendaServ.getModel();
                tabela.removeRow(linha);
                atualizavalortotalserv();
            }
        }
    }//GEN-LAST:event_BtRemoverServicoVendaActionPerformed

    private void TfValorUnitarioServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioServKeyReleased
        TfQuantidadeServKeyReleased(evt);
    }//GEN-LAST:event_TfValorUnitarioServKeyReleased

    private void TfValorUnitarioServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioServKeyTyped
        valida.limitemaximo(evt, TfValorUnitarioServ.getText(), 13);
    }//GEN-LAST:event_TfValorUnitarioServKeyTyped

    private void BtPesqServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqServicoActionPerformed
       final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto(), "S");
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodServico.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodServicoKeyReleased(null);
                } else {
                    TfCodServico.setText("");
                    TfCodServicoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqServicoActionPerformed

    private void BtCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadServicoActionPerformed
        BtCadProdutoActionPerformed(evt);
    }//GEN-LAST:event_BtCadServicoActionPerformed

    private void TfDescontoServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoServKeyReleased
        if(TfValorUnitarioServ.getValue() != BigDecimal.ZERO){
            if(TfQuantidadeServ.getValue() != BigDecimal.ZERO){
                if(!TfCodFuncionario.getText().equals("") && !TfFuncionario.getText().equals("")){
                    if(prodcompravenda.getCompravenda().getFuncionario().percentmaxdesconto() >= Float.parseFloat(TfDescontoServ.getValue().toString())){
                        TfQuantidadeServKeyReleased(evt);
                    }else{
                        msg.CampoNaoPreenchido(LbNotificacao, "Desconto digitado maior que o permitido!");
                        TfDescontoServ.setValue(BigDecimal.ZERO);
                    }
                }else{
                    msg.CampoNaoPreenchido(LbNotificacao, "Digite o funcionário para permitir desconto!");
                    TfDescontoServ.setValue(BigDecimal.ZERO);
                    TfCodFuncionario.grabFocus();
                }
            }else{
                msg.CampoNaoPreenchido(LbNotificacao, "Digite a quantidade do produto!");
                TfDescontoServ.setValue(BigDecimal.ZERO);
                TfQuantidadeServ.grabFocus();
            }
        }else{
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do produto!");
            TfDescontoServ.setValue(BigDecimal.ZERO);
            TfValorUnitarioServ.grabFocus();
        }
    }//GEN-LAST:event_TfDescontoServKeyReleased

    private void TfDescontoServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoServKeyTyped
        valida.limitemaximo(evt, TfDescontoServ.getText(), 10);
    }//GEN-LAST:event_TfDescontoServKeyTyped

    private void TfDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoKeyTyped
        valida.limitemaximo(evt, TfDescontoServ.getText(), 10);
    }//GEN-LAST:event_TfDescontoKeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadCliente;
    private javax.swing.JButton BtCadCondicaoPgto;
    private javax.swing.JButton BtCadFuncionario;
    private javax.swing.JButton BtCadProduto;
    private javax.swing.JButton BtCadServico;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtIncluir;
    private javax.swing.JButton BtIncluirProdutoVenda;
    private javax.swing.JButton BtIncluirServicoVenda;
    private javax.swing.JButton BtPesqCliente;
    private javax.swing.JButton BtPesqCondicaoPgto;
    private javax.swing.JButton BtPesqFuncionario;
    private javax.swing.JButton BtPesqProduto;
    private javax.swing.JButton BtPesqServico;
    private javax.swing.JButton BtRemoverProdutoVenda;
    private javax.swing.JButton BtRemoverServicoVenda;
    private javax.swing.JCheckBox CbPromocao;
    private javax.swing.JCheckBox CbPromocaoServ;
    private javax.swing.JLabel LbNotificacao;
    private javax.swing.JPanel PnBotoes;
    private javax.swing.JTable TbVenda;
    private javax.swing.JTable TbVendaServ;
    private javax.swing.JTextField TfCliente;
    private javax.swing.JTextField TfCodCliente;
    private javax.swing.JTextField TfCodCondicaoPgto;
    private javax.swing.JTextField TfCodFuncionario;
    private javax.swing.JTextField TfCodProduto;
    private javax.swing.JTextField TfCodServico;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfCondicaoPgto;
    private javax.swing.JFormattedTextField TfData;
    private JNumberField.JNumberField TfDesconto;
    private JNumberField.JNumberField TfDescontoServ;
    private javax.swing.JTextField TfFuncionario;
    private javax.swing.JTextField TfProduto;
    private JNumberField.JNumberField TfQuantidade;
    private JNumberField.JNumberField TfQuantidadeServ;
    private javax.swing.JTextField TfServico;
    private JNumberField.JNumberField TfValorProduto;
    private JNumberField.JNumberField TfValorServ;
    private JNumberField.JNumberField TfValorTotalVenda;
    private JNumberField.JNumberField TfValorTotalVendaServ;
    private JNumberField.JNumberField TfValorUnitario;
    private JNumberField.JNumberField TfValorUnitarioServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario() {
        getTelasusuario().getTela().setCodigo(16);
        if (!getTelasusuario().eadmintela()) {
            PnBotoes.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(1);
        if (!getTelasusuario().eadmintela()) {
            BtCadCliente.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(3);
        if (!getTelasusuario().eadmintela()) {
            BtCadFuncionario.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(11);
        if (!getTelasusuario().eadmintela()) {
            BtCadProduto.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(6);
        if (!getTelasusuario().eadmintela()) {
            BtCadCondicaoPgto.setVisible(false);
        }
    }

    public boolean camposobrigatoriospreenchidos() {
        if (TfCodFuncionario.getText().equals("") || TfFuncionario.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Informe qual funcionário realizou o atendimento nesta venda!");
            TfCodFuncionario.grabFocus();
            return false;
        }
        if (TfCodCliente.getText().equals("") || TfCliente.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Informe qual cliente está realizando a venda!");
            TfCodCliente.grabFocus();
            return false;
        }
        if (TfCodCondicaoPgto.getText().equals("") || TfCondicaoPgto.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Informe qual a condição de pagamento escolhida pelo cliente!");
            TfCodCondicaoPgto.grabFocus();
            return false;
        }
        if (TbVenda.getRowCount() == 0 && TbVendaServ.getRowCount() == 0) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira os produtos ou serviços desta venda!");
            TfCodProduto.grabFocus();
            return false;
        }
        return true;
    }

    public void enviardados() {
        prodcompravenda.getCompravenda().setData(datas.retornadataehora());
        prodcompravenda.getCompravenda().setDescricao("VENDA AO CLIENTE " + TfCliente.getText() +" - CÓDIGO DO SISTEMA: "+TfCodigo.getText());
        cliente.setCodigo(Integer.parseInt(TfCodCliente.getText()));
        prodcompravenda.getCompravenda().setCodigopessoa(cliente.retornacodigopessoacliente());
        prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
        prodcompravenda.getCompravenda().getOperacao().setCodigo(2);
    }

    public void atualizavalortotal() {
        float valor = 0;
        for (int i = 0; i < TbVenda.getRowCount(); i++) {
            TfValorTotalVenda.setText(TbVenda.getValueAt(i, 6).toString());
            valor = valor + Float.parseFloat(TfValorTotalVenda.getValue().toString());
        }
        TfValorTotalVenda.setValue(BigDecimal.valueOf(valor));
    }
    
    public void atualizavalortotalserv() {
        float valor = 0;
        for (int i = 0; i < TbVendaServ.getRowCount(); i++) {
            TfValorTotalVendaServ.setText(TbVendaServ.getValueAt(i, 6).toString());
            valor = valor + Float.parseFloat(TfValorTotalVendaServ.getValue().toString());
        }
        TfValorTotalVendaServ.setValue(BigDecimal.valueOf(valor));
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
