/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.lojadafatima.InterfacesOperacoes;

import br.com.lojadafatima.ClassesFerramentas.ClasseDatas;
import br.com.lojadafatima.ClassesFerramentas.GeraCodigos;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.ClassesFerramentas.Relatorios;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseProdutosCompraVenda;
import br.com.lojadafatima.ConexaoBDpostgre.ConexaoPostgre;
import br.com.lojadafatima.Financeiro.ClasseContasPagarReceber;
import br.com.lojadafatima.Financeiro.ClasseParcelas;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesCliente;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesCondicaoPgto;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFuncionario;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesProduto;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceCondicaoPagto;
import br.com.lojadafatima.InterfacesPessoa.InterfaceCliente;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFuncionario;
import br.com.lojadafatima.InterfacesProduto.InterfaceProduto;
import br.com.lojadafatima.Pessoa.ClasseCliente;
import br.com.lojadafatima.Produto.ClasseMvtoEstoque;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import java.math.BigDecimal;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author hp
 */
public class InterfaceVenda extends javax.swing.JDialog {

    MaskFormatter data;
    MaskFormatter valor;
    private java.awt.Frame primeiratela;
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    ClasseProdutosCompraVenda prodcompravenda = new ClasseProdutosCompraVenda();
    ClasseDatas datas = new ClasseDatas();
    LimpaCamposTela limpar = new LimpaCamposTela();
    ClasseCliente cliente = new ClasseCliente();
    boolean estoqueok = false;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    ClasseParcelas parcelas = new ClasseParcelas();
    MensagensUsuario msg = new MensagensUsuario();

    /**
     * Creates new form InterfaceVenda
     */
    public InterfaceVenda(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(usuario);
        analisausuario();
        TfCodCliente.setDocument(new PermiteApenasNumeros());
        TfCodCondicaoPgto.setDocument(new PermiteApenasNumeros());
        TfCodFuncionario.setDocument(new PermiteApenasNumeros());
        TfCodProduto.setDocument(new PermiteApenasNumeros());
        valida.validacamposCancelar(jPanel1, PnBotoes);
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        TbVenda.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        TfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel montar mascara no campo de Data");
        }
        TfData = new JFormattedTextField(data);
        jLabel3 = new javax.swing.JLabel();
        TfCodFuncionario = new javax.swing.JTextField();
        BtPesqFuncionario = new javax.swing.JButton();
        TfFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtCadFuncionario = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        TfCodCliente = new javax.swing.JTextField();
        BtPesqCliente = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        TfCliente = new javax.swing.JTextField();
        BtCadCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        TfCodCondicaoPgto = new javax.swing.JTextField();
        BtPesqCondicaoPgto = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TfCondicaoPgto = new javax.swing.JTextField();
        BtCadCondicaoPgto = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        TfCodProduto = new javax.swing.JTextField();
        BtPesqProduto = new javax.swing.JButton();
        TfProduto = new javax.swing.JTextField();
        BtCadProduto = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        BtIncluirProdutoVenda = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbVenda = new javax.swing.JTable();
        BtRemoverProdutoVenda = new javax.swing.JButton();
        PnBotoes = new javax.swing.JPanel();
        BtGravar = new javax.swing.JButton();
        BtIncluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        TfQuantidade = new JNumberField.JNumberField(2);
        ;
        TfValorUnitario = new JNumberField.JNumberField();
        TfValorProduto = new JNumberField.JNumberField();
        TfValorTotalVenda = new JNumberField.JNumberField();
        jLabel13 = new javax.swing.JLabel();
        TfDesconto = new JNumberField.JNumberField(2);
        ;
        jLabel15 = new javax.swing.JLabel();
        CbPromocao = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Venda - Software Loja da Fátima");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setText("Código");

        TfCodigo.setEditable(false);

        jLabel2.setText("Data");

        TfData.setEditable(false);

        jLabel3.setText("Cód. Funcionário");

        TfCodFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodFuncionarioFocusLost(evt);
            }
        });
        TfCodFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodFuncionarioKeyReleased(evt);
            }
        });

        BtPesqFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFuncionarioActionPerformed(evt);
            }
        });

        TfFuncionario.setEditable(false);

        jLabel4.setText("Funcionário");

        BtCadFuncionario.setText("Cadastrar Funcionário");
        BtCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadFuncionarioActionPerformed(evt);
            }
        });

        jLabel5.setText("Cód. Cliente");

        TfCodCliente.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodClienteFocusLost(evt);
            }
        });
        TfCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodClienteKeyReleased(evt);
            }
        });

        BtPesqCliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqClienteActionPerformed(evt);
            }
        });

        jLabel6.setText("Cliente");

        TfCliente.setEditable(false);

        BtCadCliente.setText("Cadastrar Cliente");
        BtCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadClienteActionPerformed(evt);
            }
        });

        jLabel7.setText("Cód. Condicao de Pagamento");

        TfCodCondicaoPgto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodCondicaoPgtoFocusLost(evt);
            }
        });
        TfCodCondicaoPgto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodCondicaoPgtoKeyReleased(evt);
            }
        });

        BtPesqCondicaoPgto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqCondicaoPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqCondicaoPgtoActionPerformed(evt);
            }
        });

        jLabel8.setText("Condicao de Pagamento");

        TfCondicaoPgto.setEditable(false);

        BtCadCondicaoPgto.setText("Cadastrar Condicao de Pagamento");
        BtCadCondicaoPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadCondicaoPgtoActionPerformed(evt);
            }
        });

        jLabel9.setText("Cód. Produto");

        TfCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodProdutoKeyReleased(evt);
            }
        });

        BtPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqProdutoActionPerformed(evt);
            }
        });

        TfProduto.setEditable(false);

        BtCadProduto.setText("Cadastrar Produto");
        BtCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadProdutoActionPerformed(evt);
            }
        });

        jLabel10.setText("Produto");

        jLabel11.setText("Quantidade");

        jLabel12.setText("Valor Unitário");

        jLabel14.setText("Valor Total do Produto");

        jLabel16.setText("Valor Total da Venda");

        BtIncluirProdutoVenda.setText("Incluir Produto na Venda");
        BtIncluirProdutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirProdutoVendaActionPerformed(evt);
            }
        });

        TbVenda.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Venda", "Cód. Produto", "Produto", "Quantidade", "Valor Unitário", "Valor Total do Produto na Venda"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbVenda.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbVenda);
        if (TbVenda.getColumnModel().getColumnCount() > 0) {
            TbVenda.getColumnModel().getColumn(1).setResizable(false);
        }

        BtRemoverProdutoVenda.setText("Remover Produto");
        BtRemoverProdutoVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverProdutoVendaActionPerformed(evt);
            }
        });

        BtGravar.setText("Gravar");
        BtGravar.setName("Gravar"); // NOI18N
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtIncluir.setText("Nova Venda");
        BtIncluir.setName("Incluir"); // NOI18N
        BtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirActionPerformed(evt);
            }
        });

        BtCancelar.setText("Cancelar");
        BtCancelar.setName("Cancelar"); // NOI18N
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotoesLayout = new javax.swing.GroupLayout(PnBotoes);
        PnBotoes.setLayout(PnBotoesLayout);
        PnBotoesLayout.setHorizontalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotoesLayout.createSequentialGroup()
                .addComponent(BtIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnBotoesLayout.setVerticalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(BtGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        TfQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfQuantidadeFocusLost(evt);
            }
        });
        TfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyTyped(evt);
            }
        });

        TfValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfValorUnitarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfValorUnitarioKeyTyped(evt);
            }
        });

        TfValorProduto.setEditable(false);

        TfValorTotalVenda.setEditable(false);

        jLabel13.setText("%");

        TfDesconto.setEditable(false);
        TfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfDescontoKeyReleased(evt);
            }
        });

        jLabel15.setText("Desconto");

        CbPromocao.setText("Promocao");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TfCodFuncionario, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                                    .addComponent(TfCodCliente))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(BtPesqCliente)
                                    .addComponent(BtPesqFuncionario)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfCodCondicaoPgto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtPesqCondicaoPgto)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BtCadFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfCondicaoPgto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtCadCondicaoPgto))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfCliente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtCadCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfFuncionario)
                                .addGap(205, 205, 205))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55)
                                .addComponent(jLabel2))
                            .addComponent(jLabel3)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel12)
                                    .addComponent(TfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(TfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(13, 13, 13)
                                        .addComponent(jLabel4))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(14, 14, 14)
                                        .addComponent(jLabel10)))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel16)
                                    .addComponent(TfValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15))))
                    .addComponent(jScrollPane1)
                    .addComponent(PnBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CbPromocao)
                            .addComponent(jLabel11)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtIncluirProdutoVenda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtRemoverProdutoVenda))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TfData, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(BtPesqProduto)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(TfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(TfValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(TfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtCadProduto, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(168, 168, 168)
                                .addComponent(jLabel14)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCodFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesqFuncionario)
                    .addComponent(TfFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCadFuncionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesqCliente)
                    .addComponent(TfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCadCliente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCodCondicaoPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesqCondicaoPgto)
                    .addComponent(TfCondicaoPgto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCadCondicaoPgto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfCodProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesqProduto)
                    .addComponent(TfProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtCadProduto))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel12)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TfQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfValorUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfValorProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbPromocao)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtIncluirProdutoVenda)
                    .addComponent(BtRemoverProdutoVenda)
                    .addComponent(TfValorTotalVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PnBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadFuncionarioActionPerformed
        final InterfaceFuncionario tela = new InterfaceFuncionario(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadFuncionarioActionPerformed

    private void BtCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadClienteActionPerformed
        final InterfaceCliente tela = new InterfaceCliente(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadClienteActionPerformed

    private void BtCadCondicaoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadCondicaoPgtoActionPerformed
        final InterfaceCondicaoPagto tela = new InterfaceCondicaoPagto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadCondicaoPgtoActionPerformed

    private void TfCodFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFuncionarioKeyReleased
        if (!TfCodFuncionario.getText().equals("")) {
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
            if (prodcompravenda.getCompravenda().getFuncionario().efuncionarioativo()) {
                prodcompravenda.getCompravenda().getFuncionario().getPessoafis().getPessoa().setCodigo(prodcompravenda.getCompravenda().getFuncionario().retornacodigopessoafuncionario());
                TfFuncionario.setText(prodcompravenda.getCompravenda().getFuncionario().getPessoafis().retornanomeporCodigo());
            } else {
                TfFuncionario.setText("");
            }
        } else {
            TfFuncionario.setText("");
        }
    }//GEN-LAST:event_TfCodFuncionarioKeyReleased

    private void BtPesqFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFuncionarioActionPerformed
        final ConsulSimplesFuncionario tela = new ConsulSimplesFuncionario(getPrimeiratela(), true, prodcompravenda.getCompravenda().getFuncionario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getFuncionario().getCodigo() != 0) {
                    TfCodFuncionario.setText("" + prodcompravenda.getCompravenda().getFuncionario().getCodigo());
                    TfCodFuncionarioKeyReleased(null);
                } else {
                    TfCodFuncionario.setText("");
                    TfFuncionario.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqFuncionarioActionPerformed

    private void TfCodCondicaoPgtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodCondicaoPgtoKeyReleased
        if (!TfCodCondicaoPgto.getText().equals("")) {
            prodcompravenda.getCompravenda().getCondicao().setCodigo(Integer.parseInt(TfCodCondicaoPgto.getText()));
            TfCondicaoPgto.setText(prodcompravenda.getCompravenda().getCondicao().retornadescricaocondicao());
        } else {
            TfCondicaoPgto.setText("");
        }
    }//GEN-LAST:event_TfCodCondicaoPgtoKeyReleased

    private void BtPesqCondicaoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqCondicaoPgtoActionPerformed
        final ConsulSimplesCondicaoPgto tela = new ConsulSimplesCondicaoPgto(getPrimeiratela(), true, prodcompravenda.getCompravenda().getCondicao());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getCondicao().getCodigo() == 0) {
                    TfCodCondicaoPgto.setText("");
                } else {
                    TfCodCondicaoPgto.setText("" + prodcompravenda.getCompravenda().getCondicao().getCodigo());
                }
                TfCodCondicaoPgtoKeyReleased(null);
            }
        });
    }//GEN-LAST:event_BtPesqCondicaoPgtoActionPerformed

    private void TfCodProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodProdutoKeyReleased
        if (!TfCodProduto.getText().equals("")) {
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
            if (prodcompravenda.getForneproduto().getProduto().eprodutoativo()) {
                TfProduto.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                TfValorUnitario.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() + ((prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() * prodcompravenda.getForneproduto().getProduto().retornapercentuallucro())/100)));
                TfQuantidade.setValue(BigDecimal.valueOf(0));
                TfValorProduto.setValue(BigDecimal.valueOf(0));
            } else {
                TfProduto.setText("");
                TfValorUnitario.setValue(BigDecimal.valueOf(0));
                TfQuantidade.setValue(BigDecimal.valueOf(0));
                TfValorProduto.setValue(BigDecimal.valueOf(0));
            }
        } else {
            TfProduto.setText("");
            TfValorUnitario.setValue(BigDecimal.valueOf(0));
            TfQuantidade.setValue(BigDecimal.valueOf(0));
            TfValorProduto.setValue(BigDecimal.valueOf(0));
        }
    }//GEN-LAST:event_TfCodProdutoKeyReleased

    private void BtPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqProdutoActionPerformed
        final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodProduto.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodProdutoKeyReleased(null);
                } else {
                    TfCodProduto.setText("");
                    TfCodProdutoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqProdutoActionPerformed

    private void BtCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadProdutoActionPerformed
        final InterfaceProduto tela = new InterfaceProduto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadProdutoActionPerformed

    private void BtIncluirProdutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirProdutoVendaActionPerformed
        boolean inclui = true;
        TfQuantidadeFocusLost(null);
        if (estoqueok) {
            if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
                if (TfValorProduto.getValue() != BigDecimal.valueOf(0)) {
                    for (int i = 0; i < TbVenda.getRowCount(); i++) {
                        if (Integer.parseInt(TbVenda.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodProduto.getText())) {
                            inclui = false;
                            if (JOptionPane.showConfirmDialog(null, "Este produto ja foi adiconado a esta venda!\n"
                                    + "Deseja substituir a quantidade adquirida deste produto?", "Produto adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                TbVenda.setValueAt(TfQuantidade.getText(), i, 3);
                                TbVenda.setValueAt(TfValorUnitario.getText(), i, 4);
                                TbVenda.setValueAt(TfValorProduto.getText(), i, 5);
                            }
                        }
                    }
                    if (inclui) {
                        DefaultTableModel tabela = (DefaultTableModel) TbVenda.getModel();
                        int linha = tabela.getRowCount();
                        tabela.setNumRows(linha + 1);
                        tabela.setValueAt(TfCodigo.getText(), linha, 0);
                        tabela.setValueAt(TfCodProduto.getText(), linha, 1);
                        tabela.setValueAt(TfProduto.getText(), linha, 2);
                        tabela.setValueAt(TfQuantidade.getText(), linha, 3);
                        tabela.setValueAt(TfValorUnitario.getText(), linha, 4);
                        tabela.setValueAt(TfValorProduto.getText(), linha, 5);
                    }
                    TfCodProduto.setText("");
                    TfProduto.setText("");
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                    TfValorUnitario.setValue(BigDecimal.valueOf(0));
                    TfValorProduto.setValue(BigDecimal.valueOf(0));
                    atualizavalortotal();
                } else {
                    JOptionPane.showMessageDialog(null, "Digite o valor unitario do produto e a quantidade corretamente!", "Informe os valores corretamente!", JOptionPane.INFORMATION_MESSAGE);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Informe o produto a ser adicionado nesta compra!", "Informe o produto", JOptionPane.INFORMATION_MESSAGE);
                TfCodProduto.grabFocus();
            }
        }
    }//GEN-LAST:event_BtIncluirProdutoVendaActionPerformed

    private void BtRemoverProdutoVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverProdutoVendaActionPerformed
        int linha = TbVenda.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este produto da venda?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbVenda.getModel();
                tabela.removeRow(linha);
                atualizavalortotal();
            }
        }
    }//GEN-LAST:event_BtRemoverProdutoVendaActionPerformed

    private void BtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirActionPerformed
        TfData.setText(datas.retornaratartual());
        GeraCodigos geracodigos = new GeraCodigos();
        TfCodigo.setText("" + geracodigos.gerasequencia("COMPRA_VENDA", "CD_COMPRA_VENDA", "CD_OPERACAO", 2));
        valida.validacamposCadastrar(jPanel1, PnBotoes);
    }//GEN-LAST:event_BtIncluirActionPerformed

    private void TfCodClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodClienteKeyReleased
        if (!TfCodCliente.getText().equals("")) {
            cliente.setCodigo(Integer.parseInt(TfCodCliente.getText()));
            if (cliente.eativo()) {
                TfCliente.setText(cliente.retornanomecliente());
            } else {
                TfCliente.setText("");
            }
        } else {
            TfCliente.setText("");
        }
    }//GEN-LAST:event_TfCodClienteKeyReleased

    private void BtPesqClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqClienteActionPerformed
        final ConsulSimplesCliente tela = new ConsulSimplesCliente(getPrimeiratela(), true, cliente);
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (cliente.getCodigo() != 0) {
                    TfCodCliente.setText("" + cliente.getCodigo());
                    TfCodClienteKeyReleased(null);
                } else {
                    TfCodCliente.setText("");
                    TfCliente.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqClienteActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (camposobrigatoriospreenchidos()) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Gravar esta venda e de que todas as informacoes estao corretas?", "Deseja gravar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                enviardados();
                prodcompravenda.getCompravenda().incluir();

                ClasseMvtoEstoque mvestoque = new ClasseMvtoEstoque();
                mvestoque.setCompravenda(prodcompravenda.getCompravenda());
                mvestoque.setDtmvto(datas.retornadataehora());
                mvestoque.setTpmvto("S");
                for (int i = 0; i < TbVenda.getRowCount(); i++) {
                    prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbVenda.getValueAt(i, 1).toString()));
                    TfQuantidade.setText(TbVenda.getValueAt(i, 3).toString());
                    prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidade.getValue().toString()));
                    TfValorUnitario.setText(TbVenda.getValueAt(i, 4).toString());
                    prodcompravenda.setValorunit(Float.parseFloat(TfValorUnitario.getValue().toString()));
                    TfValorProduto.setText(TbVenda.getValueAt(i, 5).toString());
                    prodcompravenda.setValorprodut(Float.parseFloat(TfValorProduto.getValue().toString()));
                    prodcompravenda.incluirprodutocompravenda();

                    mvestoque.getProduto().setCodigo(Integer.parseInt(TbVenda.getValueAt(i, 1).toString()));
                    TfQuantidade.setText(TbVenda.getValueAt(i, 3).toString());
                    mvestoque.setQtmvto(Float.parseFloat(TfQuantidade.getValue().toString()));
                    mvestoque.incluirmvto();
                }
                parcelas.getConta().setCompravenda(prodcompravenda.getCompravenda());
                parcelas.getConta().setCondicao(prodcompravenda.getCompravenda().getCondicao());
                parcelas.getConta().setOperacao(prodcompravenda.getCompravenda().getOperacao());
                parcelas.getConta().setDescricao(prodcompravenda.getCompravenda().getDescricao());
                parcelas.getConta().setDtconta(TfData.getText());
                parcelas.getConta().setTotal(Float.parseFloat(TfValorTotalVenda.getValue().toString()));
                parcelas.getConta().setCodigopessoa(prodcompravenda.getCompravenda().getCodigopessoa());
                parcelas.getConta().incluir();

                parcelas.gerarparcelas();

                final InterfaceAjusteDatasEPrecos tela = new InterfaceAjusteDatasEPrecos(getPrimeiratela(), true, parcelas);
                tela.setVisible(true);
                tela.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosed(java.awt.event.WindowEvent evt) {
//                        Relatorios rel = new Relatorios();
//                        Map par = new HashMap();
//                        par.put("$P{SUBREPORT_DIR}", "relatorios\\");
//                        par.put("$P{CD_COMPRA_VENDA}", prodcompravenda.getCompravenda().getCodigo());
//                        par.put("$P{CD_OPERACAO}", prodcompravenda.getCompravenda().getOperacao().getCodigo());
//                        par.put("$P{CD_CONTA}", parcelas.getConta().getCodigo());
//                        par.put("$P{PESSOA}", TfCliente.getText());
//                        par.put("$P{FUNCIONARIO}", TfFuncionario.getText());
//                        par.put("$P{CONDICAO}", TfCondicaoPgto.getText());
//                        try {
//                            Connection conn = DriverManager.getConnection("jdbc:postgresql://localhost:5432/lojafatima", "lojafatima", "lojafatima");
//                            par.put("$P{REPORT_CONNECTION}", conn);
//                            rel.iniciarSplash(prodcompravenda.getCompravenda().getOperacao().operacaorelatorio(), "relatorios\\notaoperacaoestoquefinanceiro.jasper",  par);
//                        } catch (SQLException ex) {
//                            
//                        }
                    }
                });

                limpar.Limpar(jPanel1);
                limpar.Limpar(TbVenda);
                valida.validacamposCancelar(jPanel1, PnBotoes);
            }
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar esta venda?\n"
                + "(Caso sim, TODOS os dados digitados serao limpos da tela)", "Deseja cancelar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpar.Limpar(jPanel1);
            limpar.Limpar(TbVenda);
            valida.validacamposCancelar(jPanel1, PnBotoes);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void TfQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyReleased
        TfValorProduto.setValue(TfQuantidade.getValue().multiply(TfValorUnitario.getValue()));
    }//GEN-LAST:event_TfQuantidadeKeyReleased

    private void TfValorUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioKeyReleased
        TfQuantidadeKeyReleased(evt);
    }//GEN-LAST:event_TfValorUnitarioKeyReleased

    private void TfQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfQuantidadeFocusLost
        estoqueok = false;
        if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
            ClasseMvtoEstoque estoque = new ClasseMvtoEstoque();
            estoque.getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
            if (Float.parseFloat(TfQuantidade.getValue().toString()) > estoque.retornaestoqueatual()) {
                JOptionPane.showMessageDialog(null, "A quantidade digitada e maior que o estoque atual disponivel deste produto!\nEstoque atual: " + estoque.retornaestoqueatual(), "Estoque indiponivel", JOptionPane.INFORMATION_MESSAGE);
                TfValorProduto.setValue(BigDecimal.valueOf(0));
            } else {
                estoqueok = true;
            }
        }
    }//GEN-LAST:event_TfQuantidadeFocusLost

    private void TfQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyTyped
        valida.limitemaximo(evt, TfQuantidade.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeKeyTyped

    private void TfValorUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioKeyTyped
        valida.limitemaximo(evt, TfValorUnitario.getText(), 13);
    }//GEN-LAST:event_TfValorUnitarioKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (PnBotoes.isVisible() && BtGravar.isEnabled()) {
            if (JOptionPane.showConfirmDialog(null, "Voce esta prestes a fechar esta janela.\nAo fechar esta janela tudo que voce digitou sera esquecido!", "Tem certeza que deseja fechar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void TfCodClienteFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodClienteFocusLost
        if (TfCliente.getText().equals("")) {
            TfCodCliente.setText("");
            JOptionPane.showMessageDialog(null, "Digite o codigo do cliente corretamente!", "Codigo inesxistente", JOptionPane.INFORMATION_MESSAGE);
        } else {
            ClasseContasPagarReceber contas = new ClasseContasPagarReceber();
            cliente.setCodigo(Integer.parseInt(TfCodCliente.getText()));
            contas.setCodigopessoa(cliente.retornacodigopessoacliente());
            contas.setCodigopessoa(cliente.retornacodigopessoacliente());
            if (contas.epessoainadimplente()) {
                if (JOptionPane.showConfirmDialog(null, "Existem contas a receber em aberto ou vencidas desta pessoa, deseja continuar?", "Pessoa inadimplente", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
                    TfCodCliente.setText("");
                    TfCodClienteKeyReleased(null);
                }
            }
        }
    }//GEN-LAST:event_TfCodClienteFocusLost

    private void TfCodFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodFuncionarioFocusLost
        if (TfFuncionario.getText().equals("")) {
            TfCodFuncionario.setText("");
            JOptionPane.showMessageDialog(null, "Digite o codigo do funcionario corretamente!", "Codigo inesxistente", JOptionPane.INFORMATION_MESSAGE);
        }else{
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
            if(prodcompravenda.getCompravenda().getFuncionario().percentmaxdesconto() > 0){
                TfDesconto.setEditable(true);
            }else{
                TfDesconto.setEditable(false);
            }
        }
    }//GEN-LAST:event_TfCodFuncionarioFocusLost

    private void TfCodCondicaoPgtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodCondicaoPgtoFocusLost
        if (TfCondicaoPgto.getText().equals("")) {
            TfCodCondicaoPgto.setText("");
            JOptionPane.showMessageDialog(null, "Digite o codigo da condicao de pagamento corretamente!", "Codigo inesxistente", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_TfCodCondicaoPgtoFocusLost

    private void TfDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoKeyReleased
        if(TfValorTotalVenda.getValue() != BigDecimal.valueOf(0)){
            float valorcomdesconto;
            valorcomdesconto = Float.parseFloat(TfValorTotalVenda.getValue().toString()) + ((Float.parseFloat(TfValorTotalVenda.getValue().toString()) * prodcompravenda.getCompravenda().getFuncionario().percentmaxdesconto())/ 100);
            TfValorTotalVenda.setValue(BigDecimal.valueOf(valorcomdesconto));
        }
    }//GEN-LAST:event_TfDescontoKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadCliente;
    private javax.swing.JButton BtCadCondicaoPgto;
    private javax.swing.JButton BtCadFuncionario;
    private javax.swing.JButton BtCadProduto;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtIncluir;
    private javax.swing.JButton BtIncluirProdutoVenda;
    private javax.swing.JButton BtPesqCliente;
    private javax.swing.JButton BtPesqCondicaoPgto;
    private javax.swing.JButton BtPesqFuncionario;
    private javax.swing.JButton BtPesqProduto;
    private javax.swing.JButton BtRemoverProdutoVenda;
    private javax.swing.JCheckBox CbPromocao;
    private javax.swing.JPanel PnBotoes;
    private javax.swing.JTable TbVenda;
    private javax.swing.JTextField TfCliente;
    private javax.swing.JTextField TfCodCliente;
    private javax.swing.JTextField TfCodCondicaoPgto;
    private javax.swing.JTextField TfCodFuncionario;
    private javax.swing.JTextField TfCodProduto;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfCondicaoPgto;
    private javax.swing.JFormattedTextField TfData;
    private JNumberField.JNumberField TfDesconto;
    private javax.swing.JTextField TfFuncionario;
    private javax.swing.JTextField TfProduto;
    private JNumberField.JNumberField TfQuantidade;
    private JNumberField.JNumberField TfValorProduto;
    private JNumberField.JNumberField TfValorTotalVenda;
    private JNumberField.JNumberField TfValorUnitario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario() {
//        getTelasusuario().getTela().setCodigo(16);
//        if (!getTelasusuario().eadmintela()) {
//            PnBotoes.setVisible(false);
//        }
//
//        getTelasusuario().getTela().setCodigo(1);
//        if (!getTelasusuario().eadmintela()) {
//            BtCadCliente.setVisible(false);
//        }
//
//        getTelasusuario().getTela().setCodigo(3);
//        if (!getTelasusuario().eadmintela()) {
//            BtCadFuncionario.setVisible(false);
//        }
//
//        getTelasusuario().getTela().setCodigo(11);
//        if (!getTelasusuario().eadmintela()) {
//            BtCadProduto.setVisible(false);
//        }
//
//        getTelasusuario().getTela().setCodigo(6);
//        if (!getTelasusuario().eadmintela()) {
//            BtCadCondicaoPgto.setVisible(false);
//        }
    }

    public boolean camposobrigatoriospreenchidos() {
        if (TfCodFuncionario.getText().equals("") || TfFuncionario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe qual funcionario realizou o atendimento nesta venda!", "Campos obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            TfCodFuncionario.grabFocus();
            return false;
        }
        if (TfCodCliente.getText().equals("") || TfCliente.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe qual cliente esta realizando a venda!", "Campos obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            TfCodCliente.grabFocus();
            return false;
        }
        if (TfCodCondicaoPgto.getText().equals("") || TfCondicaoPgto.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Informe qual a condicao de pagamento escolhida pelo cliente!", "Campos obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            TfCodCondicaoPgto.grabFocus();
            return false;
        }
        if (TbVenda.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Insira os produtos escolhidos pelo cliente nesta venda!", "Campos obrigatorios", JOptionPane.INFORMATION_MESSAGE);
            TfCodProduto.grabFocus();
            return false;
        }
        return true;
    }

    public void enviardados() {
        prodcompravenda.getCompravenda().setData(datas.retornadataehora());
        prodcompravenda.getCompravenda().setDescricao("VENDA DE NRO. " + TfCodigo.getText() + " AO CLIENTE " + TfCliente.getText());
        cliente.setCodigo(Integer.parseInt(TfCodCliente.getText()));
        prodcompravenda.getCompravenda().setCodigopessoa(cliente.retornacodigopessoacliente());
        prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
        prodcompravenda.getCompravenda().getOperacao().setCodigo(2);
    }

    public void atualizavalortotal() {
        float valor = 0;
        for (int i = 0; i < TbVenda.getRowCount(); i++) {
            TfValorTotalVenda.setText(TbVenda.getValueAt(i, 5).toString());
            valor = valor + Float.parseFloat(TfValorTotalVenda.getValue().toString());
        }
        TfValorTotalVenda.setValue(BigDecimal.valueOf(valor));
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
