package br.com.lojadafatima.InterfacesOperacoes;

import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseOperacoes;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceRealizarOperacoes extends javax.swing.JDialog {

    ClasseOperacoes operacoes = new ClasseOperacoes();
    Preenche preenche = new Preenche();
    private java.awt.Frame primeiratela;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();

    public InterfaceRealizarOperacoes(java.awt.Frame telaorigem, boolean modal, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(usuario);
        analisausuario();
        preenche.PreencheJComboBox(CbOperacoes, operacoes.retornaoperacoescombobox(false));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        CbOperacoes = new javax.swing.JComboBox();
        BtAbrir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Realizar Operação - Software Loja da Fátima");
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Selecione a Operação que deseja realizar:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        jPanel1.add(CbOperacoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 273, -1));

        BtAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sucesso2.png"))); // NOI18N
        BtAbrir.setText("Abrir");
        BtAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtAbrirActionPerformed(evt);
            }
        });
        jPanel1.add(BtAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 69, 79, 36));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BtAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtAbrirActionPerformed
        if (CbOperacoes.getSelectedItem() != null) {
            operacoes.setDescricao(CbOperacoes.getSelectedItem().toString());
            operacoes.setCodigo(operacoes.retornacodigooperacao());
            if (operacoes.getCodigo() != 0) {
                operacoes.retornaoperacao();
                if (operacoes.getInestoque().equals("S") && operacoes.getInfinanceiro().equals("S")) {
                    final InterfaceOperacaoEstoqueFinanceiro tela = new InterfaceOperacaoEstoqueFinanceiro(getPrimeiratela(), true, operacoes, getTelasusuario());
                    tela.setVisible(true);
                    tela.addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosed(java.awt.event.WindowEvent evt) {

                        }
                    });
                } else if (operacoes.getInestoque().equals("S")) {
                    final InterfaceOperacaoEstoque tela = new InterfaceOperacaoEstoque(getPrimeiratela(), true, operacoes, getTelasusuario());
                    tela.setVisible(true);
                    tela.addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosed(java.awt.event.WindowEvent evt) {

                        }
                    });
                } else if (operacoes.getInfinanceiro().equals("S")) {
                    final InterfaceOperacaoFinanceiro tela = new InterfaceOperacaoFinanceiro(getPrimeiratela(), true, operacoes, getTelasusuario());
                    tela.setVisible(true);
                    tela.addWindowListener(new java.awt.event.WindowAdapter() {
                        public void windowClosed(java.awt.event.WindowEvent evt) {

                        }
                    });
                }
            }
        }
    }//GEN-LAST:event_BtAbrirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtAbrir;
    private javax.swing.JComboBox CbOperacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario(){
        getTelasusuario().getTela().setCodigo(22);
        if(!getTelasusuario().eadmintela()){
            BtAbrir.setVisible(false);
        }
    }
    
    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
