package br.com.lojadafatima.InterfacesOperacoes;

import br.com.lojadafatima.ClassesFerramentas.ClasseDatas;
import br.com.lojadafatima.ClassesFerramentas.GeraCodigos;
import br.com.lojadafatima.ClassesFerramentas.GerenciadorCamposBotoes;
import br.com.lojadafatima.ClassesFerramentas.LimpaCamposTela;
import br.com.lojadafatima.ClassesFerramentas.MensagensUsuario;
import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseOperacoes;
import br.com.lojadafatima.CompraVendaOperacoes.ClasseProdutosCompraVenda;
import br.com.lojadafatima.ConexaoBDpostgre.ConexaoPostgre;
import br.com.lojadafatima.Financeiro.ClasseContasPagarReceber;
import br.com.lojadafatima.Financeiro.ClasseParcelas;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesCliente;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesCondicaoPgto;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFornecedor;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesFuncionario;
import br.com.lojadafatima.InterfaceConsultaSimples.ConsulSimplesProduto;
import br.com.lojadafatima.InterfacesFinanceiro.InterfaceCondicaoPagto;
import br.com.lojadafatima.InterfacesPessoa.InterfaceCliente;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFornecedor;
import br.com.lojadafatima.InterfacesPessoa.InterfaceFuncionario;
import br.com.lojadafatima.InterfacesProduto.InterfaceProduto;
import br.com.lojadafatima.Pessoa.ClasseCliente;
import br.com.lojadafatima.Pessoa.ClasseFornecedor;
import br.com.lojadafatima.Produto.ClasseMvtoEstoque;
import br.com.lojadafatima.Usuario.ClasseTelasUsuario;
import java.math.BigDecimal;
import java.util.HashMap;
import javax.swing.JDialog;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.MaskFormatter;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Guilherme Azevedo
 */
public class InterfaceOperacaoEstoqueFinanceiro extends javax.swing.JDialog {

    ClasseProdutosCompraVenda prodcompravenda = new ClasseProdutosCompraVenda();
    GerenciadorCamposBotoes valida = new GerenciadorCamposBotoes();
    private java.awt.Frame primeiratela;
    MaskFormatter valor;
    MaskFormatter data;
    ClasseDatas datas = new ClasseDatas();
    LimpaCamposTela limpar = new LimpaCamposTela();
    ClasseCliente cliente = new ClasseCliente();
    boolean estoqueok = false;
    private ClasseTelasUsuario telasusuario = new ClasseTelasUsuario();
    MensagensUsuario msg = new MensagensUsuario();

    public InterfaceOperacaoEstoqueFinanceiro(java.awt.Frame telaorigem, boolean modal, ClasseOperacoes ope, ClasseTelasUsuario usuario) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        initComponents();
        setTelasusuario(usuario);
        prodcompravenda.getCompravenda().setOperacao(ope);
        CbPessoaActionPerformed(null);
        valida.validacamposCancelar(jPanel1, PnBotoes);
        valida.validacamposCancelar(jPanel3, PnBotoes);
        valida.validacamposCancelar(jPanel4, PnBotoes);
        TfDescOperacao.setDocument(new NaoPermiteAspasSimples());
        TfCodPessoa.setDocument(new PermiteApenasNumeros());
        TfCodCondicaoPgto.setDocument(new PermiteApenasNumeros());
        TfCodFuncionario.setDocument(new PermiteApenasNumeros());
        TfCodProduto.setDocument(new PermiteApenasNumeros());
        TfCodServico.setDocument(new PermiteApenasNumeros());
        analisausuario();
        setDefaultCloseOperation(JDialog.DO_NOTHING_ON_CLOSE);
        TbProdutos.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TfCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        try{
            data = new MaskFormatter("##/##/####");
        } catch(Exception ex){
            JOptionPane.showMessageDialog(null, "Nao foi possivel montar mascara no campo de Data");
        }
        TfData = new JFormattedTextField(data);
        jLabel2 = new javax.swing.JLabel();
        TfDescOperacao = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TfCodFuncionario = new javax.swing.JTextField();
        BtPesqFuncionario = new javax.swing.JButton();
        TfFuncionario = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtCadFuncionario = new javax.swing.JButton();
        TfCodCondicaoPgto = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        BtPesqCondicaoPgto = new javax.swing.JButton();
        TfCondicaoPgto = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BtCadCondicaoPgto = new javax.swing.JButton();
        PnBotoes = new javax.swing.JPanel();
        BtGravar = new javax.swing.JButton();
        BtIncluir = new javax.swing.JButton();
        BtCancelar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        CbPessoa = new javax.swing.JComboBox();
        LbCodPessoa = new javax.swing.JLabel();
        TfCodPessoa = new javax.swing.JTextField();
        BtPesqPessoa = new javax.swing.JButton();
        TfPessoa = new javax.swing.JTextField();
        LbNomePessoa = new javax.swing.JLabel();
        BtCadPessoa = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        LbNotificacao = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        TfCodProduto = new javax.swing.JTextField();
        BtPesqProduto = new javax.swing.JButton();
        TfProduto = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtCadProduto = new javax.swing.JButton();
        TfQuantidade = new JNumberField.JNumberField(2);
        ;
        jLabel11 = new javax.swing.JLabel();
        CbPromocao = new javax.swing.JCheckBox();
        TfValorUnitario = new JNumberField.JNumberField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TfDesconto = new JNumberField.JNumberField(2);
        ;
        TfValorProduto = new JNumberField.JNumberField();
        jLabel14 = new javax.swing.JLabel();
        BtIncluirProdutoTabela = new javax.swing.JButton();
        BtRemoverProdutoTabela = new javax.swing.JButton();
        TfValorTotalOperacao = new JNumberField.JNumberField();
        jLabel16 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbProdutos = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        TfCodServico = new javax.swing.JTextField();
        BtPesqServico = new javax.swing.JButton();
        TfServico = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        BtCadServico = new javax.swing.JButton();
        TfQuantidadeServ = new JNumberField.JNumberField(2);
        ;
        jLabel19 = new javax.swing.JLabel();
        TfValorUnitarioServ = new JNumberField.JNumberField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        TfDescontoServ = new JNumberField.JNumberField(2);
        ;
        jLabel22 = new javax.swing.JLabel();
        TfValorServ = new JNumberField.JNumberField();
        jLabel23 = new javax.swing.JLabel();
        CbPromocaoServ = new javax.swing.JCheckBox();
        BtIncluirServTabela = new javax.swing.JButton();
        BtRemoverServTabela = new javax.swing.JButton();
        TfValorTotalOperacaoServ = new JNumberField.JNumberField();
        jLabel24 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TbServicos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Operação de Estoque e Financeiro - Software Loja da Fátima");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TfCodigo.setEditable(false);
        jPanel1.add(TfCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 80, -1));

        jLabel1.setText("Código");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfData.setEditable(false);
        jPanel1.add(TfData, new org.netbeans.lib.awtextra.AbsoluteConstraints(96, 31, 79, -1));

        jLabel2.setText("Data");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(98, 11, -1, -1));

        TfDescOperacao.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescOperacaoKeyTyped(evt);
            }
        });
        jPanel1.add(TfDescOperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 31, 230, -1));

        jLabel18.setText("Descrição da Operação");
        jPanel1.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(181, 11, -1, -1));

        jLabel3.setText("Cód. Funcionário");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 154, 212, -1));

        TfCodFuncionario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodFuncionarioFocusLost(evt);
            }
        });
        TfCodFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodFuncionarioKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 174, 150, -1));

        BtPesqFuncionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 174, -1, -1));

        TfFuncionario.setEditable(false);
        jPanel1.add(TfFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 174, 293, -1));

        jLabel4.setText("Funcionário");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 154, -1, -1));

        BtCadFuncionario.setText("Cadastrar Funcionário");
        BtCadFuncionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadFuncionarioActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadFuncionario, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 176, 199, -1));

        TfCodCondicaoPgto.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodCondicaoPgtoFocusLost(evt);
            }
        });
        TfCodCondicaoPgto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodCondicaoPgtoKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 226, 150, -1));

        jLabel7.setText("Cód. Condição de Pagamento");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 205, -1, -1));

        BtPesqCondicaoPgto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqCondicaoPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqCondicaoPgtoActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 225, -1, -1));

        TfCondicaoPgto.setEditable(false);
        jPanel1.add(TfCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 226, 293, -1));

        jLabel8.setText("Condição de Pagamento");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 205, -1, -1));

        BtCadCondicaoPgto.setText("Cadastrar Condição de Pagamento");
        BtCadCondicaoPgto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadCondicaoPgtoActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadCondicaoPgto, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 225, -1, -1));

        BtGravar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/salvar.png"))); // NOI18N
        BtGravar.setText("Gravar");
        BtGravar.setName("Gravar"); // NOI18N
        BtGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGravarActionPerformed(evt);
            }
        });

        BtIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluir.setText("Nova Operação");
        BtIncluir.setName("Incluir"); // NOI18N
        BtIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirActionPerformed(evt);
            }
        });

        BtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/cancelar.png"))); // NOI18N
        BtCancelar.setText("Cancelar");
        BtCancelar.setName("Cancelar"); // NOI18N
        BtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PnBotoesLayout = new javax.swing.GroupLayout(PnBotoes);
        PnBotoes.setLayout(PnBotoesLayout);
        PnBotoesLayout.setHorizontalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PnBotoesLayout.createSequentialGroup()
                .addComponent(BtIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PnBotoesLayout.setVerticalGroup(
            PnBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BtIncluir, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
            .addComponent(BtCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(BtGravar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.add(PnBotoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 569, 716, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 256, 716, -1));

        jLabel5.setText("Quem está envolvido nesta operação?");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 57, -1, -1));

        CbPessoa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cliente", "Fornecedor" }));
        CbPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(CbPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 77, 184, -1));

        LbCodPessoa.setText("Cód. Pessoa");
        jPanel1.add(LbCodPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 103, -1, -1));

        TfCodPessoa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfCodPessoaFocusLost(evt);
            }
        });
        TfCodPessoa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodPessoaKeyReleased(evt);
            }
        });
        jPanel1.add(TfCodPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 124, 149, -1));

        BtPesqPessoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(BtPesqPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 123, -1, -1));

        TfPessoa.setEditable(false);
        jPanel1.add(TfPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(225, 124, 296, -1));

        LbNomePessoa.setText("Nome/Nome Fantasia");
        jPanel1.add(LbNomePessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 103, -1, -1));

        BtCadPessoa.setText("Cadastrar Cliente");
        BtCadPessoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadPessoaActionPerformed(evt);
            }
        });
        jPanel1.add(BtCadPessoa, new org.netbeans.lib.awtextra.AbsoluteConstraints(527, 123, 199, -1));

        LbNotificacao.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(LbNotificacao)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LbNotificacao)
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 613, 716, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Cód. Produto");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodProdutoKeyReleased(evt);
            }
        });
        jPanel3.add(TfCodProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 138, -1));

        BtPesqProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(BtPesqProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 31, -1, -1));

        TfProduto.setEditable(false);
        jPanel3.add(TfProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 32, 302, -1));

        jLabel10.setText("Produto");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 11, -1, -1));

        BtCadProduto.setText("Cadastrar Produto");
        BtCadProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadProdutoActionPerformed(evt);
            }
        });
        jPanel3.add(BtCadProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 31, 184, -1));

        TfQuantidade.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfQuantidadeFocusLost(evt);
            }
        });
        TfQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeKeyTyped(evt);
            }
        });
        jPanel3.add(TfQuantidade, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 97, -1));

        jLabel11.setText("Quantidade");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        CbPromocao.setText("Promoção");
        jPanel3.add(CbPromocao, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        TfValorUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfValorUnitarioKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfValorUnitarioKeyTyped(evt);
            }
        });
        jPanel3.add(TfValorUnitario, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 82, 92, -1));

        jLabel12.setText("Valor Unitário");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 62, -1, -1));

        jLabel13.setText("Desconto");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 62, -1, -1));

        jLabel6.setText("%");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 85, -1, -1));

        TfDesconto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfDescontoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescontoKeyTyped(evt);
            }
        });
        jPanel3.add(TfDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 82, 100, -1));

        TfValorProduto.setEditable(false);
        jPanel3.add(TfValorProduto, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 82, 96, -1));

        jLabel14.setText("Valor Total do Produto");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(411, 62, -1, -1));

        BtIncluirProdutoTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirProdutoTabela.setText("Incluir Produto");
        BtIncluirProdutoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirProdutoTabelaActionPerformed(evt);
            }
        });
        jPanel3.add(BtIncluirProdutoTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, -1, -1));

        BtRemoverProdutoTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverProdutoTabela.setText("Remover Produto");
        BtRemoverProdutoTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverProdutoTabelaActionPerformed(evt);
            }
        });
        jPanel3.add(BtRemoverProdutoTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 134, -1, -1));

        TfValorTotalOperacao.setEditable(false);
        jPanel3.add(TfValorTotalOperacao, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 136, 116, -1));

        jLabel16.setText("Valor Total dos Produtos");
        jPanel3.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(584, 113, -1, -1));

        TbProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Operação", "Cód. Produto", "Produto", "Quantidade", "Valor Unitário", "Desconto", "Valor Total do Produto na Venda", "Promoção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbProdutos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TbProdutos);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 691, 102));

        jTabbedPane1.addTab("Produto", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setText("Cód. Serviço");
        jPanel4.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, -1, -1));

        TfCodServico.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfCodServicoKeyReleased(evt);
            }
        });
        jPanel4.add(TfCodServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 31, 138, -1));

        BtPesqServico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesqServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesqServicoActionPerformed(evt);
            }
        });
        jPanel4.add(BtPesqServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(154, 31, -1, -1));

        TfServico.setEditable(false);
        jPanel4.add(TfServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 32, 302, -1));

        jLabel17.setText("Serviço");
        jPanel4.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 11, -1, -1));

        BtCadServico.setText("Cadastrar Serviço");
        BtCadServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtCadServicoActionPerformed(evt);
            }
        });
        jPanel4.add(BtCadServico, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 31, 184, -1));

        TfQuantidadeServ.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                TfQuantidadeServFocusLost(evt);
            }
        });
        TfQuantidadeServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfQuantidadeServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfQuantidadeServKeyTyped(evt);
            }
        });
        jPanel4.add(TfQuantidadeServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 82, 97, -1));

        jLabel19.setText("Quantidade");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 62, -1, -1));

        TfValorUnitarioServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfValorUnitarioServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfValorUnitarioServKeyTyped(evt);
            }
        });
        jPanel4.add(TfValorUnitarioServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 82, 92, -1));

        jLabel20.setText("Valor Unitário");
        jPanel4.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 62, -1, -1));

        jLabel21.setText("Desconto");
        jPanel4.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 62, -1, -1));

        TfDescontoServ.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TfDescontoServKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TfDescontoServKeyTyped(evt);
            }
        });
        jPanel4.add(TfDescontoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(235, 82, 100, -1));

        jLabel22.setText("%");
        jPanel4.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(339, 85, -1, -1));

        TfValorServ.setEditable(false);
        jPanel4.add(TfValorServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 82, 96, -1));

        jLabel23.setText("Valor Total do Serviço");
        jPanel4.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 62, -1, -1));

        CbPromocaoServ.setText("Promoção");
        CbPromocaoServ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPromocaoServActionPerformed(evt);
            }
        });
        jPanel4.add(CbPromocaoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 109, -1, -1));

        BtIncluirServTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/adicionar.png"))); // NOI18N
        BtIncluirServTabela.setText("Incluir Serviço");
        BtIncluirServTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtIncluirServTabelaActionPerformed(evt);
            }
        });
        jPanel4.add(BtIncluirServTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 134, -1, -1));

        BtRemoverServTabela.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/deletar.png"))); // NOI18N
        BtRemoverServTabela.setText("Remover Serviço");
        BtRemoverServTabela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtRemoverServTabelaActionPerformed(evt);
            }
        });
        jPanel4.add(BtRemoverServTabela, new org.netbeans.lib.awtextra.AbsoluteConstraints(135, 134, -1, -1));

        TfValorTotalOperacaoServ.setEditable(false);
        jPanel4.add(TfValorTotalOperacaoServ, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 136, 116, -1));

        jLabel24.setText("Valor Total dos Serviços");
        jPanel4.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(587, 113, -1, -1));

        TbServicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código Operação", "Cód. Serviço", "Serviço", "Quantidade", "Valor Unitário", "Desconto", "Valor Total do Servico na Venda", "Promoção"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbServicos.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(TbServicos);

        jPanel4.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 165, 691, 102));

        jTabbedPane1.addTab("Serviço", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 264, -1, 299));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void TfDescOperacaoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescOperacaoKeyTyped
        valida.limitemaximo(evt, TfDescOperacao.getText(), 50);
    }//GEN-LAST:event_TfDescOperacaoKeyTyped

    private void TfCodFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodFuncionarioKeyReleased
        if (!TfCodFuncionario.getText().equals("")) {
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
            if (prodcompravenda.getCompravenda().getFuncionario().efuncionarioativo()) {
                prodcompravenda.getCompravenda().getFuncionario().getPessoafis().getPessoa().setCodigo(prodcompravenda.getCompravenda().getFuncionario().retornacodigopessoafuncionario());
                TfFuncionario.setText(prodcompravenda.getCompravenda().getFuncionario().getPessoafis().retornanomeporCodigo());
            } else {
                TfFuncionario.setText("");
            }
        } else {
            TfFuncionario.setText("");
        }
    }//GEN-LAST:event_TfCodFuncionarioKeyReleased

    private void BtPesqFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqFuncionarioActionPerformed
        final ConsulSimplesFuncionario tela = new ConsulSimplesFuncionario(getPrimeiratela(), true, prodcompravenda.getCompravenda().getFuncionario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getFuncionario().getCodigo() != 0) {
                    TfCodFuncionario.setText("" + prodcompravenda.getCompravenda().getFuncionario().getCodigo());
                    TfCodFuncionarioKeyReleased(null);
                } else {
                    TfCodFuncionario.setText("");
                    TfFuncionario.setText("");
                }
            }
        });
    }//GEN-LAST:event_BtPesqFuncionarioActionPerformed

    private void BtCadFuncionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadFuncionarioActionPerformed
        final InterfaceFuncionario tela = new InterfaceFuncionario(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadFuncionarioActionPerformed

    private void TfCodCondicaoPgtoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodCondicaoPgtoKeyReleased
        if (!TfCodCondicaoPgto.getText().equals("")) {
            prodcompravenda.getCompravenda().getCondicao().setCodigo(Integer.parseInt(TfCodCondicaoPgto.getText()));
            TfCondicaoPgto.setText(prodcompravenda.getCompravenda().getCondicao().retornadescricaocondicao());
        } else {
            TfCondicaoPgto.setText("");
        }
    }//GEN-LAST:event_TfCodCondicaoPgtoKeyReleased

    private void BtPesqCondicaoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqCondicaoPgtoActionPerformed
        final ConsulSimplesCondicaoPgto tela = new ConsulSimplesCondicaoPgto(getPrimeiratela(), true, prodcompravenda.getCompravenda().getCondicao());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getCompravenda().getCondicao().getCodigo() == 0) {
                    TfCodCondicaoPgto.setText("");
                } else {
                    TfCodCondicaoPgto.setText("" + prodcompravenda.getCompravenda().getCondicao().getCodigo());
                }
                TfCodCondicaoPgtoKeyReleased(null);
            }
        });
    }//GEN-LAST:event_BtPesqCondicaoPgtoActionPerformed

    private void BtCadCondicaoPgtoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadCondicaoPgtoActionPerformed
        final InterfaceCondicaoPagto tela = new InterfaceCondicaoPagto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadCondicaoPgtoActionPerformed

    private void TfCodProdutoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodProdutoKeyReleased
        if (!TfCodProduto.getText().equals("")){
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
            if (prodcompravenda.getForneproduto().getProduto().eprodutoativo() && !prodcompravenda.getForneproduto().getProduto().eservico()) {
                if(CbPessoa.getSelectedItem().toString().equals("Fornecedor") && prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("E")){
                    if(!TfCodPessoa.getText().equals("") && !TfPessoa.getText().equals("")){
                        if(prodcompravenda.getForneproduto().produtodestefornecedor()){
                            TfProduto.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                            TfQuantidade.setValue(BigDecimal.valueOf(0));
                            TfValorProduto.setValue(BigDecimal.valueOf(0));
                            if(prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("E")){
                                TfValorUnitario.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() + ((prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() * prodcompravenda.getForneproduto().getProduto().retornapercentuallucro())/100)));
                            }else{
                                TfValorUnitario.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto()));
                            }
                        }else{
                            TfProduto.setText("");
                            TfValorUnitario.setValue(BigDecimal.valueOf(0));
                            TfQuantidade.setValue(BigDecimal.valueOf(0));
                            TfValorProduto.setText("");
                            msg.CampoNaoPreenchido(LbNotificacao, "Este produto não pode ser adquirido por este fornecedor!");
                        }
                    }else{
                        msg.CampoNaoPreenchido(LbNotificacao, "Digite o Fornecedor para que o sistema busque apenas os produtos deste Fornecedor!");
                        limpar.Limpar(jPanel3);
                        TfCodPessoa.grabFocus();
                    }
                }else{
                    TfProduto.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                    TfValorProduto.setValue(BigDecimal.valueOf(0));
                    if(prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("E")){
                        TfValorUnitario.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() + ((prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() * prodcompravenda.getForneproduto().getProduto().retornapercentuallucro())/100)));
                    }else{
                        TfValorUnitario.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto()));
                    }
                }
            }else{
                TfProduto.setText("");
                TfValorUnitario.setValue(BigDecimal.valueOf(0));
                TfQuantidade.setValue(BigDecimal.valueOf(0));
                TfValorProduto.setText("");
            }
        }else{
            TfProduto.setText("");
            TfValorUnitario.setValue(BigDecimal.valueOf(0));
            TfQuantidade.setValue(BigDecimal.valueOf(0));
            TfValorProduto.setText("");
        }
    }//GEN-LAST:event_TfCodProdutoKeyReleased

    private void BtPesqProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqProdutoActionPerformed
        final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto(), "P");
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodProduto.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodProdutoKeyReleased(null);
                } else {
                    TfCodProduto.setText("");
                    TfCodProdutoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqProdutoActionPerformed

    private void BtCadProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadProdutoActionPerformed
        final InterfaceProduto tela = new InterfaceProduto(getPrimeiratela(), true, getTelasusuario());
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {

            }
        });
    }//GEN-LAST:event_BtCadProdutoActionPerformed

    private void BtIncluirProdutoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirProdutoTabelaActionPerformed
        boolean inclui = true;
        limpar.Limpar(TbServicos);
        TfValorTotalOperacaoServ.setValue(BigDecimal.ZERO);
        if (estoqueok) {
            if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
                if (TfValorProduto.getValue() != BigDecimal.valueOf(0) || TfQuantidade.getValue() != BigDecimal.ZERO) {
                    for (int i = 0; i < TbProdutos.getRowCount(); i++) {
                        if (Integer.parseInt(TbProdutos.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodProduto.getText())) {
                            inclui = false;
                            if (JOptionPane.showConfirmDialog(null, "Este produto já foi adicionado a esta operação!\n"
                                    + "Deseja substituir a quantidade deste produto?", "Produto adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                TbProdutos.setValueAt(TfQuantidade.getText(), i, 3);
                                TbProdutos.setValueAt(TfValorUnitario.getText(), i, 4);
                                TbProdutos.setValueAt(TfDesconto.getText(), i, 5);
                                TbProdutos.setValueAt(TfValorProduto.getText(), i, 6);
                                if(CbPromocao.isSelected()){
                                    TbProdutos.setValueAt("S", i, 7);
                                }else{
                                    TbProdutos.setValueAt("N", i, 7);
                                }
                            }
                        }
                    }
                    if (inclui) {
                        DefaultTableModel tabela = (DefaultTableModel) TbProdutos.getModel();
                        int linha = tabela.getRowCount();
                        tabela.setNumRows(linha + 1);
                        tabela.setValueAt(TfCodigo.getText(), linha, 0);
                        tabela.setValueAt(TfCodProduto.getText(), linha, 1);
                        tabela.setValueAt(TfProduto.getText(), linha, 2);
                        tabela.setValueAt(TfQuantidade.getText(), linha, 3);
                        tabela.setValueAt(TfValorUnitario.getText(), linha, 4);
                        tabela.setValueAt(TfDesconto.getText(), linha, 5);
                        tabela.setValueAt(TfValorProduto.getText(), linha, 6);
                        if(CbPromocao.isSelected()){
                            tabela.setValueAt("S", linha, 7);
                        }else{
                            tabela.setValueAt("N", linha, 7);
                        }
                    }
                    TfCodProduto.setText("");
                    TfProduto.setText("");
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                    TfValorUnitario.setValue(BigDecimal.valueOf(0));
                    TfDesconto.setValue(BigDecimal.ZERO);
                    TfValorProduto.setValue(BigDecimal.valueOf(0));
                    atualizavalortotal();
                } else {
                    msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do produto e a quantidade corretamente!");
                }
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Informe o produto a ser adicionado nesta operação!");
                TfCodProduto.grabFocus();
            }
        }
    }//GEN-LAST:event_BtIncluirProdutoTabelaActionPerformed

    private void BtRemoverProdutoTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverProdutoTabelaActionPerformed
        int linha = TbProdutos.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este produto da operação?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbProdutos.getModel();
                tabela.removeRow(linha);
                atualizavalortotal();
            }
        }
    }//GEN-LAST:event_BtRemoverProdutoTabelaActionPerformed

    private void BtGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGravarActionPerformed
        if (camposobrigatoriospreenchidos()) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Gravar esta operação e de que todas as informações estçao corretas?", "Deseja gravar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                enviardados();
                prodcompravenda.getCompravenda().incluir();

                ClasseMvtoEstoque mvestoque = new ClasseMvtoEstoque();
                final ClasseParcelas parcelas = new ClasseParcelas();
                mvestoque.setCompravenda(prodcompravenda.getCompravenda());
                mvestoque.setDtmvto(datas.retornadataehora());
                mvestoque.setTpmvto(prodcompravenda.getCompravenda().getOperacao().getTpestoque());
                
                if (TbProdutos.getRowCount() > 0){
                    for (int i = 0; i < TbProdutos.getRowCount(); i++) {
                        prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbProdutos.getValueAt(i, 1).toString()));
                        TfQuantidade.setText(TbProdutos.getValueAt(i, 3).toString());
                        prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidade.getValue().toString()));
                        TfValorUnitario.setText(TbProdutos.getValueAt(i, 4).toString());
                        prodcompravenda.setValorunit(Float.parseFloat(TfValorUnitario.getValue().toString()));
                        TfValorProduto.setText(TbProdutos.getValueAt(i, 5).toString());
                        prodcompravenda.setValorprodut(Float.parseFloat(TfValorProduto.getValue().toString()));
                        prodcompravenda.incluirprodutocompravenda();

                        mvestoque.getProduto().setCodigo(Integer.parseInt(TbProdutos.getValueAt(i, 1).toString()));
                        TfQuantidade.setText(TbProdutos.getValueAt(i, 3).toString());
                        mvestoque.setQtmvto(Float.parseFloat(TfQuantidade.getValue().toString()));
                        mvestoque.incluirmvto();
                    }
                    parcelas.getConta().setTotal(Float.parseFloat(TfValorTotalOperacao.getValue().toString()));
                }else if (TbServicos.getRowCount() > 0){
                    for (int i = 0; i < TbServicos.getRowCount(); i++) {
                        prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TbServicos.getValueAt(i, 1).toString()));
                        TfQuantidadeServ.setText(TbServicos.getValueAt(i, 3).toString());
                        prodcompravenda.setQuantidade(Float.parseFloat(TfQuantidadeServ.getValue().toString()));
                        TfValorUnitarioServ.setText(TbServicos.getValueAt(i, 4).toString());
                        prodcompravenda.setValorunit(Float.parseFloat(TfValorUnitarioServ.getValue().toString()));
                        TfValorServ.setText(TbServicos.getValueAt(i, 5).toString());
                        prodcompravenda.setValorprodut(Float.parseFloat(TfValorServ.getValue().toString()));
                        prodcompravenda.incluirprodutocompravenda();
                    }
                    parcelas.getConta().setTotal(Float.parseFloat(TfValorTotalOperacaoServ.getValue().toString()));
                }
                
                parcelas.getConta().setCompravenda(prodcompravenda.getCompravenda());
                parcelas.getConta().setCondicao(prodcompravenda.getCompravenda().getCondicao());
                parcelas.getConta().setOperacao(prodcompravenda.getCompravenda().getOperacao());
                parcelas.getConta().setDescricao(prodcompravenda.getCompravenda().getDescricao());
                parcelas.getConta().setDtconta(TfData.getText());
                parcelas.getConta().setCodigopessoa(prodcompravenda.getCompravenda().getCodigopessoa());
                parcelas.getConta().incluir();

                parcelas.gerarparcelas();

                final InterfaceAjusteDatasEPrecos tela = new InterfaceAjusteDatasEPrecos(getPrimeiratela(), true, parcelas);
                tela.setVisible(true);
                tela.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosed(java.awt.event.WindowEvent evt) {
                        HashMap filtro = new HashMap();
                        filtro.put("CD_COMPRA_VENDA", prodcompravenda.getCompravenda().getCodigo());
                        filtro.put("CD_OPERACAO", prodcompravenda.getCompravenda().getOperacao().getCodigo());
                        filtro.put("CD_CONTA", parcelas.getConta().getCodigo());
                        filtro.put("DS_NOTA", "EXTRATO DE "+prodcompravenda.getCompravenda().getOperacao().getDescricao());
                        if(CbPessoa.getSelectedItem().toString().equals("Fornecedor")) filtro.put("TP_PESSOA", "Fornecedor:");
                        else                                                           filtro.put("TP_PESSOA", "Cliente:");
                        ConexaoPostgre conexao = new ConexaoPostgre();
                        JDialog dialog = new JDialog(new javax.swing.JFrame(), "Visualização - Software Loja da Fátima", true);
                        dialog.setSize(1000, 700);
                        dialog.setLocationRelativeTo(null);
                        try {
                            JasperPrint print = JasperFillManager.fillReport("relatorios\\notaoperacaoestoquefinanceiro.jasper", filtro, conexao.conecta());
                            
                            JasperViewer viewer = new JasperViewer(print, true);
                            dialog.getContentPane().add(viewer.getContentPane());
                            dialog.setVisible(true);
                        } catch (Exception ex) {
                            System.out.println(ex);
                        }
                    }
                });

                limpar.Limpar(jPanel1);
                limpar.Limpar(jPanel3);
                limpar.Limpar(jPanel4);
                limpar.Limpar(TbProdutos);
                limpar.Limpar(TbServicos);
                valida.validacamposCancelar(jPanel1, PnBotoes);
                valida.validacamposCancelar(jPanel3, PnBotoes);
                valida.validacamposCancelar(jPanel4, PnBotoes);
            }
        }
    }//GEN-LAST:event_BtGravarActionPerformed

    private void BtIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirActionPerformed
        TfData.setText(datas.retornadataatual());
        GeraCodigos geracodigos = new GeraCodigos();
        TfDescOperacao.setText(prodcompravenda.getCompravenda().getOperacao().getDescricao());
        TfCodigo.setText("" + geracodigos.gerasequencia("COMPRA_VENDA", "CD_COMPRA_VENDA", "CD_OPERACAO", prodcompravenda.getCompravenda().getOperacao().getCodigo()));
        valida.validacamposCadastrar(jPanel1, PnBotoes);
        valida.validacamposCadastrar(jPanel3, PnBotoes);
        valida.validacamposCadastrar(jPanel4, PnBotoes);
    }//GEN-LAST:event_BtIncluirActionPerformed

    private void BtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCancelarActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Deseja realmente cancelar esta compra?\n"
                + "(Caso sim, TODOS os dados digitados serão limpos da tela)", "Deseja cancelar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
            limpar.Limpar(jPanel1);
            limpar.Limpar(jPanel3);
            limpar.Limpar(jPanel4);
            limpar.Limpar(TbProdutos);
            limpar.Limpar(TbServicos);
            valida.validacamposCancelar(jPanel1, PnBotoes);
            valida.validacamposCancelar(jPanel3, PnBotoes);
            valida.validacamposCancelar(jPanel4, PnBotoes);
        }
    }//GEN-LAST:event_BtCancelarActionPerformed

    private void TfCodPessoaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodPessoaKeyReleased
        limpar.Limpar(TbProdutos);
        atualizavalortotal();
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            if (!TfCodPessoa.getText().equals("")) {
                cliente.setCodigo(Integer.parseInt(TfCodPessoa.getText()));
                if (cliente.eativo()) {
                    TfPessoa.setText(cliente.retornanomecliente());
                } else {
                    TfPessoa.setText("");
                }
            } else {
                TfPessoa.setText("");
            }
        } else {
            if (!TfCodPessoa.getText().equals("")) {
                prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodPessoa.getText()));
                if (prodcompravenda.getForneproduto().getFornecedor().efornecedorativo()) {
                    prodcompravenda.getForneproduto().getFornecedor().getPessoajur().getPessoa().setCodigo(prodcompravenda.getForneproduto().getFornecedor().retornacodigopessoafornecedor());
                    TfPessoa.setText(prodcompravenda.getForneproduto().getFornecedor().getPessoajur().retornanomeporCodigo());
                } else {
                    TfPessoa.setText("");
                }
            } else {
                TfPessoa.setText("");
            }
        }
    }//GEN-LAST:event_TfCodPessoaKeyReleased

    private void BtPesqPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqPessoaActionPerformed
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            final ConsulSimplesCliente tela = new ConsulSimplesCliente(getPrimeiratela(), true, cliente);
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    if (cliente.getCodigo() != 0) {
                        TfCodPessoa.setText("" + cliente.getCodigo());
                        TfCodPessoaKeyReleased(null);
                    } else {
                        TfCodPessoa.setText("");
                        TfPessoa.setText("");
                    }
                }
            });
        } else {
            final ConsulSimplesFornecedor tela = new ConsulSimplesFornecedor(getPrimeiratela(), true, prodcompravenda.getForneproduto().getFornecedor());
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {
                    if (prodcompravenda.getForneproduto().getFornecedor().getCodigo() != 0) {
                        TfCodPessoa.setText("" + prodcompravenda.getForneproduto().getFornecedor().getCodigo());
                        TfCodPessoaKeyReleased(null);
                    } else {
                        TfCodPessoa.setText("");
                        TfPessoa.setText("");
                    }
                }
            });
        }
    }//GEN-LAST:event_BtPesqPessoaActionPerformed

    private void BtCadPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadPessoaActionPerformed
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            final InterfaceCliente tela = new InterfaceCliente(getPrimeiratela(), true, getTelasusuario());
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {

                }
            });
        } else {
            final InterfaceFornecedor tela = new InterfaceFornecedor(getPrimeiratela(), true, getTelasusuario());
            tela.setVisible(true);
            tela.addWindowListener(new java.awt.event.WindowAdapter() {
                public void windowClosed(java.awt.event.WindowEvent evt) {

                }
            });
        }
    }//GEN-LAST:event_BtCadPessoaActionPerformed

    private void CbPessoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPessoaActionPerformed
        limpar.Limpar(TbProdutos);
        atualizavalortotal();
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            LbCodPessoa.setText("Cód. Cliente");
            LbNomePessoa.setText("Cliente");
            BtCadPessoa.setText("Cadastrar Cliente");
        } else {
            LbCodPessoa.setText("Cód. Fornecedor");
            LbNomePessoa.setText("Fornecedor");
            BtCadPessoa.setText("Cadastrar Fornecedor");
        }
        analisausuario();
        TfCodPessoaKeyReleased(null);
    }//GEN-LAST:event_CbPessoaActionPerformed

    private void TfQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyReleased
        if(TfDesconto.getValue() == BigDecimal.ZERO) TfValorProduto.setValue(TfQuantidade.getValue().multiply(TfValorUnitario.getValue()));
        else{
            TfValorProduto.setValue(TfQuantidade.getValue().multiply(TfValorUnitario.getValue()));
            TfValorProduto.setValue(TfValorProduto.getValue().subtract((TfValorProduto.getValue().multiply(TfDesconto.getValue())).divide(BigDecimal.valueOf(100))));
        }
    }//GEN-LAST:event_TfQuantidadeKeyReleased

    private void TfValorUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioKeyReleased
        TfQuantidadeKeyReleased(evt);
    }//GEN-LAST:event_TfValorUnitarioKeyReleased

    private void TfQuantidadeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfQuantidadeFocusLost
        if (prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("S")) {
            estoqueok = false;
            if (!TfCodProduto.getText().equals("") && !TfProduto.getText().equals("")) {
                ClasseMvtoEstoque estoque = new ClasseMvtoEstoque();
                estoque.getProduto().setCodigo(Integer.parseInt(TfCodProduto.getText()));
                if (Float.parseFloat(TfQuantidade.getValue().toString()) > estoque.retornaestoqueatual()) {
                    JOptionPane.showMessageDialog(null, "A quantidade digitada é maior que o estoque atual disponível deste produto!\nEstoque atual: " + estoque.retornaestoqueatual(), "Estoque insuficiente", JOptionPane.OK_OPTION);
                    TfQuantidade.setValue(BigDecimal.valueOf(0));
                } else {
                    estoqueok = true;
                }
            }else{
                msg.CampoNaoPreenchido(LbNotificacao, "Digite o Produto antes da Quantidade!");
                TfCodProduto.grabFocus();
            }
        }
    }//GEN-LAST:event_TfQuantidadeFocusLost

    private void TfQuantidadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeKeyTyped
        valida.limitemaximo(evt, TfQuantidade.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeKeyTyped

    private void TfValorUnitarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioKeyTyped
        valida.limitemaximo(evt, TfValorUnitario.getText(), 13);
    }//GEN-LAST:event_TfValorUnitarioKeyTyped

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        if (PnBotoes.isVisible() && BtGravar.isEnabled()) {
            if (JOptionPane.showConfirmDialog(null, "Você está prestes a fechar esta janela.\nAo fechar esta janela tudo que você digitou será esquecido!", "Tem certeza que deseja fechar?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                dispose();
            }
        } else {
            dispose();
        }
    }//GEN-LAST:event_formWindowClosing

    private void TfCodFuncionarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodFuncionarioFocusLost
        if (TfFuncionario.getText().equals("")) {
            TfCodFuncionario.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código do funcionário corretamente!");
        }else{
            prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
        }
    }//GEN-LAST:event_TfCodFuncionarioFocusLost

    private void TfCodPessoaFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodPessoaFocusLost
        if (TfPessoa.getText().equals("")) {
            TfCodPessoa.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código corretamente!");
        } else {
            if (CbPessoa.getSelectedItem().toString().equals("Fornecedor") && prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("E")) {
                prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodPessoa.getText()));
            }
            if (prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("E")) {
                ClasseContasPagarReceber contas = new ClasseContasPagarReceber();
                if (CbPessoa.getSelectedItem().toString().equals("Fornecedor")) {
                    ClasseFornecedor forn = new ClasseFornecedor();
                    forn.setCodigo(Integer.parseInt(TfCodPessoa.getText()));
                    contas.setCodigopessoa(forn.retornacodigopessoafornecedor());
                } else {
                    ClasseCliente cliente = new ClasseCliente();
                    cliente.setCodigo(Integer.parseInt(TfCodPessoa.getText()));
                    contas.setCodigopessoa(cliente.retornacodigopessoacliente());
                }
                contas.setCodigopessoa(cliente.retornacodigopessoacliente());
                if (contas.epessoainadimplente()) {
                    if (JOptionPane.showConfirmDialog(null, "Existem contas à receber em aberto ou vencidas desta pessoa, deseja continuar?", "Pessoa inadimplente", JOptionPane.YES_NO_OPTION) == JOptionPane.NO_OPTION) {
                        TfCodPessoa.setText("");
                        TfCodPessoaKeyReleased(null);
                    }
                }
            }

        }
    }//GEN-LAST:event_TfCodPessoaFocusLost

    private void TfCodCondicaoPgtoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfCodCondicaoPgtoFocusLost
        if (TfCondicaoPgto.getText().equals("")) {
            TfCodCondicaoPgto.setText("");
            msg.CampoNaoPreenchido(LbNotificacao, "Digite o código da condição de pagamento corretamente!");
        }
    }//GEN-LAST:event_TfCodCondicaoPgtoFocusLost

    private void TfDescontoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoKeyReleased
        if(TfValorUnitario.getValue() != BigDecimal.ZERO){
            if(TfQuantidade.getValue() != BigDecimal.ZERO){
                if(!prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("S") && (!TfCodPessoa.getText().equals("") && !TfPessoa.getText().equals(""))){
                    TfQuantidadeKeyReleased(evt);
                }else{
                    if(prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("S")){
                        msg.CampoNaoPreenchido(LbNotificacao, "Digite o Funcionário para permitir o desconto!");
                        TfDesconto.setValue(BigDecimal.ZERO);
                        TfCodFuncionario.grabFocus();
                    }else{
                        TfQuantidadeKeyReleased(evt);
                    }
                }
            }else{
                msg.CampoNaoPreenchido(LbNotificacao, "Digite a quantidade do Produto!");
                TfDesconto.setValue(BigDecimal.ZERO);
                TfQuantidade.grabFocus();
            }
        }else{
            msg.CampoNaoPreenchido(LbNotificacao, "Insira o Valor Unitário do Produto!");
            TfDesconto.setValue(BigDecimal.ZERO);
            TfValorUnitario.grabFocus();
        }
    }//GEN-LAST:event_TfDescontoKeyReleased

    private void TfDescontoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoKeyTyped
        valida.limitemaximo(evt, TfDesconto.getText(), 10);
    }//GEN-LAST:event_TfDescontoKeyTyped

    private void TfCodServicoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfCodServicoKeyReleased
        if (!TfCodServico.getText().equals("")){
            prodcompravenda.getForneproduto().getProduto().setCodigo(Integer.parseInt(TfCodServico.getText()));
            if (prodcompravenda.getForneproduto().getProduto().eprodutoativo() && prodcompravenda.getForneproduto().getProduto().eservico()) {
                if(CbPessoa.getSelectedItem().toString().equals("Fornecedor") && prodcompravenda.getCompravenda().getOperacao().getTpestoque().equals("E")){
                    if(!TfCodPessoa.getText().equals("") && !TfPessoa.getText().equals("")){
                        if(prodcompravenda.getForneproduto().produtodestefornecedor()){
                            TfServico.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                            TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                            TfValorServ.setValue(BigDecimal.valueOf(0));
                            if(prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("E")){
                                TfValorUnitarioServ.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() + ((prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() * prodcompravenda.getForneproduto().getProduto().retornapercentuallucro())/100)));
                            }else{
                                TfValorUnitarioServ.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto()));
                            }
                        }else{
                            TfServico.setText("");
                            TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
                            TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                            TfValorServ.setText("");
                            msg.CampoNaoPreenchido(LbNotificacao, "Este serviço não pode ser adquirido com este fornecedor!");
                        }
                    }else{
                        msg.CampoNaoPreenchido(LbNotificacao, "Digite o Fornecedor para que o sistema busque apenas os serviços deste Fornecedor!");
                        limpar.Limpar(jPanel4);
                        TfCodPessoa.grabFocus();
                    }
                }else{
                    TfServico.setText(prodcompravenda.getForneproduto().getProduto().retornadescricaoproduto());
                    TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                    TfValorServ.setValue(BigDecimal.valueOf(0));
                    if(prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("E")){
                        TfValorUnitarioServ.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() + ((prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto() * prodcompravenda.getForneproduto().getProduto().retornapercentuallucro())/100)));
                    }else{
                        TfValorUnitarioServ.setValue(BigDecimal.valueOf(prodcompravenda.getForneproduto().getProduto().mediavalordecompraproduto()));
                    }
                }
            }else{
                TfServico.setText("");
                TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
                TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                TfValorServ.setText("");
            }
        }else{
            TfServico.setText("");
            TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
            TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
            TfValorServ.setText("");
        }
    }//GEN-LAST:event_TfCodServicoKeyReleased

    private void BtPesqServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesqServicoActionPerformed
        final ConsulSimplesProduto tela = new ConsulSimplesProduto(getPrimeiratela(), true, prodcompravenda.getForneproduto().getProduto(), "S");
        tela.setVisible(true);
        tela.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                if (prodcompravenda.getForneproduto().getProduto().getCodigo() != 0) {
                    TfCodServico.setText("" + prodcompravenda.getForneproduto().getProduto().getCodigo());
                    TfCodServicoKeyReleased(null);
                } else {
                    TfCodServico.setText("");
                    TfCodServicoKeyReleased(null);
                }
            }
        });
    }//GEN-LAST:event_BtPesqServicoActionPerformed

    private void BtCadServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtCadServicoActionPerformed
        BtCadProdutoActionPerformed(evt);
    }//GEN-LAST:event_BtCadServicoActionPerformed

    private void TfQuantidadeServFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_TfQuantidadeServFocusLost
        estoqueok = true;
    }//GEN-LAST:event_TfQuantidadeServFocusLost

    private void TfQuantidadeServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeServKeyReleased
        if(TfDescontoServ.getValue() == BigDecimal.ZERO) TfValorServ.setValue(TfQuantidadeServ.getValue().multiply(TfValorUnitarioServ.getValue()));
        else{
            TfValorServ.setValue(TfQuantidade.getValue().multiply(TfValorUnitario.getValue()));
            TfValorServ.setValue(TfValorServ.getValue().subtract((TfValorServ.getValue().multiply(TfDescontoServ.getValue())).divide(BigDecimal.valueOf(100))));
        }
    }//GEN-LAST:event_TfQuantidadeServKeyReleased

    private void TfQuantidadeServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfQuantidadeServKeyTyped
        valida.limitemaximo(evt, TfQuantidadeServ.getText(), 10);
    }//GEN-LAST:event_TfQuantidadeServKeyTyped

    private void TfValorUnitarioServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioServKeyReleased
        TfQuantidadeServKeyReleased(evt);
    }//GEN-LAST:event_TfValorUnitarioServKeyReleased

    private void TfValorUnitarioServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfValorUnitarioServKeyTyped
        valida.limitemaximo(evt, TfValorUnitarioServ.getText(), 13);
    }//GEN-LAST:event_TfValorUnitarioServKeyTyped

    private void TfDescontoServKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoServKeyReleased
        if(TfValorUnitarioServ.getValue() != BigDecimal.ZERO){
            if(TfQuantidadeServ.getValue() != BigDecimal.ZERO){
                if(!prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("S") && (!TfCodServico.getText().equals("") && !TfServico.getText().equals(""))){
                    TfQuantidadeServKeyReleased(evt);
                }else{
                    if(prodcompravenda.getCompravenda().getOperacao().getTpfinanceiro().equals("S")){
                        msg.CampoNaoPreenchido(LbNotificacao, "Digite o Funcionário para permitir o desconto!");
                        TfDescontoServ.setValue(BigDecimal.ZERO);
                        TfCodFuncionario.grabFocus();
                    }else{
                        TfQuantidadeServKeyReleased(evt);
                    }
                }
            }else{
                msg.CampoNaoPreenchido(LbNotificacao, "Digite a quantidade do Serviço!");
                TfDescontoServ.setValue(BigDecimal.ZERO);
                TfQuantidadeServ.grabFocus();
            }
        }else{
            msg.CampoNaoPreenchido(LbNotificacao, "Insira o Valor Unitário do Serviço!");
            TfDescontoServ.setValue(BigDecimal.ZERO);
            TfValorUnitarioServ.grabFocus();
        }
    }//GEN-LAST:event_TfDescontoServKeyReleased

    private void TfDescontoServKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TfDescontoServKeyTyped
        valida.limitemaximo(evt, TfDescontoServ.getText(), 10);
    }//GEN-LAST:event_TfDescontoServKeyTyped

    private void BtIncluirServTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtIncluirServTabelaActionPerformed
        boolean inclui = true;
        limpar.Limpar(TbProdutos);
        TfValorTotalOperacao.setValue(BigDecimal.ZERO);
            if (!TfCodServico.getText().equals("") && !TfServico.getText().equals("")) {
                if (TfValorServ.getValue() != BigDecimal.valueOf(0) || TfQuantidadeServ.getValue() != BigDecimal.ZERO) {
                    for (int i = 0; i < TbServicos.getRowCount(); i++) {
                        if (Integer.parseInt(TbServicos.getValueAt(i, 1).toString()) == Integer.parseInt(TfCodServico.getText())) {
                            inclui = false;
                            if (JOptionPane.showConfirmDialog(null, "Este serviço já foi adicionado a esta operação!\n"
                                    + "Deseja substituir a quantidade deste serviço?", "Serviço adicionado", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                                TbServicos.setValueAt(TfQuantidadeServ.getText(), i, 3);
                                TbServicos.setValueAt(TfValorUnitarioServ.getText(), i, 4);
                                TbServicos.setValueAt(TfDescontoServ.getText(), i, 5);
                                TbServicos.setValueAt(TfValorServ.getText(), i, 6);
                                if(CbPromocaoServ.isSelected()){
                                    TbServicos.setValueAt("S", i, 7);
                                }else{
                                    TbServicos.setValueAt("N", i, 7);
                                }
                            }
                        }
                    }
                    if (inclui) {
                        DefaultTableModel tabela = (DefaultTableModel) TbServicos.getModel();
                        int linha = tabela.getRowCount();
                        tabela.setNumRows(linha + 1);
                        tabela.setValueAt(TfCodigo.getText(), linha, 0);
                        tabela.setValueAt(TfCodServico.getText(), linha, 1);
                        tabela.setValueAt(TfServico.getText(), linha, 2);
                        tabela.setValueAt(TfQuantidadeServ.getText(), linha, 3);
                        tabela.setValueAt(TfValorUnitarioServ.getText(), linha, 4);
                        tabela.setValueAt(TfDescontoServ.getText(), linha, 5);
                        tabela.setValueAt(TfValorServ.getText(), linha, 6);
                        if(CbPromocaoServ.isSelected()){
                            tabela.setValueAt("S", linha, 7);
                        }else{
                            tabela.setValueAt("N", linha, 7);
                        }
                    }
                    TfCodServico.setText("");
                    TfServico.setText("");
                    TfQuantidadeServ.setValue(BigDecimal.valueOf(0));
                    TfValorUnitarioServ.setValue(BigDecimal.valueOf(0));
                    TfDescontoServ.setValue(BigDecimal.ZERO);
                    TfValorServ.setValue(BigDecimal.valueOf(0));
                    atualizavalortotalserv();
                } else {
                    msg.CampoNaoPreenchido(LbNotificacao, "Digite o valor unitário do serviço e a quantidade corretamente!");
                }
            } else {
                msg.CampoNaoPreenchido(LbNotificacao, "Informe o serviço a ser adicionado nesta operação!");
                TfCodProduto.grabFocus();
            }
        
    }//GEN-LAST:event_BtIncluirServTabelaActionPerformed

    private void BtRemoverServTabelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtRemoverServTabelaActionPerformed
        int linha = TbServicos.getSelectedRow();
        if (linha > -1) {
            if (JOptionPane.showConfirmDialog(null, "Tem certeza que deseja remover este serviço da operação?", "Deseja remover?", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
                DefaultTableModel tabela = (DefaultTableModel) TbServicos.getModel();
                tabela.removeRow(linha);
                atualizavalortotalserv();
            }
        }
    }//GEN-LAST:event_BtRemoverServTabelaActionPerformed

    private void CbPromocaoServActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPromocaoServActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CbPromocaoServActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtCadCondicaoPgto;
    private javax.swing.JButton BtCadFuncionario;
    private javax.swing.JButton BtCadPessoa;
    private javax.swing.JButton BtCadProduto;
    private javax.swing.JButton BtCadServico;
    private javax.swing.JButton BtCancelar;
    private javax.swing.JButton BtGravar;
    private javax.swing.JButton BtIncluir;
    private javax.swing.JButton BtIncluirProdutoTabela;
    private javax.swing.JButton BtIncluirServTabela;
    private javax.swing.JButton BtPesqCondicaoPgto;
    private javax.swing.JButton BtPesqFuncionario;
    private javax.swing.JButton BtPesqPessoa;
    private javax.swing.JButton BtPesqProduto;
    private javax.swing.JButton BtPesqServico;
    private javax.swing.JButton BtRemoverProdutoTabela;
    private javax.swing.JButton BtRemoverServTabela;
    private javax.swing.JComboBox CbPessoa;
    private javax.swing.JCheckBox CbPromocao;
    private javax.swing.JCheckBox CbPromocaoServ;
    private javax.swing.JLabel LbCodPessoa;
    private javax.swing.JLabel LbNomePessoa;
    private javax.swing.JLabel LbNotificacao;
    private javax.swing.JPanel PnBotoes;
    private javax.swing.JTable TbProdutos;
    private javax.swing.JTable TbServicos;
    private javax.swing.JTextField TfCodCondicaoPgto;
    private javax.swing.JTextField TfCodFuncionario;
    private javax.swing.JTextField TfCodPessoa;
    private javax.swing.JTextField TfCodProduto;
    private javax.swing.JTextField TfCodServico;
    private javax.swing.JTextField TfCodigo;
    private javax.swing.JTextField TfCondicaoPgto;
    private javax.swing.JFormattedTextField TfData;
    private javax.swing.JTextField TfDescOperacao;
    private JNumberField.JNumberField TfDesconto;
    private JNumberField.JNumberField TfDescontoServ;
    private javax.swing.JTextField TfFuncionario;
    private javax.swing.JTextField TfPessoa;
    private javax.swing.JTextField TfProduto;
    private JNumberField.JNumberField TfQuantidade;
    private JNumberField.JNumberField TfQuantidadeServ;
    private javax.swing.JTextField TfServico;
    private JNumberField.JNumberField TfValorProduto;
    private JNumberField.JNumberField TfValorServ;
    private JNumberField.JNumberField TfValorTotalOperacao;
    private JNumberField.JNumberField TfValorTotalOperacaoServ;
    private JNumberField.JNumberField TfValorUnitario;
    private JNumberField.JNumberField TfValorUnitarioServ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

    public void analisausuario() {
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            getTelasusuario().getTela().setCodigo(1);
            if (!getTelasusuario().eadmintela()) {
                BtCadPessoa.setVisible(false);
            } else {
                BtCadPessoa.setVisible(true);
            }
        } else {
            getTelasusuario().getTela().setCodigo(2);
            if (!getTelasusuario().eadmintela()) {
                BtCadPessoa.setVisible(false);
            } else {
                BtCadPessoa.setVisible(true);
            }
        }

        getTelasusuario().getTela().setCodigo(3);
        if (!getTelasusuario().eadmintela()) {
            BtCadFuncionario.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(11);
        if (!getTelasusuario().eadmintela()) {
            BtCadProduto.setVisible(false);
        }

        getTelasusuario().getTela().setCodigo(6);
        if (!getTelasusuario().eadmintela()) {
            BtCadCondicaoPgto.setVisible(false);
        }
    }

    public void atualizavalortotal() {
        float valor = 0;
        for (int i = 0; i < TbProdutos.getRowCount(); i++) {
            TfValorTotalOperacao.setText(TbProdutos.getValueAt(i, 6).toString());
            valor = valor + Float.parseFloat(TfValorTotalOperacao.getValue().toString());
        }
        TfValorTotalOperacao.setValue(BigDecimal.valueOf(valor));
    }
    
    public void atualizavalortotalserv() {
        float valor = 0;
        for (int i = 0; i < TbServicos.getRowCount(); i++) {
            TfValorTotalOperacaoServ.setText(TbServicos.getValueAt(i, 6).toString());
            valor = valor + Float.parseFloat(TfValorTotalOperacaoServ.getValue().toString());
        }
        TfValorTotalOperacaoServ.setValue(BigDecimal.valueOf(valor));
    }

    public boolean camposobrigatoriospreenchidos() {
        if (TfDescOperacao.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Digite a descrição desta operação!");
            TfDescOperacao.grabFocus();
            return false;
        }
        if (TfCodFuncionario.getText().equals("") || TfFuncionario.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira o Funcionário que está realizando o antendimento nesta operação!");
            TfCodFuncionario.grabFocus();
            return false;
        }
        if (TfCodPessoa.getText().equals("") || TfPessoa.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira qual a pessoa envolvida nesta operação!");
            TfCodPessoa.grabFocus();
            return false;
        }
        if (TfCodCondicaoPgto.getText().equals("") || TfCondicaoPgto.getText().equals("")) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira a condição de pagamento escolhida para esta operação!");
            TfCodCondicaoPgto.grabFocus();
            return false;
        }
        if (TbProdutos.getRowCount() < 1 && TbServicos.getRowCount() < 1) {
            msg.CampoObrigatorioNaoPreenchido(LbNotificacao, "Insira os produtos ou serviços que fazem parte desta operação!");
            
            return false;
        }
        return true;
    }

    public void enviardados() {
        prodcompravenda.getCompravenda().setData(datas.retornadataehora());
        prodcompravenda.getCompravenda().setDescricao(prodcompravenda.getCompravenda().getOperacao().getDescricao() + " NRO. " + TfCodigo.getText() + " - " + TfDescOperacao.getText());
        if (CbPessoa.getSelectedItem().toString().equals("Cliente")) {
            cliente.setCodigo(Integer.parseInt(TfCodPessoa.getText()));
            prodcompravenda.getCompravenda().setCodigopessoa(cliente.retornacodigopessoacliente());
        } else {
            prodcompravenda.getForneproduto().getFornecedor().setCodigo(Integer.parseInt(TfCodPessoa.getText()));
            prodcompravenda.getCompravenda().setCodigopessoa(prodcompravenda.getForneproduto().getFornecedor().retornacodigopessoafornecedor());
        }
        prodcompravenda.getCompravenda().getFuncionario().setCodigo(Integer.parseInt(TfCodFuncionario.getText()));
    }

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseTelasUsuario getTelasusuario() {
        return telasusuario;
    }

    public void setTelasusuario(ClasseTelasUsuario telasusuario) {
        this.telasusuario = telasusuario;
    }
}
