/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.lojadafatima.InterfaceConsultaSimples;

import br.com.lojadafatima.ClassesFerramentas.NaoPermiteAspasSimples;
import br.com.lojadafatima.ClassesFerramentas.PermiteApenasNumeros;
import br.com.lojadafatima.ClassesFerramentas.PermiteNumerosPontoBarra;
import br.com.lojadafatima.ClassesFerramentas.Preenche;
import br.com.lojadafatima.Pessoa.ClasseCliente;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;

/**
 *
 * @author hp
 */
public class ConsulSimplesCliente extends javax.swing.JDialog {

    private java.awt.Frame primeiratela;
    private ClasseCliente cliente = new ClasseCliente();
    Preenche preenche = new Preenche();
    
    public ConsulSimplesCliente(java.awt.Frame telaorigem, boolean modal, ClasseCliente cli) {
        super(telaorigem, modal);
        setPrimeiratela(telaorigem);
        setCliente(cli);
        initComponents();
        CbPesquisa.setSelectedIndex(0);
        CbPesquisa2.setSelectedIndex(0);
        TbPesquisa.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CbPesquisa = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        CbPesquisa2 = new javax.swing.JComboBox();
        TfPesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPesquisa = new javax.swing.JTable();
        BtPesquisa = new javax.swing.JButton();
        BtSelecionar = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Consulta Rápida de Cliente - Software Loja da Fátima");

        CbPesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Geral", "Codigo", "Nome/Nome Fantasia", "CPF/CNPJ" }));
        CbPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CbPesquisaActionPerformed(evt);
            }
        });

        jLabel19.setText("Filtro da Pesquisa");

        TfPesquisa.setEditable(false);

        TbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome/Nome Fantasia", "CPF/CNPJ", "Data do Cadastro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TbPesquisa.getTableHeader().setReorderingAllowed(false);
        TbPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbPesquisaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbPesquisa);

        BtPesquisa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/buscar.png"))); // NOI18N
        BtPesquisa.setText("Pesquisar");
        BtPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtPesquisaActionPerformed(evt);
            }
        });

        BtSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/sucesso2.png"))); // NOI18N
        BtSelecionar.setText("Selecionar");
        BtSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtSelecionarActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/lojadafatima/Icones/cancelar.png"))); // NOI18N
        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(CbPesquisa, 0, 188, Short.MAX_VALUE)
                                .addComponent(CbPesquisa2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(TfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(BtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jLabel19)
                        .addComponent(jScrollPane1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BtSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CbPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TfPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtPesquisa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CbPesquisa2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 51, Short.MAX_VALUE)
                    .addComponent(BtSelecionar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CbPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CbPesquisaActionPerformed
        switch (CbPesquisa.getSelectedIndex()) {
            case 0: {
                CbPesquisa2.setEnabled(true);
                TfPesquisa.setEditable(false);
                CbPesquisa2.removeAllItems();
                CbPesquisa2.addItem("");
                CbPesquisa2.addItem("Pessoa Fisica");
                CbPesquisa2.addItem("Pessoa Juridica");
                TfPesquisa.setDocument(new NaoPermiteAspasSimples());
                break;
            }
            case 1: {
                CbPesquisa2.setEnabled(false);
                TfPesquisa.setEditable(true);
                CbPesquisa2.removeAllItems();
                CbPesquisa2.addItem("");
                TfPesquisa.setDocument(new PermiteApenasNumeros());
                break;
            }
            case 2: {
                CbPesquisa2.setEnabled(true);
                TfPesquisa.setEditable(true);
                CbPesquisa2.removeAllItems();
                CbPesquisa2.addItem("");
                CbPesquisa2.addItem("Pessoa Fisica");
                CbPesquisa2.addItem("Pessoa Juridica");
                TfPesquisa.setDocument(new NaoPermiteAspasSimples());
                break;
            }
            case 3: {
                CbPesquisa2.setEnabled(true);
                TfPesquisa.setEditable(true);
                CbPesquisa2.removeAllItems();
                CbPesquisa2.addItem("");
                CbPesquisa2.addItem("CPF");
                CbPesquisa2.addItem("CNPJ");
                TfPesquisa.setDocument(new PermiteNumerosPontoBarra());
                break;
            }
        }
    }//GEN-LAST:event_CbPesquisaActionPerformed

    private void BtPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtPesquisaActionPerformed
        int[] parametro = new int[4];
        parametro[0] = 70;
        parametro[1] = 300;
        parametro[2] = 100;
        parametro[3] = 70;
        preenche.FormataJtable(TbPesquisa, parametro);

        switch (CbPesquisa.getSelectedIndex()) {
            case 0: {
                switch (CbPesquisa2.getSelectedIndex()) {
                    case 0: {
                        preenche.PreencherJtable(TbPesquisa, getCliente().consultageral());
                        break;
                    }
                    case 1: {
                        preenche.PreencherJtable(TbPesquisa, getCliente().consultageralpessoafisica());
                        break;
                    }
                    case 2: {
                        preenche.PreencherJtable(TbPesquisa, getCliente().consultageralpessoajuridica());
                        break;
                    }
                }
                break;
            }
            case 1: {
                if (TfPesquisa.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Digite o código do cliente que deseja consultar!", "Digite o código", JOptionPane.INFORMATION_MESSAGE);
                    TfPesquisa.grabFocus();
                } else {
                    getCliente().setCodigo(Integer.parseInt(TfPesquisa.getText()));
                    preenche.PreencherJtable(TbPesquisa, getCliente().consultacodigo());
                }
                break;
            }
            case 2: {
                switch (CbPesquisa2.getSelectedIndex()) {
                    case 0: {
                        if (TfPesquisa.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Digite o nome/nome fantasia do cliente que deseja consultar!", "Digite o nome", JOptionPane.INFORMATION_MESSAGE);
                            TfPesquisa.grabFocus();
                        } else {
                            preenche.PreencherJtable(TbPesquisa, getCliente().consultadescricaogeral(TfPesquisa.getText().toUpperCase()));
                        }
                        break;
                    }
                    case 1: {
                        if (TfPesquisa.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Digite o nome do cliente que deseja consultar!", "Digite o nome", JOptionPane.INFORMATION_MESSAGE);
                            TfPesquisa.grabFocus();
                        } else {
                            preenche.PreencherJtable(TbPesquisa, getCliente().consultadescricaofisica(TfPesquisa.getText().toUpperCase()));
                        }
                        break;
                    }
                    case 2: {
                        if (TfPesquisa.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Digite o nome fantasia do cliente que deseja consultar!", "Digite o nome", JOptionPane.INFORMATION_MESSAGE);
                            TfPesquisa.grabFocus();
                        } else {
                            preenche.PreencherJtable(TbPesquisa, getCliente().consultadescricaojuridica(TfPesquisa.getText().toUpperCase()));
                        }
                        break;
                    }
                }
                break;
            }
            case 3: {
                switch (CbPesquisa2.getSelectedIndex()) {
                    case 0: {
                        if (TfPesquisa.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Digite o CPF/CNPJ do cliente que deseja consultar!", "Digite o CPF/CNPJ", JOptionPane.INFORMATION_MESSAGE);
                            TfPesquisa.grabFocus();
                        } else {
                            preenche.PreencherJtable(TbPesquisa, getCliente().consultaCPFouCNPJ(TfPesquisa.getText()));
                        }
                        break;
                    }
                    case 1: {
                        if (TfPesquisa.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Digite o CPF do cliente que deseja consultar!", "Digite o CPF", JOptionPane.INFORMATION_MESSAGE);
                            TfPesquisa.grabFocus();
                        } else {
                            preenche.PreencherJtable(TbPesquisa, getCliente().consultaCPF(TfPesquisa.getText()));
                        }
                        break;
                    }
                    case 2: {
                        if (TfPesquisa.getText().equals("")) {
                            JOptionPane.showMessageDialog(null, "Digite o CNPJ do cliente que deseja consultar!", "Digite o CNPJ", JOptionPane.INFORMATION_MESSAGE);
                            TfPesquisa.grabFocus();
                        } else {
                            preenche.PreencherJtable(TbPesquisa, getCliente().consultaCNPJ(TfPesquisa.getText()));
                        }
                        break;
                    }
                }
                break;
            }
        }
    }//GEN-LAST:event_BtPesquisaActionPerformed

    private void TbPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbPesquisaMouseClicked
        if(TbPesquisa.getSelectedRow() > -1){
            getCliente().setCodigo(Integer.parseInt(TbPesquisa.getValueAt(TbPesquisa.getSelectedRow(), 0).toString()));
        }
    }//GEN-LAST:event_TbPesquisaMouseClicked

    private void BtSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtSelecionarActionPerformed
        if(TbPesquisa.getSelectedRow() > -1){
            dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Selecione um cliente para retornar para a tela anterior!", "A pesquisa não retornou valores", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_BtSelecionarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        getCliente().setCodigo(0);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtPesquisa;
    private javax.swing.JButton BtSelecionar;
    private javax.swing.JComboBox CbPesquisa;
    private javax.swing.JComboBox CbPesquisa2;
    private javax.swing.JTable TbPesquisa;
    private javax.swing.JTextField TfPesquisa;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    public java.awt.Frame getPrimeiratela() {
        return primeiratela;
    }

    public void setPrimeiratela(java.awt.Frame primeiratela) {
        this.primeiratela = primeiratela;
    }

    public ClasseCliente getCliente() {
        return cliente;
    }

    public void setCliente(ClasseCliente cliente) {
        this.cliente = cliente;
    }
}
